### ISSUE TITLE
2.2.1 GPX Importer

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#101]
The clients regularly receive data in GPX format, including from:
* GPS Wristwatches
* GPS Trackers temporarily attached to smaller ships
* Some types of fixed-wing aircraft

I believe it's possible to represent tracks in GPX in a range of structure, so we'll have to start off by supporting our sample data-files.  I'll do a quick look for sample data on the Internet, and include some links in this issue.

**Comment by robintw** [comment]
I've started looking into this today, and have a few questions - probably mostly fairly simple ones:

1. GPX files are XML files, which means we'll need to parse with a XML parser. There are two consequences to this:
    a) We should install a XML parsing library - [lxml](https://lxml.de/) is generally considered a good one. Are you happy for me to add this to the `requirements.txt` file?
    b) I don't think we'll easily be able to record the location of tokens in the file for use with the extraction highlighter API. Is this a problem? If so, we might be able to get around it - but I imagine the extraction highlighter isn't such an issue for highly structured data like XML.
    
2. What is `platform_type="Fisher"` in the following code (taken from the E-Trac parser), and do I need to set it to a different value? At the moment it seems as if we're assuming the platform is a UK platform - will there be a way for the user to change this via the CLI or the interactive resolver?

```
platform = data_store.get_platform(
                    platform_name=vessel_name,
                    nationality="UK",
                    platform_type="Fisher",
                    privacy="Public",
                )
```

3. What sensor name do you want for the sensor that creates the GPX data? For the E-TRAC importer we just use:

```
sensor = platform.get_sensor(
                    session=data_store.session,
                    all_sensors=all_sensors,
                    sensor_name="E-Trac",
                    sensor_type="GPS",
                    privacy="TEST",
                )
```

4. The example GPX files (https://github.com/debrief/pepys-import/pull/100/files) all have a single track (<trk>) element inside them, which seems to be associated with a single platform. Would you like me to design the code to accept GPX files with multiple tracks for multiple platforms in them?

**Comment by IanMayo** [comment]
1a. Parser, sure - add your favorite
1b. Highlighter: I agree, we won't support highlighting (well, not without worrying our own parser)
2,3 : well have to talk through those, but I think it's most likely that you'll pass None, and leave it for the use to complete (via the resolver)
4. Yes please - let's support multi segment legs.
