### ISSUE TITLE
User Support - loading platforms

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#1021]
> .. ideally I would like to go via the quickest means to update the participants tables rather than adding them one at a time – uploading a table as I did in the early days.  Is this still doable in the new versions of Pepys? If so, can you please write me, for the team, a step wise guide to upload a table with a list of additional/ new participants, that will update the participants table in Pepys.

The analysts have a list of new platforms to add to Pepys, probably non-UK ships. They would like a reminder of how to do this.  I can offer:
* Here is a blank CSV file containing the relevant headings, plus a list of platform types.
* Fill in one row per new platform. For Nationality use the full country name. For platform-type use one of those in the attached CSV file
* Once the CSV is complete, navigate to `..../Tools/Pepys/Current/pepys_import/database/default_data`
* There will be other `.csv` files in that folder.  Pepys will import any with a proper pepys table name for the first part of the filename.  So, if there is already a `platforms.csv` present, rename it to `platforms_old.csv` - the same for any other files
* Paste the new `platforms.csv` into that folder
* From the start menu, enter `Pepys Admin`
* First check how many platforms are currently loaded. Select `(2) Status`. Take note of how many platforms are loaded.
* Now import the new platforms as follows:
* Select `(1) Initialise / Clear`
* Select `(5) Import Metadata`
* The new platforms will be loaded.
* Finally select `(.) Back` and `(2) Status` again, to verify the new platforms are loaded.

**Comment by IanMayo** [comment]
@robintw - would you mind reviewing the above steps please?

**Comment by robintw** [comment]
That all looks good.

(One step says `If there is a current file in there called` and doesn't seem to be complete - but everything else looks good)

**Comment by IanMayo** [comment]
Job complete.
