### ISSUE TITLE
Performance delay loading Platforms in Maintenance UI

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#1036]
If this is unavoidable, then c'est la view, but...

I entered Maintenance UI of `pepys-admin` multiple times while doing benchmarking.  To get rid of recent test data I had to separately delete the datafile and the platform that's ok.  When I selected `datafiles` the page opened instantly - even though there are lots of them.  But, when I selected `platforms` there was a 20 second delay.

I don't know if we can optimise what's happening there - I guess it's pulling data out of other tables to de-normalise the data for easier working.  

But, if we could remove the delay it would improve the user experience.

**Comment by robintw** [comment]
I've just been down a rabbit hole with this, and have managed to speed it up significantly. I need to check that the new code actually does the same as the old code, but it's looking promising.

I must stop work for the day now though - will continue on Mon.
