### ISSUE TITLE
Delay when entering `Maintain Tasks`

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#1037]
In testing the timeline, I was in & out of Maintain Tasks a lot.

Each time I entered it took 25 seconds for `Initialising GUI and loading  tasks and platforms` to complete.

The analysts have:
* 1 Series
* 1 Wargame
* About 15 serials
* Up to 8 participants per serial

This doesn't seem a lot of data, though I presume some de-normalisation is going on.

**Comment by robintw** [comment]
I've looked into the code, and I don't think there's much we can do to improve this. We're loading all of the data, including various bits of denormalisation, but we need all of that data to be able to display in the GUI when we're not connected to the database (the main GUI display loop doesn't hold an open connection to the database, we only start a database session when we actually edit something).

There might be something we could do with a complete restructure of the code, but I suspect that #1038 would be easier to improve first.

**Comment by robintw** [comment]
Actually, there may be something we can do here. A few notes for 'future me':

- On startup of the GUI, we could load with a `lazyload` for various attributes - eg `lazyload("child_wargames.participants"), lazyload("child_wargames.child_serials")` which would be quicker
- Inside `handle_tree_select` we then check the type of the object, join it back to the session, load the particular attributes of interest and then expunge again
- (I can't seem to find a function that loads all the attributes on the object, to call before expunging - so we may need to access these parameters manually)

**Comment by IanMayo** [comment]
I don't think this is a particularly high priority.  I _Think_ analysts will tend to enter `maintain tasks` and stay in there - rather than pop in & out.

**Comment by IanMayo** [comment]
Close.  As I said - they will tend to stay in `maintain tasks`, rather than drop in & out.  So, the `cost` isn't encountered very often.
