### ISSUE TITLE
Investigate database and network access speed at clients

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#1038]
## 🐞 Overview
A number of recent issues have been about delays or slow speeds when using Pepys. Some of these have been because of inefficiencies in the Pepys code, but there seems to be an underlying slowness about the database access at the clients which we don't seem to see on our dev machines - even when connecting to a remote Postgres server across the internet.

In collaboration with the clients, we should investigate this a bit more. It could be there is some sort of network bottleneck that they can do something about, or it could be that their Postgres server is particularly slow, poorly resourced (RAM etc), or poorly configured (if it's just been installed with the default settings and is being used concurrently by a number of users...).

**Comment by robintw** [comment]
This has been partly achieved by discussing with the tech support team at the clients, and getting the Postgres server upgraded from 4Gb RAM to 16Gb RAM. I still think there are some issues, as a lot of operations for them are _way, way_ slower than they are for us - even when accessing TracStor over the internet.

**Comment by IanMayo** [comment]
Going to close this.  Unless we find a _suitable candidate_ with postgres tuning skills we aren't going to be able to sit someone at a terminal on their network.  Our alternative strategy is that we'll address bottlenecks as we encounter them.

**Comment by IanMayo** [comment]
Some other performance tips here: https://github.com/debrief/pepys-import/pull/1049#issuecomment-932391221
