### ISSUE TITLE
Visit plan - 1st October

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#1054]
* unpack zips into temporary folders
* start with Link11 import
    * config pepys to send to SQLite file
    * find folder of test data
    * load folder of data, answering lots of questions
    * check sqlite data looks right
* move onto performance improvement zip
    * check performance in `Maintain Data` page - opening states table, platforms table, others
* look at timeline, check if any quad-graphs are incorrect. Check if missing from database.  #1012
* look at timeline, check for daylight-savings issues. _Maybe_ create mock wargame if necessary.
* Try to see locate/view some ORCA data

**Comment by IanMayo** [comment]
Notes: trying to load folder of files didn't work.   Now trying to load single file (GEV08)

Error at link_16_importer.py. ValueError: could not convert string to float ("15:24.602"). I've opened the CSV in notepad, and the second column actually contains the full time:  `16:15:24.602`.  The time component of the filename is `T16-15-06`.

It _looks like_ the presence of milliseconds in the CSV date-time persuades MS-Excel to hide the hours.  But, they are present in the file.

**Comment by mew-nsc** [comment]
That's interesting. The REP parser seems to have been created with the MM:SS:MS timestamp in mind. Are the ones with HH:MM:SS:MS format at least internally consistent?

**Comment by IanMayo** [comment]
Next issue. Line 120. 
```TypeError: unsupported operand type(s) for +=@ 'datetime.timedelta' and 'bool'```

The above is because `self.base_timestamp` is `false`.

**Comment by IanMayo** [comment]
Yes - the files are internally consistent - they stick with one of the two time formats.

**Comment by mew-nsc** [comment]
> Format of filename is `GEV_DD_MM_YYYYThh-mm-ss_ii-ii.raw-PPLI_201.csv` Other sample format of V1 is: `GEV_DD-HH-YYYYThh-mm-ss.raw-PPLI_201.csv`
> 
> I _guess we have to look for the date-time in the string - since there could be unknown guff before or after it.

I did wonder if there might be something after the date/time stamp. That would have been too easy...
