### ISSUE TITLE
Help Texts table is empty.

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#1095]
I called in to perform a manual database change to fix [this](https://github.com/debrief/pepys-import/pull/1088/commits/815d59d40d9c7861e311f90cac5b5010df964991#diff-9e84bcf1c69edf7b6b02fc55e9c0691dd97516edabb3e7a5aaedfed7ac2c8354)

But, on the main network, the 'help texts' table on Postgres is empty.

When I config with a local sqlite database it gets populated
correctly, but the master PostGres one is empty.

I guess I need to:
* rename the default CSV files so only 'help texts' matches the expect
file structure
* update Help Text in `.csv` as described in link above
* run 'import reference data' in Pepys-Admin

Do you think that would handle it @robintw ?

**Comment by robintw** [comment]
Yes, that should work @IanMayo. Not sure why it's empty...that's strange.

**Comment by IanMayo** [comment]
Done. Moved all CSV files (other than help text) into a tmp folder, ran `load reference data` , and it's all ok.
