### ISSUE TITLE
Jupyter Notebook File Failing

### ISSUE THREAD

**Issue by BarisSari** [debrief/pepys-import#11]
When the jupyter notebook file tried to run (**_/examples/notebooks/data_store_sqlite.ipynb_**) , it throws the following error:
```
OperationalError: (sqlite3.OperationalError) no such table: Datafiles
[SQL: SELECT "Datafiles".datafile_id AS "Datafiles_datafile_id", "Datafiles".simulated AS "Datafiles_simulated", "Datafiles".reference AS "Datafiles_reference", "Datafiles".url AS "Datafiles_url", "Datafiles".privacy_id AS "Datafiles_privacy_id", "Datafiles".datafile_type_id AS "Datafiles_datafile_type_id" 
FROM "Datafiles" 
WHERE "Datafiles".reference = ?
 LIMIT ? OFFSET ?]
[parameters: ('../repl_files/missing_platform.rep', 1, 0)]
```
![Screenshot from 2019-11-07 13-33-51](https://user-images.githubusercontent.com/41292272/68381854-97e55280-0163-11ea-8604-24e894241c39.png)

We should examine and fix it.

**Comment by IanMayo** [comment]
Could the issue be because we still need to initialise the database?  That would explain why the `Datafiles` table isn't there.

**Comment by BarisSari** [comment]
> Could the issue be because we still need to initialise the database? That would explain why the `Datafiles` table isn't there.

Yes, it was the first issue. But then, many other issues popped up.
