### ISSUE TITLE
Introduce depth/elevation data in NMEA sample file

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#117]
NMEA data can include depth, formatted like this:
```
$POSL,PDS,9.2,M*0
```
We should determine:
* units
* is it depth or elevation?

Once the above are resolved, we should insert some sample depth data into the `NMEA_Trial.log`.

**Comment by robintw** [comment]
@IanMayo Are you able to find out units and whether it's depth/elevation, then I can update the parser.

**Comment by IanMayo** [comment]
Yes, it's certainly depth in metres.
