### ISSUE TITLE
2.2.3 Local Parsers/Tests

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#122]
There will be two types of parsers/QA-tests:
1. core ones, supplied with pepys-import
2. local ones, supplied/maintained by peyps-import users

The second category covers file formats that are private to the clients, or which require very frequent modification (due to the fragility of data-files that are entered by hand).

We will support local implementations through a series of environmental variables - the `PEPYS_LOCAL_xxx` vars defined in #119 .  At the relevant point in `file_processor.py` we will check for the presence of either environmental variable.  If the variable is present, then the files in that folder will be processed, and added to the core ones provided by pepys-import.

I've realised that the clients may wish to replace some of our parsers with their own.  This _could_ be supported by Pepys dynamically loading its own parsers, in addition to the local ones.  So, some _expert user_ could go into the Pepys folder and move a parser to their local folder, and apply the fix (or relaxation of some test).

**Comment by BarisSari** [comment]
Hi @IanMayo . I have a few questions. In our core importers, we create classes that inherit our abstract `Importer` class. Will the users follow the same strategy? Currently, I'm separating classes of a module by checking if it's a subclass of Importer and a concrete class. If they will have different strategies, I should change it. 

On the other hand, if they will create a base importer for their parsers, it might cause some problems with imports. I think we should be more restricted about local parsers even though I don't have any clear idea about it.
