### ISSUE TITLE
Trouble running scripts from network share

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#124]
I copied `pepys_import` to a folder in a network share. This share appears to all users as their `M:` drive.

But, when I ran `create_shortcuts.bat`, I got a security warning: `Open file -security warning.` `This file is in a location outside your local network`.

I said to run anyway.  Then the PowerShell script displayed a similar test-warning within the CLI shell, giving me the choice to `Do not run` `Run anyway` `something else...`.

The shortcuts got copied to the correct `Send to` location.  But, when I right-clicked to `Send to Pepys (persistent)` I got the warning again.

It appears we need to add the server(s) hosting the `M:` drive to the Internet Explorer trusted domains listing.

This does not seem to introduce a security risk, since the drive's are still within the LAN.

**Comment by IanMayo** [comment]
I've just tried to reproduce this on my MS-Windows VM, by putting the `.bat` files on a mapped MACOS drive.  But, it's treated as `trusted`- and _just runs_.

**Comment by robintw** [comment]
Yes, I think this is a configuration issue with their LAN and nothing that we can do anything about - they'll have to sort it, unfortunately.

**Comment by IanMayo** [comment]
Two users ran the scripts today without the warnings shown.

_Maybe_ it's specific to my account on that network, will investigate further onsite. Closing issue.
