### ISSUE TITLE
7.2.1 PostGIS deployment

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#136]
* [x] PostGIS installed on network
* [x] Pepys database present in PostGIS
* [x] Pepys user account defined for PostGIS
* [x] Pepys installed on shared drive
* [x] Database config file produced for PostGIS (in shared drive)
* [x] Environment variable configured to point to config file

Update sequence
* [ ] Download/verify/transfer
* [ ] Archive current version (in shared folder)
* [ ] Unpack new version to shared folder
* [ ] Select `Pepys-Admin` from `Start Menu`. If not present click on `bin\install_pepys.bat`, and try again
* [ ] Go into menu, select `Migrate` to update database Schema as necessary

**Comment by robintw** [comment]
I think the update steps are now documented at https://pepys-import.readthedocs.io/en/latest/installation.html - let me know if these need more detail or separating from the installation (although they overlap almost 100%!)

**Comment by robintw** [comment]
I think this is now sorted, as the client has a Postgres database configured and set up correctly.
