### ISSUE TITLE
Sort & Refactor Imports

### ISSUE THREAD

**Issue by BarisSari** [debrief/pepys-import#144]
During the development of the project, we are adding new imports when they are necessary. As far as I observed, we don't think about the order of imports or types of imports(absolute, relative, etc.). According to PEP-8, absolute imports are recommended if your package layout is not too complex:

> Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on sys.path)

It also [mentions](https://www.python.org/dev/peps/pep-0008/#imports) the order of imports. We can use `isort` library to refactor imports. I was thinking to include it to pre-commit but it sometimes causes conflicts with `black`. Therefore, we can use it from time to time to have better imports.

This is a low priority task that aims to enhance our imports.

**Comment by IanMayo** [comment]
Good suggestion, I welcome it.

This seems to be a flake8 extension that checks the order: https://github.com/PyCQA/flake8-import-order

_Maybe_ run `isort` as a one-off across the whole repo, but I'd be quite happy for black/flake8 to check it from then onwards.
