### ISSUE TITLE
Change Flake8 & Black Character Length

### ISSUE THREAD

**Issue by BarisSari** [debrief/pepys-import#145]
Maybe I couldn't find it, but I don't see the flake8 config in the repository anymore. If we are going to use the 100 character limit, we should declare it in a config file and adapt our black commands according to that.

This is a low priority task that aims to enhance code reading and review.

**Comment by IanMayo** [comment]
The settings are in `setup.cfg`:  https://github.com/debrief/pepys-import/blob/develop/setup.cfg#L17

VS-Code reads them from there, I _hope_ black does too.

**Comment by BarisSari** [comment]
Apparently, it doesn't support `setup.cfg`: https://github.com/psf/black/issues/683

My IDE wasn't configured according to that, either. I think we should pass the line-length parameter to Black to make it compatible with our Flake8 configuration.
