### ISSUE TITLE
Speed Unit Failing

### ISSUE THREAD

**Issue by BarisSari** [debrief/pepys-import#15]
When a new object tried to push to **State** table, _speed_ attribute causes the following error:

![Screenshot from 2019-11-07 15-27-23](https://user-images.githubusercontent.com/41292272/68389082-2d3c1300-0173-11ea-940e-7215b76e9f11.png)

![Screenshot from 2019-11-07 15-29-21](https://user-images.githubusercontent.com/41292272/68389186-6a080a00-0173-11ea-943c-4c3ae5a7ac35.png)

**Comment by IanMayo** [comment]
Ok, that's almost certainly because we've introduced `pint` quantities.

@tahirs95 should be the man to fix this :-)

**Comment by IanMayo** [comment]
@BarisSari - I can't find `local_file.py` is it in a branch?

**Comment by BarisSari** [comment]
It is actually the same code with jupyter notebook file (experiments/notebooks). But I haven't pushed it to any branch

**Comment by IanMayo** [comment]
Aah, I see :-)

**Comment by IanMayo** [comment]
I'm taking this issue on.  It highlights an important hole in the testing.
