### ISSUE TITLE
Over-relaxed importer catching .DS_Store files

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#162]
@robintw has indicated that Pepys is trying to process MacOS `.DS_Store` files.

We should identify the importer, and make the tests more strict.

**Comment by robintw** [comment]
This is also a bit broader than this: we're trying to load the output and error log files that we produce as part of running the import. This then means that we're trying to import the output log of the error log of the original file...which gets crazy and eventually overruns the field length in the database for the datafile name.
