### ISSUE TITLE
Add some way for the user to find where in the input file the validator found a problem

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#166]
At the moment the validators report problems, but don't say _where_ the problem was found. I'm aware that we probably don't have the line number for the location where the error was found (because we're in the validator rather than the parser, and so don't know anything about line numbers) - but could we include the timestamp, so the user can look through the file and find the right location by looking for the right timestamp value?

**Comment by IanMayo** [comment]
> include the timestamp

Yes, good idea.  Maybe the platform and sensor too, in case the file has data from several platforms.

**Comment by robintw** [comment]
Probably best for you to do this @BarisSari, as you're most familiar with the error reporting code

**Comment by BarisSari** [comment]
Sure, I can do that.
