### ISSUE TITLE
Extract common parts of load_this_file method into superclass

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#168]
All of the importers have a `load_this_file` method that starts with code like:

```
        self.errors = list()
        basename = os.path.basename(path)
        print(f"GPX parser working on {basename}")
        error_type = self.short_name + f" - Parsing error on {basename}"
        prev_location = None
        datafile.measurements[self.short_name] = list()
```

This could be extracted into the base class, and just called from there - to save work (and mistakes) for clients writing parsers.

_However_ this would mean that the `Importer` class was no longer an Abstract Base Class - are you happy for me to change this @IanMayo? Basically we'd actually be having a bit of functionality in the `Importer` class.

**Comment by IanMayo** [comment]
Yes, that's a great example of pushing logic into our code, and reducing the load on the parser-maintainers.
