### ISSUE TITLE
Tests are getting slow - what can we do about this?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#169]
It's getting quite slow to run the full test suite now - it took around 8-9 minutes for me recently.

I think we should try and reduce this where we can, without making the tests less useful.

A few ideas:

1. We could reduce the size of some of the import files. For example, the NMEA example file is very large and takes almost two minutes to import by itself. @IanMayo If you're happy with this idea then as you know the format, could you reduce the length of this file and commit a new version?

2. We could mark some tests as slow, so we can easily run a subset that doesn't take very long. In general, the PostGIS tests are slow, and the 'import everything and check it doesn't raise an exception' tests are slow. We can do this using pytest marks (see [here](https://docs.pytest.org/en/latest/mark.html#mark).

**Comment by robintw** [comment]
I found a way to find the slowest tests, by running `pytest --durations=10`

```
110.30s call     tests/test_importers_postgis.py::SampleImporterTestCase::test_process_folders_descending
85.57s call     tests/test_importers.py::SampleImporterTests::test_process_folders_descending_in_memory
81.58s call     tests/test_importers.py::SampleImporterTests::test_process_folders_descending
76.72s call     tests/test_load_nmea.py::TestLoadNMEA::test_load_NMEA_data
8.14s call     tests/test_data_store_api_postgis.py::DataStoreStatusTestCase::test_get_status_of_reference
5.56s call     tests/test_data_store_api_postgis.py::PlatformAndDatafileTestCase::test_find_platform
4.98s call     tests/test_data_store_api_postgis.py::SensorTestCase::test_find_sensor
4.78s call     tests/test_data_store_api_postgis.py::SensorTestCase::test_find_sensor_synonym
4.68s call     tests/test_data_store_api_postgis.py::PlatformAndDatafileTestCase::test_find_platform_synonym
4.65s call     tests/test_data_store_api_postgis.py::DataStoreStatusTestCase::test_get_status_of_measurement
```

**Comment by IanMayo** [comment]
@robintw - I'm keen to learn more about the how this "cost" affects us, i.e. the impact on you of the ~10 minute test-suite.

Are you running the test-suite very frequently on your local machine, to prevent regressions?  Or is the impact the wait while Travis is verifying the build?

**Comment by robintw** [comment]
Yeah I've been running it quite frequently on my local machine, mainly because a lot of the work I've been doing recently has been touching things that are used across the code-base, and so I've been breaking things across a wide range of tests. I also find it nicer to run locally as I can drop into a debugger if needed.

It's not a major issue to solve this - but I just thought I'd mention it.

**Comment by robintw** [comment]
This isn't so much of an issue now that I'm not doing major changes that affect the whole codebase, so I'll close for now, and we can open another issue if it becomes a problem in future.
