### ISSUE TITLE
Black isn't being run as pre-commit

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#17]
I've just made some changes, and pushed to a PR.

The PR failed because of Black issues.

I then ran black from command-line, and it fixed the stuff.

But, I was expecting it to _automatically_ run on the files.

**Comment by IanMayo** [comment]
_May_ have been my problem, not doing `pip install`

**Comment by BarisSari** [comment]
Have you installed pre-commit? `pip install pre-commit && pre-commit install`
If you do that, I think it's not possible to commit without applying Black. It should throw an error _commit failed_ and reformat files.

**Comment by IanMayo** [comment]
Sorted. `Ian` failed to run the command line config. Duh.
