### ISSUE TITLE
Extract common parts of sqlite_db and postgres_db

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#170]
We currently have two separate files (`sqlite_db.py` and `postgres_db.py`) which define the table schema for the two backend databases that we support. They need to be separate because SQLite and Postgres don't quite support the same things (eg. data types).

However, we have a number of extra functions defined on the table classes (such as `create_state` or `submit`) and these should be extracted somehow to be common between the two files.

Not really sure how to go about this - do we need to something like multiple inheritance?

**Comment by IanMayo** [comment]
I welcome input from @BarisSari on this.

**Comment by BarisSari** [comment]
I think we are all aware of the issue of duplicated codes. After a quick search, it seems to me that we can use _Mixin Classes_ and solve this issue without any problems. Please check the following link:
https://docs.sqlalchemy.org/en/13/orm/extensions/declarative/mixins.html#mixin-and-custom-base-classes

**Comment by BarisSari** [comment]
Fixed in #180
