### ISSUE TITLE
Trouble extracting data from datastore

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#176]
@tahirs95 is working on the management app, which includes the ability to export data.

But, when select queries are on the PG datastore which return `State` objects, this error is thrown:
```
  File "/Users/ian/git/pepys-import/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function st_asewkb(pepys.geometry) does not exist
LINE 1: ...s."States".sensor_id AS "pepys_States_sensor_id", ST_AsEWKB(...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[SQL: SELECT pepys."States".state_id AS "pepys_States_state_id", pepys."States".time AS "pepys_States_time", pepys."States".sensor_id AS "pepys_States_sensor_id", ST_AsEWKB(pepys."States".location) AS "pepys_States_location", pepys."States".elevation AS "pepys_States_elevation", pepys."States".heading AS "pepys_States_heading", pepys."States".course AS "pepys_States_course", pepys."States".speed AS "pepys_States_speed", pepys."States".source_id AS "pepys_States_source_id", pepys."States".privacy_id AS "pepys_States_privacy_id", pepys."States".created_date AS "pepys_States_created_date" 
FROM pepys."States" 
```
 
I've done some research.  [This](https://stackoverflow.com/questions/37233116/point-type-in-sqlalchemy/37234645) solution says to provide the object type, but we already do that.

Or, [This](https://docs.ckan.org/projects/ckanext-spatial/en/latest/install.html) solution says to double-check that PostGIS is installed.  But, if we've already inserted this spatial data into the database, then the PostGIS extensions must be present.

I'm pretty sure this issue isn't related to the admin export - it does look like its in the config of SQLAlchemy or GeoAlchemy.  Here is a call that fails:
```
datastore = DataStore(
        db_username="postgres",
        db_password="postgres",
        db_host="localhost",
        db_port=5432,
        db_name="pepys",
        welcome_text="Pepys_Admin",
    )
    with datastore.session_scope():
        measurement_summary = datastore.get_status(report_measurement=True) 
```

**Comment by robintw** [comment]
It could be a schema related issue. [This post](https://gis.stackexchange.com/questions/132103/postgis-st-within-does-not-exist) suggests it might be searching in the wrong schema for the function. Possibly this broke when we changed the schema from `public` to `pepys`? Either postgis was installed to the wrong schema, or we're loading the wrong schema to search in? Maybe?

**Comment by robintw** [comment]
Weirdly, I've just tried this using our remote test Postgres server, with exactly the code you gave (with an additional `print(measurement_summary.report())` at the end, and changing the connection details to the remote server), and it worked fine - printing a report telling me that there are 543 states stored.

Can you have a go on the remote server and see if you get the problem?

**Comment by robintw** [comment]
I've just tried on a local (permanent - not using `testing.postgresql`) Postgres server too, and everything works fine, including export using the Admin CLI.

Is it possible that there is something strange with your Postgres configuration? Have you tried with a new DB, in case you have an old or weirdly-configured schema?

For reference, I used the code below. I first ran it with the two commented lines uncommented - so that it initialised the DB and imported some GPX files - and then I ran it with those two lines commented to see the output status without changing the DB. I then tried the Admin CLI, and it didn't crash for the export - although I didn't see any exported file, just a print out of some State objects to the console.

```
from pepys_import.core.store.data_store import DataStore
from pepys_import.file.file_processor import FileProcessor
from pepys_import.file.get_importers import get_importers



datastore = DataStore(
        db_username="pepys",
        db_password="pepys",
        db_host="localhost",
        db_port=5432,
        db_name="pepys",
        welcome_text="Pepys_Import",
    )

def load_data(datastore):

    processor = FileProcessor()

    importers = get_importers()
    processor.register_importers(importers)

    processor.process('tests/sample_data/track_files/gpx', datastore, True)


#datastore.initialise()
#load_data(datastore)

with datastore.session_scope():
    measurement_summary = datastore.get_status(report_measurement=True) 
    print(measurement_summary.report())
```

**Comment by IanMayo** [comment]
Aah yes - I does run successfully against the `alwaysdata.net` remote server.  Hmm.

My issue isn't that PostGIS is in the wrong schema. The PG functions are in `pepys\Functions` and the special `spatial_ref_sys` is in the `pepys` schema:
![image](https://user-images.githubusercontent.com/1108513/76247209-14ce2900-6237-11ea-8e0a-c6d1ffe13327.png)

**Comment by IanMayo** [comment]
Yes, @robintw - deleting the database, then recreating it fixed the issue.  Thanks!

**Comment by IanMayo** [comment]
Ok, so this isn't quite clear in my mind yet, but...

* I created a blank database (PGAdmin).
* I manually inserted PostGIS: `CREATE EXTENSION postgis;`
* I manually ran this call: `select ST_AsEWKB('0101000000E41C2BE7414C35C0D8FFEF3E7D7C3640')`
* It didn't error, it returned a result
* I used that database as the backend for Pepys_Admin, and it all ran fine.

Does this suggest that the way we configure PostGIS from Python may be wrong?

**Comment by BarisSari** [comment]
As Robin pointed before, we changed the schema, so extensions are created under `Pepys` schema. When we did that, I was using Ubuntu and it didn't crash. We also use the Ubuntu environment on Travis CI and it checks whether `spatial_sys_ref` is in Pepys schema each time. Do you think that `spatial_sys_ref` is created in Peys schema but not functions such as `ST_AsEWKB`?
