### ISSUE TITLE
REP Comment Parser only catching first word

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#178]
In the REP format for comments, the content for the comment itself is all the tokens that appear after the track name (or narrative-entry type for `;NARRATIVE2:` entries.

But, our current token-based processing only store the first comment. That's a mistake - it should group them together to store a phrase.

_Hopefully_ the REP comment parser uses the ExtractionHighlighter, and this issue gives us a further opportunity to test-drive composite highlight tokens.

**Comment by robintw** [comment]
Yes, all parsers now use the highlighter, so this should be fairly easy to fix and debug with the highlighted code. I'll deliberately leave this for you to do, so you have a chance to play with the highlighter and the combining of tokens etc.

**Comment by IanMayo** [comment]
> I'll deliberately leave this for you to do

Nice logic.

**Comment by IanMayo** [comment]
@robintw - I want to get a new release made this morning, for which I'm the bottleneck.  Would you mind taking this on after-all ?

**Comment by robintw** [comment]
Done. See https://github.com/debrief/pepys-import/pull/184

(You caught me just before I went out - off for the rest of the day now)
