### ISSUE TITLE
Switch SQLite to use int IDs instead of Blobs

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#18]
It would be easier to track what's happening in our development databases if we could easily read the ID numbers.

We should change the SQLite schema to use ints, instead of blobs.

**Comment by BarisSari** [comment]
I'm taking this issue on me

**Comment by IanMayo** [comment]
I'm pretty sure I did this last night, though I welcome your review :-)

**Comment by BarisSari** [comment]
> I'm pretty sure I did this last night, though I welcome your review :-)

Okay, I'm late :-) It's already done
