### ISSUE TITLE
Add ability to turn off moving of input files

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#205]
I think we discussed this on Slack, but I couldn't see any issue for it. We thought it'd be helpful to be able to turn off the moving of input files for testing purposes (both for us testing the CLI and for the parser writers when testing new parsers, so they don't have to keep moving files back all the time).

This could be an appropriate setting to put into the config file @BarisSari is developing in #202.

**Comment by IanMayo** [comment]
In my opinion it's something that's more suited to being a parameter for the `import.py` class. 

We wouldn't want to change the shared config file and not archive anybody's files.  

Maybe a `--archive true / false` (default true) flag for `import.py` .

**Comment by BarisSari** [comment]
As far as I searched, I think we might have a better flag solution. We might give `--archive` or `--no-archive` flags for `import.py` instead of `--archive true/false`. Because it might mislead in some cases `--archive false` can be understood as True because of casting types.

**Comment by IanMayo** [comment]
Sure, @BarisSari - good thinking.  Happy with "flag" strategy.

Hmm, `--archive` or `no-archive`.  I guess `archive` is the better strategy.  So, by omitting the flag, the files stay in their place, which is the less _destructive_ option.

So, let's go with `archive`.
