### ISSUE TITLE
Fix name or implementation of distance_between_two_points_haversine

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#207]
The function `distance_between_two_points_haversine` in `unit_utils.py` states in its name that it calculates a distance, but actually returns a speed in metres per second.

Either the name should change, or the functionality should change, so it does what it says in the name.

From looking at the git history, I think @tahirs95 wrote this, so probably best for him to investigate.

**Comment by BarisSari** [comment]
Hi Robin. I implemented that function. Actually, it is calculating the distance between two points in kilometers. However, we always use meter/second unit and therefore we assume that it calculated kilometer/hour, we convert it to meter/second. I agree that it is confusing. We might return the kilometer value from that function. Or we can rename it as you suggested.

Note: By the way, I realize that some files look completely changed in the PRs. However, not any lines change all. I think it's because of the line separators.

**Comment by IanMayo** [comment]
```
    c = 2 * asin(sqrt(a))
    radius = 6371  # Radius of earth in kilometers. Use 3956 for miles
    distance = c * radius
    return (
        (distance * unit_registry.kilometers / unit_registry.hour)
        .to(unit_registry.meter / unit_registry.second)
        .magnitude
    )
```

```
        calculated_speed = distance_between_two_points_haversine(
            self.prev_location, self.location
        )
```

Oops :-). We calculate speed by first calculating the distance between the two points, and then calculating the time between the two timestamps.  `distance / time = speed`.

Once we've got the two speeds, we need to put them into the same units (prob the measured units), and then compare their `magnitude`s.

So, the haversine function should just return the distance (ideally as a distance-with-units, in metres).

**Comment by robintw** [comment]
I'd prefer it if @BarisSari dealt with this: I don't really understand what the purpose of this function is, and why it is returning the result in strange units...sorry!

**Comment by IanMayo** [comment]
Sure, ok :-)

**Comment by BarisSari** [comment]
> I'd prefer it if @BarisSari dealt with this: I don't really understand what the purpose of this function is, and why it is returning the result in strange units...sorry!

Sure, @robintw . I'll fix this issue but you can check this link to have a better understanding on the haversine formula: https://www.movable-type.co.uk/scripts/latlong.html

> This uses the ‘haversine’ formula to calculate the great-circle distance between two points – that is, the shortest distance over the earth’s surface – giving an ‘as-the-crow-flies’ distance between the points (ignoring any hills they fly over, of course!).

**Comment by robintw** [comment]
Yeah it wasn't the haversine formula that I was confused about - I just couldn't understand how it was returning a speed when it wasn't doing any calculations about time... Anyway, if you've fixed it that's great :)
