### ISSUE TITLE
Are we exporting depth/elevation incorrectly in REP export?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#210]
When we export REP data in https://github.com/debrief/pepys-import/blob/c45fd82c220d65cbb6a373f8adbff3d8e1b2f775/pepys_import/core/store/data_store.py#L1164 we export the absolute value of the elevation.

According to https://debrief.github.io/tutorial/reference.html#replay_track_format the Depth field in REP files is 'Depth in metres'.

Given that we store elevation, do we actually need to do `-1 * elevation` for the export?

**Comment by IanMayo** [comment]
Yes, you're completely right. We do invert it in the way in from REP, we've missed it in the export, @tahirs95

**Comment by tahirs95** [comment]
Noted.
