### ISSUE TITLE
Typo: SLA should be SOA

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#228]
The acronym is short for `Speed of Advance` - so it's `SOA`.

We should fix this fairly soon, since it represents technical debt.

**Comment by robintw** [comment]
Ok, I'll sort that today.

Is the `mla` acronym correct? I assumed MLA and SLA were related...

**Comment by robintw** [comment]
Also, the SLA was listed as being in degrees - is this correct? If it is _speed_ of advance then I'd expect it to be a speed?

**Comment by IanMayo** [comment]
`MLA` = `Mean Line of Advance`.

Yes, SOA should be a speed.  

Yes, I'm kicking myself for not spotting that :-(

**Comment by robintw** [comment]
And what units should MLA be?

**Comment by IanMayo** [comment]
MLA is in degrees.  I got that right, at least ;-)

**Comment by BarisSari** [comment]
Fixed in #231
