### ISSUE TITLE
What shortcuts do we want in Windows Send To?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#234]
At the moment we have two shortcuts in the Windows Send To menu:

 - `Pepys Import` (imports to an in-memory SQLite database)
 - `Pepys Import (persist)` (imports to a SQLite database in the directory the files were imported from

The second one of these will no longer work, as we no longer have a `--db` option on the import CLI: it is all configured through the config file.

Do we want to replace these two entries with:

 - `Pepys Import` (imports to whatever database is configured in the config file)
 - `Pepys Import (no archive)` (as above, but doesn't archive the input files)

Alternatively, if we still want to be able to import into an in-memory SQLite database by ignoring the config file then we'll need to add an option to do this to the import CLI.

**Comment by IanMayo** [comment]
@robintw - that's a perfect plan.

**Comment by BarisSari** [comment]
> Alternatively, if we still want to be able to import into an in-memory SQLite database by ignoring the config file then we'll need to add an option to do this to the import CLI.

By default, the import CLI parses `default_config.ini`, which has connection info of the in-memory SQLite Database. However, it happens only when `PEPYS_CONFIG_FILE` environment variable doesn't exist in the system. So, there might be a solution in which you don't need to ignore the config file. It can stay the same, but we can ignore/hide the environment variable (I'm not sure whether it's possible to do that, it's just a suggestion).

**Comment by IanMayo** [comment]
> By default, the import CLI parses default_config.ini, which has connection info of the in-memory SQLite Database.

That suits someone doing self-training.  But, for parser development they'll probably want to write to a local SQLite database (so they can check the imported data).

**Comment by robintw** [comment]
Fixed in #259 and #238
