### ISSUE TITLE
Should we update default config file and fallback config options to match?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#245]
While writing the docs for the configuration file, I noticed that the default config file specifies various settings (basically an in-memory SQLite database), but when the config file is loaded, any entries that are missing will be replaced with values that are different to the default config file values - they are actually values for a local Postgres server.

Would it make sense for these to match, so we always default to the values shown in the default config file?

**Comment by IanMayo** [comment]
Good point @robintw .

Yes, I guess we should stop introducing default values for missing fields.

This _may_ break some config files, esp. where they omit the `db_type` field, knowing that `postgres` will be provided.

But, it still feels like the correct thing to do.

**Comment by BarisSari** [comment]
Thanks for pointing this out, @robintw . The reason for this difference is the default config file has been changed recently. Ian and I decided to have in-memory SQLite connection settings, yet, I didn't change the default values of the config file parser. I'm going to delete them. So, we won't have any default values for missing fields. But I have a question for @IanMayo. When you say `db_type` field, do you also mean to delete the default value of DataStore initialisation?
