### ISSUE TITLE
Number of State objects differ between dynamic importers and registering importers manually

### ISSUE THREAD

**Issue by BarisSari** [debrief/pepys-import#254]
Today, I faced this really strange problem accidentally. In `test_load_rep.py`, we register `ReplayImporter() ` manually (`processor.register_importer(ReplayImporter()`) and it parses the files under `tests/sample_data/track_files/rep_data`. It commits 746 State objects to the DB. However, when I switched it to `processor.load_process_dynamically()`, it decreases to 738! For now, I have no idea why it's decreasing but I'll debug it once my current PR work is done.

**Comment by robintw** [comment]
One vague idea I just had (I'm looking after my son at the moment so can't check)... Might it be that when other parsers are running that also operate on REP files, some of those fail on some of the files, causing all measurement objects for that file to be discarded?

If so, you'd expect this problem not to occur for GPX or NMEA, and to occur if you manually register the REP contact or comment parsers as well.

**Comment by BarisSari** [comment]
Thanks for the answer! You're right. `rep_test1_bad.rep` has 8 State objects which are proper for Replay Importer but not for Replay Comment Importer. So, it is not an issue. I'm closing it.
