### ISSUE TITLE
Add --temp or --in-memory or --db option to import CLI

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#256]
From the point-of-view of a parser author, it'd be really helpful to be able to test the whole import process via the import CLI without the possibility of accidentally loading data into a live database.

Therefore, I think we should add back in some sort of option to the import CLI to configure which database to load into. This could be:

 - a `--db db_name` option that would override the config file and load into the specified SQLite database file
 - a `--temp` or `--in-memory` option which would load into a temporary in-memory SQLite database (possibly less useful, as the user couldn't then check the data in the database).

**Comment by IanMayo** [comment]
Yes, good suggestion.  This would override any environment variable, right?

I think that just the --db parameter would be sufficient.  Our guidance can explain that using `":memory:"` as the value will use a temporary in-memory database.

**Comment by robintw** [comment]
Fixed in #259
