### ISSUE TITLE
Shortcut to run pepys-admin on Windows

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#270]
Do we want to add to the `create_shortcuts.ps1` script to make it create a shortcut to the Pepys-Admin application in the Start Menu/Desktop/Somewhere?

**Comment by robintw** [comment]
Do you want this done in time for the new release this week @IanMayo? I'm aware that at the moment a user has no easy way to run pepys-admin.

**Comment by IanMayo** [comment]
Yes please @robintw 

I was concerned that the user wouldn't be able to specify the `--db` parameter, but it should work fine from the environmental variable.

**Comment by robintw** [comment]
Fixed in #277
