### ISSUE TITLE
Folders created with logs/highlighted output are in UTC time - is this correct?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#275]
Just been doing something and noticed that the times that are used to create the folders for storing the output logs/highlighted files for an import (like `2020/04/01/14/15/30`) are using the UTC timezone - therefore they don't match up with what the user would see on their clock when we're in BST (like we are at the moment).

Is this intentional? Just wanted to check, as it may confuse users.

**Comment by IanMayo** [comment]
I've just checked with client(s), they're sure UTC is the correct strategy.  That's just a coincidence, I hadn't discussed it with them before.
