### ISSUE TITLE
Potential bug in Command Line Importer

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#284]
I was just doing a test-import of `tests\sample_data\track_data`.  I forgot to set the default resolver.

So, it jumped into the command-line resolver. I thought "that's ok, I'll give it a go".  But, after I'd added a platform, it wanted the classification (privacy) for it.  

I was then stuck in an infinite loop, where I kept getting asked about that privacy.

[note: I've just tried again, and wasn't stuck in the loop - if @BarisSari  can't reproduce it, let's close this issue.]

**Comment by robintw** [comment]
That's interesting, I did exactly the same test before I submitted the PR for changing to default to the command-line resolver and didn't get that issue.

**Comment by robintw** [comment]
Actually, I've just experienced the same bug myself - I was importing `rep_test1.rep`.
