### ISSUE TITLE
Suspected issue with empty database

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#286]
I don't know if I've imagined this, but.

I'm importing `rep_Test1.rep` using the CLI importer.

It asks me for the classification on the data-file.  None are loaded.  So, I create a classification `public`

Shortly afterwards, it asks me for the classification for the platform.  Now the values offered are the ones from the reference `.csv` _plus_ the `public` one I entered above.

So, I think we're loading the reference data later in the process than we need to.

This only really relates to people _Test-driving_ Pepys, but it could hit a few people in the next few weeks.

**Comment by BarisSari** [comment]
I don't think it offers the ones from the reference `.csv ` @IanMayo . It creates `Public` privacy when Replay Importer starts to parse the file:
https://github.com/debrief/pepys-import/blob/bd487174fab9158ab0e911ebf3a09a0c8dac66cf/importers/replay_importer.py#L45-L51

Yet, these hardcoded values are also reference data. We might create them at the beginning if you'd like to.

**Comment by IanMayo** [comment]
@BarisSari - yes, we should load the reference data when we encounter an empty database.
