### ISSUE TITLE
Folder for Pepys Admin export will default to bin on Windows

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#288]
On Windows, when Pepys Admin is run from the Start Menu and a file is exported, if just a filename is given then it will be placed in the `bin` directory in the pepys-import installation.

We need to decide where files should be placed if they are just given to Pepys Admin as a bare filename with no path. Do we need to make this a configuration option in the config file? Or do we assume something standard like the user's Desktop or My Documents or something? (Obviously that would only work on Windows...)

Thoughts @IanMayo?

**Comment by IanMayo** [comment]
Hmm, well spotted.

`bin` certainly isn't a good location.

If we knew that the current working directory was `bin`, we could follow the `filename` question with `folder`. The default would be `~\`, and _hopefully_ it would support autocomplete.  

If folder/path autocomplete isn't very, very simple then I'm happy to defer it for the future.

**Comment by robintw** [comment]
Fixed in #323
