### ISSUE TITLE
Exported REP files on Windows have double spacing

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#289]
When exporting a file from Pepys Admin on Windows, it ends up looking like this:

```
120427 162938.000	NELSON	AA	22 11 10.63 N	021 41 52.3702 W	0	8.75	0.0

120427 163038.000	NELSON	AA	22 17 10.63 N	021 47 52.3702 W	0	10.69	0.0

120427 163138.000	NELSON	AA	22 29 10.63 N	021 17 52.3702 W	0	14.58	0.0

120427 163238.000	NELSON	AA	22 11 10.63 N	021 35 52.3702 W	0	18.47	0.0

120427 163338.000	NELSON	AA	22 23 10.63 N	021 11 52.3702 W	0	6.80	0.0

```

There are extra blank lines between the lines. I expect this is a problem with line endings on Windows vs other operating systems.

**Comment by BarisSari** [comment]
@robintw , I modified the `export_datafile` method recently. It creates tab-separated files for better visualization. So, I think it's not related to the operating system. It was really difficult to check the exported data when it was space-separated. However, it is easy to switch it back if it causes any failures.

(I changed the following lines)
https://github.com/debrief/pepys-import/blob/ef9732e2c96aa58cf384e7f1a4aeeb4432d0d184/pepys_import/core/store/data_store.py#L1327
https://github.com/debrief/pepys-import/blob/ef9732e2c96aa58cf384e7f1a4aeeb4432d0d184/pepys_import/core/store/data_store.py#L1361
https://github.com/debrief/pepys-import/blob/ef9732e2c96aa58cf384e7f1a4aeeb4432d0d184/pepys_import/core/store/data_store.py#L1383
