### ISSUE TITLE
Summary of files that succeeded/failed at the end of an import?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#290]
At the moment, when we import a file and the import fails due to errors in the file, there isn't actually anything printed out on the console - you have to go and find the archive folder and look for the error log.

Do we want to have a list provided at the end of the import process saying "Files successfully imported: X, Y and Z. Files failed import: A, B, C"?

**Comment by IanMayo** [comment]
Yes please - I remember that frustration.

Maybe also include the name of the importer(s) or test(s) that failed alongside the filename.
