### ISSUE TITLE
.rep is appended to file name in export, even though example has .rep on it

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#292]
When exporting a REP file from Pepys Admin:

```
(pepys-admin) (export by platform) 1
Please provide a name (Press Enter for default value (exported_GPX.rep)):test_export.rep
Objects are going to be exported to 'test_export.rep.rep'.
Objects successfully exported to test_export.rep.rep.
-------------------------------------------------------------
--- Menu ---
(1) Initialise/Clear
(2) Status
(3) Export
(4) Export by Platform and sensor
(0) Exit

(pepys-admin) 0
Thank you for using Pepys Admin
(pepys) ~/Documents/IanMayo/pepys-import(fix-double-line-spacing-windows ✗) cat test_export.rep.rep 
120427 162938.000	NELSON	AA	22 11 10.63 N	021 41 52.3702 W	0	8.75	0.0
```

The prompt says `Please provide a name (Press Enter for default value (exported_GPX.rep)):test_export.rep` which has a default value of `exported_GPX.rep` - so I assumed I needed to add a `.rep` to the filename I gave. However, when I did that, it exported a file called `test_export.rep.rep`.

**Comment by IanMayo** [comment]
@robintw - the _intention_ for this export was that `.rep` would be appended to a tidied version of the original name.  The _tidying_ would be to replace any `.` chars with a `_`.

So, if the input was `boat1.rep`, the output would be `boat1_rep.rep`.

**Comment by robintw** [comment]
Yes, that makes sense for the default value (which is auto-generated from the datafile name - which I assume is what you mean by the 'input' there), but what should we do when the user gives us a name to export to? Presumably they will be giving the actual name they want us to use? And we should just add `.rep` to if it doesn't exist?

**Comment by IanMayo** [comment]
> And we should just add .rep to if it doesn't exist?

Yes, that makes complete sense.

**Comment by robintw** [comment]
Great, that's what my code in #294 does.
