### ISSUE TITLE
CLI - datafiles

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#297]
When we're importing a datafile, we don't need to ask the user if they want to create the new datafile.   We just create it.

**Comment by BarisSari** [comment]
I'm sorry that I'm always asking about privacy but I should ask it for datafile, too. We are using `resolver.resolve_datafile()` inside of `DataStore.get_datafile()` method. get_datafile() doesn't have `privacy` parameter, so should we add it? Or should we use a hardcoded privacy value?

**Comment by IanMayo** [comment]
> always asking about privacy

Don't worry - there isn't a clear answer for it.  Plus, these importers are "examples" - it's quite likely that the users will develop their own working practices for when to hard-code a privacy in the importer, and when to ask the user.

Yes, when we create a datafile, let's ask the privacy for it. It's not optional, after all.  Hold on.  Let's have a case when we specify it in the importer. Let's hard-code `Private` for `NMEA` data, please.
