### ISSUE TITLE
Wrong URL in link to API

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#316]
At the end of `README.rsr` is a link to the structure and API of Pepys:
![image](https://user-images.githubusercontent.com/1108513/78659954-281af580-78c4-11ea-804b-a637b41aebe2.png)

This currently links to the `readthedocs` homepage for Pepys.  I think it should probably link to the `Source documentation` (modules) folder in the docs.

**Comment by robintw** [comment]
Fixed in #320.
