### ISSUE TITLE
Documentation - using Pepys from command line

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#317]
The `usage` page includes guidance on running Pepys from the command-line: https://pepys-import.readthedocs.io/en/latest/usage.html

```
ensuring that the python executable on your PATH is the one for 
which pepys-import has been installed.
```

Doesn't the `set-paths` script ensure the correct Python is on the command-line (with the dependencies installed)?

Aah, but from the look of it, that script can only be run from inside the `bin` folder. 

If a user is going to use any of the `pepys-import` or `pepys-admin` CLI parameters they have to do it from the command line. But, first they have to go into the `bin` folder and run `set-paths`. 

I wonder if it would be more logical for `set-paths` to be located in Pepys-root, and run from there?

Otherwise I don't necessarily know that Pepys users will know how to ensure the correct Python is being used.

**Comment by robintw** [comment]
This has been fixed by adding the `bin` folder to the PATH and updating the docs respectively. Fixed in #324
