### ISSUE TITLE
Usability - indicate when duplicate file skipped

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#319]
My database already has the contents of `sample_data\track_files` loaded.

I've navigated into `sample_data\track_files\gpx` and run `python -m pepys_import.import` (which will load the contents of the current folder).

The command runs, it shows the same database contents before\after, which I _think_ proves that Pepys recognised that the files were already loaded.  

We should show a message when we're skipping a duplicate file. It would be good if the message included the date when the file was originally loaded (datafile.created_date).

**Comment by robintw** [comment]
When I do this, I get a message printed saying `'gpx_1_0.gpx' is already loaded! Skipping the file.` - it's printed between the 'Before' and 'After' tables. Does that not appear for you?

**Comment by IanMayo** [comment]
Aah, in that case it wasn't trying to import the files. I'll have to run through it again.

**Comment by robintw** [comment]
I agree that it'd be good to include the date when the file was originally loaded though - I'll add a separate issue for that.

**Comment by BarisSari** [comment]
> When I do this, I get a message printed saying `'gpx_1_0.gpx' is already loaded! Skipping the file.` - it's printed between the 'Before' and 'After' tables. Does that not appear for you?

It is the default behavior. If it doesn't work like that, it might be that there is a bug. I'll try to reproduce it before adding the date.

**Comment by IanMayo** [comment]
@BarisSari - it's more likely that it was my user error.  I'll try it again today.

**Comment by robintw** [comment]
Is this fixed now @IanMayo? The PR #327 has now been merged to add the date to the message.
