### ISSUE TITLE
Bug in storing zero values for fields in various importers

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#345]
In various importers we have code that looks like this:

```
elevation = convert_distance(elevation_str, unit_registry.metre, None, self.errors, self.error_type)
if elevation:
    state.elevation = elevation
```

The `convert_distance` function returns False if there is an error converting the elevation string to a float. _However_, the `if elevation` statement will only be true if elevation is 'truthy' in Python. And, unfortunately in this case, a value of zero is not considered truthy. Thus, in this case elevation won't be set, and will be left at its default value of None in the database.

There are various potential ways of fixing this:

1. The quick and nasty way is to replace the if statement with `if elevation != False or elevation == 0`, but that's a fairly nasty bit of code.

2. A nicer way is to use a different 'sentinel value'. For example, we return a string of 'ERROR' when there is an error, and then check for that.

3. The nicest, but most verbose way, is to return two values from all these conversion functions: an error _and_ the actual converted value. So the code would be like:

```
elevation_valid, elevation = convert_distance(elevation_str, unit_registry.metre, None, self.errors, self.error_type)
if elevation_valid:
    state.elevation = elevation
```

Shall I go ahead and implement option 3?

**Comment by IanMayo** [comment]
Well spotted.

How about we return an error and the value.  If there is no error, use the value.  If there is an error, then report the error.
