### ISSUE TITLE
View table contents from Admin app

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#352]
At least while the volumes are low, it would be good to be able to view table contents from the Admin app.

It could be a capacity that grows, I'll capture that in a separate issue.

But, to start with, we let the user type a table name, and we return the contents of the first 10 rows, with column headers.

Let's get that done, then learn about it.

I see these problems: 
* some will show foreign keys that don't make sense
* some keys will be really long GUIDs.  Aah, but they're prob nice simple counters in SQLite.

Note: this 'feature' could prove useful for the getting started guidance in Binder.

Discussion on UI thoughts started here:
https://pepys-import.slack.com/archives/CU09ELTNK/p1588777735006700

**Comment by BarisSari** [comment]
I started working on this task and I'd like to share a few screenshots to discuss:
**Postgres**
<img width="2048" alt="Screen Shot 2020-05-07 at 13 43 20" src="https://user-images.githubusercontent.com/41292272/81285797-ba9be980-9068-11ea-9f1a-4ad2645c1ec4.png">
**SQLite**
<img width="1720" alt="Screen Shot 2020-05-07 at 13 46 38" src="https://user-images.githubusercontent.com/41292272/81286085-2ed68d00-9069-11ea-97d8-53cc1b680597.png">

My observations are as follows:
- As you pointed out, GUIDs are really long and the printed table looks like gibberish when terminal is not fullscreen.
- One of the problems is when a table has many columns (more than 6-7 rows), it again looks like gibberish.

We might exclude `created_date` from the printed tables to gain some space. We might also try to print _the most valuable attributes_ but it might be problematic because we don't know which table is going to be viewed and which columns this table has.

> some will show foreign keys that don't make sense

We can define relationships between tables (https://blog.theodo.com/2020/03/sqlalchemy-relationship-performance/) and fetch the attribute values of the foreign keys. This might lead to losing performance and we might have many additional columns.

For running SQL scripts, I suggest using prompt toolkit because it highlights the SQL language:
https://python-prompt-toolkit.readthedocs.io/en/master/pages/tutorials/repl.html#syntax-highlighting

I'll keep you updated while I'm testing more things. During this time, I'm waiting for your feedback&suggestions.

**Comment by IanMayo** [comment]
Well, I guess we weren't going to start learning, until we had something to look at.

I wonder if we can do some "intelligent" processing on the GUID fields.

If the field starts with the table name, and ends in "_id", it's the primary key, and _maybe_ we just show the last 6 digits.  If it's something else but ends in "_id" we can presume it's the foreign key to another table - and use the prefix to determine the table name.  We can then create "inner join" to pull in the value from the other table.  Aah, we don't necessarily know when field represents the "title" field in the other table.  Hmm, "name" appears to work in "most" cases.

The issue of the number of columns is more challenging.  I wonder if we could add some _annotation_ to the SQLAlchemy definition for some fields, to indicate which ones are shown in the Admin Page list view.

**Comment by robintw** [comment]
Ian's ideas sound good - a few other comments/ideas from me:

 - We ought to test this on Windows too. In previous versions of Windows, you couldn't maximise the Command Prompt window properly. I'm pretty sure you can do that now on Windows 10 (though I use a separate terminal program anyway) - but I have a feeling it's still not as good at displaying things across the whole window as it should be. Basically, it might look worse on Windows.
 - Another option for displaying the large tables is to write it out to some other sort of file and automatically open the file for the user. For example, if we know the clients have Excel on their machines, we could write out to a CSV file and automatically load it in Excel. Similarly, we could write out to a HTML file with a nice javascript table viewing interface (there are lots of them around) and load that in the browser (possibly this option is more consistent with the rest of Pepys, as we already do that with the highlighted output files). We could even merge this with Ian's idea of showing only certain fields, to say "Here's a brief view of the table in the command prompt, press 2 to view this with all fields in your browser" - or something like that.

**Comment by IanMayo** [comment]
@BarisSari - note, we still have some freedom in how we implement this.  If it's the right thing, I don't mind us creating "Views" in the database, if necessary.

**Comment by BarisSari** [comment]
> I wonder if we can do some "intelligent" processing on the GUID fields.

> If the field starts with the table name, and ends in "_id", it's the primary key, and maybe we just show the last 6 digits. If it's something else but ends in "_id" we can presume it's the foreign key to another table - and use the prefix to determine the table name. We can then create "inner join" to pull in the value from the other table. Aah, we don't necessarily know when field represents the "title" field in the other table. Hmm, "name" appears to work in "most" cases.

Thanks for the suggestion, @IanMayo. I'll try to implement it. I believe that I might get _name_ field of another table (if it exists) using the _relationship_ of SQLAlchemy. I'll let you know when I tried it out.

> The issue of the number of columns is more challenging. I wonder if we could add some annotation to the SQLAlchemy definition for some fields, to indicate which ones are shown in the Admin Page list view.

I believe that _Deferred Column Loading_ might help us to decrease the number of columns. (https://docs.sqlalchemy.org/en/13/orm/loading_columns.html#deferred-column-loading). It will not load the deferred columns unless we specifically try to get that columns' values.

> We ought to test this on Windows too. In previous versions of Windows, you couldn't maximise the Command Prompt window properly. I'm pretty sure you can do that now on Windows 10 (though I use a separate terminal program anyway) - but I have a feeling it's still not as good at displaying things across the whole window as it should be. Basically, it might look worse on Windows.
> Another option for displaying the large tables is to write it out to some other sort of file and automatically open the file for the user. For example, if we know the clients have Excel on their machines, we could write out to a CSV file and automatically load it in Excel. Similarly, we could write out to a HTML file with a nice javascript table viewing interface (there are lots of them around) and load that in the browser (possibly this option is more consistent with the rest of Pepys, as we already do that with the highlighted output files). We could even merge this with Ian's idea of showing only certain fields, to say "Here's a brief view of the table in the command prompt, press 2 to view this with all fields in your browser" - or something like that.

It would be much better if we put the result in a file. Thanks for the suggestion, @robintw . I'll apply Ian's suggestions first, and then I think we can decide if we would like to create a file or print it in the terminal.

**Comment by IanMayo** [comment]
That's all good.

I think we should hold back on sending to file, that sounds move like an export process, to be honest.
