### ISSUE TITLE
Stop searching for Sensors/Platforms/etc by name - as names may be duplicated

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#362]
This is a fairly big change, but one that should be done sooner or later. A lot of places in the code search for things like Sensors or Platforms by name - but that isn't necessarily valid as we may have duplicate names for Sensors or Platforms. Generally, when we have been passing something like `platform_name` around, we should be passing `platform_id` instead.

I'm part-way through scoping this issue, and will post here with more details when I've worked out what needs to be done.

**Comment by IanMayo** [comment]
> This is a fairly big change, but one that should be done sooner or later.

I think you mean `sooner rather than later`.

Yes, I support this change.

**Comment by robintw** [comment]
Yes I do - it's next on my todo list.
