### ISSUE TITLE
Replace manual sensor_name/platform_name attributes with SQLAlchemy relationships

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#372]
In the definitions of the `State`, `Contact` and `Comment` classes, we have defined instance variables called `sensor_name` and `platform_name`. When we add one of these classes (in, for example `Datafile.create_state`) we manually set these variables based on the sensor object that we have. As far as I can see, they're only used in the extended validator to give more useful errors to the user.

The same functionality could be implemented using SQLAlchemy relationships, and then these would automatically stay up-to-date, rather than having to be manually set on creation. We're starting to use SQLAlchemy relationships in #353 - so I think it'd be good to use them here too.

What do you think @BarisSari?

**Comment by robintw** [comment]
By the way, I'd like to implement this if we go down this route (to get me more familiar with some of the SQLAlchemy stuff we use) - but just wanted feedback from you both first.

**Comment by BarisSari** [comment]
> The same functionality could be implemented using SQLAlchemy relationships, and then these would automatically stay up-to-date, rather than having to be manually set on creation. We're starting to use SQLAlchemy relationships in #353 - so I think it'd be good to use them here too.

Yes, @robintw . It's a really good suggestion. However, I already implemented it in my view data PR. I just used different names for now but it will work fine when I rename the `relationship` and `association proxy` variables. You can look at an example here:
https://github.com/debrief/pepys-import/blob/9bc54df04762a515fa93b3d9d8867055ab11b45d/pepys_import/core/store/sqlite_db.py#L404-L411

If that's okay, I'd like to rename these new fields and solve this issue after the merge of view data PR. I don't want you to bother with a small refactoring(renaming fields and checking the logs).

**Comment by robintw** [comment]
Ah well done - you got there before me! This all sounds fine - we'll leave it until your view data PR is merged.

Looking at the link you gave in the previous comment, I think there is a `sensor` relationship missing in the `Contact` class - although it may just be an old commit where that's fixed already.

**Comment by BarisSari** [comment]
> Ah well done - you got there before me! This all sounds fine - we'll leave it until your view data PR is merged.
> 
> Looking at the link you gave in the previous comment, I think there is a `sensor` relationship missing in the `Contact` class - although it may just be an old commit where that's fixed already.

Yes, I realised it yesterday but I couldn't commit&push because of a Git Version Control issue. I fixed it now: https://github.com/debrief/pepys-import/pull/353/commits/9fd2b5752a30df6f02f380b2a3ec1508c6a37f22

**Comment by robintw** [comment]
Is this all done now @BarisSari?

**Comment by BarisSari** [comment]
No, not yet. I'll open a hotfix PR for that today, @robintw .
