### ISSUE TITLE
Standalone Pepys on laptop

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#373]
An analyst is deploying "to sea" with a laptop, and wishes to be able to use Pepys as part of the analysis process.

I propose we use this as an opportunity to trial the use of SQLite as the backend for a "deployed" Pepys database.

Beyond that experiment, this is also an opportunity to trial deploying a "snapshot" of the `master` Pepys database - to reduce the need to generate reference data (such as privacies, sensor types, etc) and metadata (platform names, sensor names, etc).

On completion of the deployment it offers the opportunity to import new reference/metadata/measurements into the `master` Pepys database.  Part of this challenge is how we tidily/logically handle the archived original datafiles (and import reports, etc).

For this to happen we need:
* [ ] Ability to export Metadata/Reference from PostGIS Pepys to SQLite instance (via Pepys-Admin) - see #374 
* [ ] Laptop installation instructions, including:
    * [ ] supporting software (SQLite browser, Debrief, Python IDE)
    * [ ] recommended file location
    * [ ] recommended archive location
    * [ ] recommended SQLite database location
    * [ ] creating/assigning config file
    * [ ] installing shortcuts/send-to, etc    
* [ ] Ability to import/merge SQLite database back into PostGIS, plus original datafile archive. #375

**Comment by robintw** [comment]
What do you suggest we do for the laptop installation instructions? The main installation instructions at https://pepys-import.readthedocs.io/en/latest/installation.html should work on a laptop - and things like where to put the files and the archives and so on will depend a lot on how the laptop is set up (eg. which folders the user has write access to, where they want to put stuff etc).

**Comment by robintw** [comment]
As the analyst now seems to have the laptop set up correctly, I'm closing this.
