### ISSUE TITLE
Inconsistent naming in reference tables

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#380]
I've just been writing tests for the uniqueness constraints that I added a few days ago (I forgot to submit tests with the PR), and have realised that we have inconsistent naming for fields in the reference tables.

See the [schema diagram](https://docs.google.com/drawings/d/1kEEYdoU5H7rcvxCaf9Aeyh0ujvEizwZWJE4uNGGNK5o/edit) for context.

All the reference tables have a `name` field for their name, except for:

 - `ClassificationTypes` which has a `class_type` field instead of name
 - `ContactTypes` which has a `contact_type` field instead of name
 - `ConfidenceLevel` which has a `level` field instead of name

Would it be better to change these to be called name, for consistency, and before the clients have a large database that needs to be changed?

(This would also make the uniqueness tests I'm writing easier, but the main reason to do this change is consistency)

What do you think @IanMayo?

**Comment by IanMayo** [comment]
Sure, yes - that's a reasonable improvement.
