### ISSUE TITLE
Better way to stamp latest migration when creating schema in DataStore

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#398]
At the moment there are two ways of creating the database structure: either using `alembic upgrade head` (which would upgrade a blank database to the latest revision), or using the SQLAlchemy commands in the DataStore class to initialise based on the SQLAlchemy table definitions.

In the latter case we also manually 'stamp' the latest alembic version into the database, so that Alembic knows what version the database is at, and can then apply new revisions later.

The problem is that we keep forgetting to update this bit of code when we create a new alembic migration - and that means Alembic thinks the database is out of date when it isn't.

There are various potential solutions:

1. Just get better at remembering to do this!

2. Change to using alembic migrations to create the database structure in DataStore, then the revision will be stamped automatically. We decided not to do this before as it would lead to an automatic alembic upgrade, which may potentially lose data. However, we could do an automatic upgrade if - and only if - there is no schema in the database already (ie. it is blank).

3. Create some sort of automated tool to update our source code on commit, to ensure that the latest revision ID from the alembic migrations folder is included in the source code in the right place.

I think number 2 is possibly best, but welcome discussion from @BarisSari and @IanMayo.

**Comment by IanMayo** [comment]
Yes, number 2 seems quite tidy/logical.

But, I'll defer judgement to @BarisSari .

**Comment by BarisSari** [comment]
Number 2 seems okay to me, @robintw . 

My only concern is that I had a strange error when I use alembic command in `DataStore.initialise()`. It was something like this: "Max connection error: 64" and it was locking the Python process. I hope we won't get it this time!

**Comment by robintw** [comment]
I've just realised that I've forgotten to update the stamped-in revision *again* - so I get errors when running a migration, because it thinks the database is further behind than it actually is.

@BarisSari Are you ok to prioritise fixing this, assuming that @IanMayo is ok with that?

**Comment by BarisSari** [comment]
> I've just realised that I've forgotten to update the stamped-in revision _again_ - so I get errors when running a migration, because it thinks the database is further behind than it actually is.
> 
> @BarisSari Are you ok to prioritise fixing this, assuming that @IanMayo is ok with that?

Sure, @robintw . I'll start working on it now.
