### ISSUE TITLE
Bug in Imported Sensor Name

### ISSUE THREAD

**Issue by BarisSari** [debrief/pepys-import#400]
When I import sample data with the following command: `python -m pepys_import.cli --path tests/sample_data/track_files --resolver default`, It creates a sensor named: `"` (15th row). The row above it looks strange, too.

<img width="1098" alt="Screen Shot 2020-05-20 at 13 58 06" src="https://user-images.githubusercontent.com/41292272/82439337-23d91f00-9aa3-11ea-90ae-e1cbf7a58c58.png">

**Comment by BarisSari** [comment]
While I'm testing default values in random imports, I figured out where `"Frigate` and `"` Sensors come from. **sen_frig_sensor.dsf** file has some sensor names as follows: 
`"Frigate Optic5"`, `" Frigate Optic5"`. 
Since we are splitting lines by separator and it's a space in default, it creates a token as `"Frigate` and `"` respectively. In the file, there are some empty rows, too. Therefore, our validation tests fail because it says that there are not enough tokens in the empty rows. But the created Platform and Sensor objects stay in the database even though measurements couldn't be imported. 

I have the following questions to you, @IanMayo:
- Should we accept the words in quotation marks as one?
- Should we keep the Sensor and Platform objects of bad files (I mean the files that couldn't pass validations)? 
- Should we skip the empty rows for DSF files validation?

**Comment by IanMayo** [comment]
Oh, well spotted :-)

I've just checked. Yes, we do need to support quoted sensor names. Here is the Java implementation:
![image](https://user-images.githubusercontent.com/1108513/82899887-98a0d300-9f53-11ea-8672-1869113bd9f7.png)


Aaah, here is where it's detailed in the reference (1):
![image](https://user-images.githubusercontent.com/1108513/82899999-bf5f0980-9f53-11ea-91c9-a9ebea4dc547.png)

(1). https://debrief.github.io/tutorial/reference.html#replay_annotation_format
