### ISSUE TITLE
Give more information on what you're selecting in the Pepys Admin GUI

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#410]
In the Pepys Admin GUI we have quite a few selection steps using things like iterfzf. Most of the time we don't explain what the user is selecting, why they're selecting it, and what it will mean when they select it. Sometimes this is obvious, sometimes it isn't.

Assuming there is a way of putting a bit of explanatory text above or below the iterfzf interface, we should alter all of these usages to put some explanatory text explaining what they're choosing and why (eg: "Choose platform to export").

## Added by Ian
Please also include this fix, related to `Export Snapshot` with this issue.
```
One UX-related issue I've just realised @BarisSari - there is no explanation anywhere that
you have to use TAB to select multiple entries in the privacies list. Is there a way of
putting a bit of explanatory text above or below the list to explain that? Actually, that 
explanatory text should explain that you're choosing which privacies of data to export 
(phrased in such a way that it comes across that you will export all data with those 
privacies, rather than just those specific Privacy table entries themselves). I've actually 
created an issue about this more broadly - I think there are various places in Pepys 
Admin where we ask the user to select things without giving them much information on 
what they're selecting and why - see #410.
```

**Comment by BarisSari** [comment]
You're right, @robintw . I'll be working on it after my current PR (offering default values in CLI) is done. I'll include a fix for `Export Snapshot` as well.
