### ISSUE TITLE
Minor issue - better warning for missing config file

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#412]
I just tried to run Pepys import (via Send to...), but my config file is missing.

This error was reported:
![image](https://user-images.githubusercontent.com/1108513/83127501-24d90480-a0d2-11ea-9030-d8a87421c777.png)

Could we catch this exception and provide a more useful warning?   I guess something like:
```
Pepys config file not found at location:  C:\git\pepys-import\pepys-import.git\default_config.ini
```

**Comment by BarisSari** [comment]
We're already catching this exception. But when we raise an exception, it prints _traceback_ and it looks ugly 🙂 I'll remove exceptions in config file and will add print&exit statements. So, it will only show messages which we would like to print.
