### ISSUE TITLE
Minor issue - delay before progress bar opens with very large file

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#413]
I'm importing the `NMEA_TRIAL.log`, there is a noticeable delay (>10 seconds) after answering the questions, before the progress bar appears.  This gives the mistaken impression that the import has hung.

Screen recording [[here]](https://youtu.be/fD7EYb4Rls8)

_Maybe_ this is while the file is being loaded, or the number of lines in the file are being counted.

Are we able to either show a progress monitor for this operation, or to add the operation to the functionality that is covered by the existing progress bar?

**Comment by robintw** [comment]
I think this is when the HighlightedFile class is reading the file and generating the lines etc. I'll look into it later.
