### ISSUE TITLE
Minor issue - view docs from Pepys Admin

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#414]
It would be useful if users could view the recent change history from the Admin app.

We have the history in the `History.rst` file.

Hmm, I've got a better option.  It would be better if users could open the html documentation from the Admin app.  I guess Python just needs to instruct the operating system to open the `docs\index.html`

(note - for some users it isn't an option to use a link to `readthedocs`, since they don't have an Internet connection)

Hmm, maybe there's another issue.  It _looks like_ the compiled html documents aren't in our distribution. We will need to sort that first, then add `9. Help` to the `Pepys Admin` menu.

The inclusion of compiled help should probably form part of the `create_deployment.bat` processing.

**Comment by robintw** [comment]
Just a note on this for when I come to fix it: we'll need to use the [sphinx-build](https://www.sphinx-doc.org/en/master/man/sphinx-build.html) command directly here, as we won't be able to rely on having make installed on the build machine.
