### ISSUE TITLE
Change location for seed .csv files

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#419]
PepysAdmin currenty loads the reference/metadata from:
`X:\tools\pepys\current\pepys_import\database\default_data\*.csv`

My clients are going to invest some effort in populating these with as much data as they can - since this will eventually make it easier for the analysts.

But, if I deliver a new release, it will overwrite the CSV files.  Well, not actually. Their working practice is to rename the `current` folder with today's date - and then unpack the new release into `current`.  But, it will appear as if the `.CSV` files have reverted to the pepys-default values.

So, I'd like the clients to be able to store the `.csv` files in the parent folder for Pepys, something like:
`X:\tools\pepys\reference_dat\*.csv`

But, Pepys-Admin will have to be told to use this location.

There are range of ways that we could provide this path:
* Another environment variable
* Add it to the config file
* A parameter to Pepys-Admin (though the users are currently just running it from the `Start` menu
* Navigate to the path from within Pepys-Admin

This task of *loading seed data* won't be performed very often, which reduces the value in the _environment variable_ or _config-file_.  Well, a bit, anyway.

**Comment by BarisSari** [comment]
Hello, @IanMayo . I believe that we already have a parameter for that. If you pass `--path` parameter (i.e. `python -m pepys_admin.cli --path tests/sample_data/csv_files`), it will look for CSV files in the given folder for importing reference data and metadata.

**Comment by IanMayo** [comment]
Thanks @Baris - the users are exclusively starting Pepys-Admin from the shortcut in the Windows Start Menu.

But, this "database seeding" won't happen very often - it _could_ be justifiable to get them to use the command line for just his operation.

**Comment by IanMayo** [comment]
Closing this issue.  The `--path` parameter for `pepys_admin` is satisfactory for this minor capability.

We'll just document it better within #423
