### ISSUE TITLE
Update versions of various dependencies

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#431]
In `requirements.txt` and `requirements_dev.txt` various requirements are pinned to specific versions - some of which are quite old.

It is probably a good idea to update these at some point - obviously checking that all the tests pass.

Specific dependencies which are very old are SQLAlchemy (as pointed out by a bot in #426), pip (the deployment procedure installs the latest version to install itself, then has to downgrade itself afterwards), pint and so on.

**Comment by IanMayo** [comment]
Yes, a very worthwhile task.  Let me squeeze it into the queue of tasks.

**Comment by robintw** [comment]
Fixed in #521.
