### ISSUE TITLE
Testing to verify robust handling of missing keys in `.csv` import

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#434]
The clients are due to be playing with importing reference and metadata from csv file.

We'll probably learn lessons (get feedback) as they get up & running.

One issue I'd like to pre-empt is that a CSV file includes the `name` of a foreign key that isn't present.

When this happens the import process should gracefully handle the failure, and highlight the missing field.  It could also suggest to the user that they use `View data` to view the entries in the relevant table.

**Comment by robintw** [comment]
Oops, sorry - I only just noticed this had been assigned to @BarisSari, and I've done it! Sorry about that - wasn't intentional at all.

**Comment by BarisSari** [comment]
That's completely fine, @robintw 🙂
