### ISSUE TITLE
Add ordering for Privacy

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#438]
When merging databases, we need to use the 'highest' privacy of the two entries when merging entries - and this requires knowing how privacies relate to each other.

We decided this was going to be a `Level` column added to the Privacy table. We'd then need to modify the code that displays privacies in the command-line resolver to display them in order, the code that adds new privacies to display the privacies first to see their levels, and then allow a level to be entered too, plus the code that imports Privacies from a CSV file to import levels too.

**Comment by IanMayo** [comment]
@BarisSari - here is a set of privacy levels that are more consistent.

* Public:  10
* Public Sensitive: 20
* Private: 30
* Private UK/IE : 40
* Private UK/IE/FR: 45
* Very Private: 50
* Very Private UK/IE : 40
* Very Private UK/IE/FR: 45
