### ISSUE TITLE
Improve display of Alembic version

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#447]
![image](https://user-images.githubusercontent.com/1108513/83873009-ed4e0600-a72a-11ea-9ec4-4fe8c6378f20.png)

I think the Create Date field above gives me what I’m looking for.  The database connected to in the above instance was last updated on 3rd June.

But, when I tried the above using an old database (the remote PostGres one at anywheredata.com), `2. View status` failed while collating the table data, since in trying to create the summary tables, it referred to a missing database field.   This failure stopped the `alembic` status from being displayed.

Solutions?
* Separate `View status` into `View summary of contents` and `View summary of database version`
* Catch the database listing error, print the error, then continue to show the alembic status 

Any other thoughts/strategies?

**Comment by BarisSari** [comment]
I think we might keep them together. We should catch the error anyway. So, in my opinion, it would be nice to see that Pepys Admin couldn't show the table data because database version is old.

**Comment by IanMayo** [comment]
Ok, let's catch the error, print it, then go on to give the Alembic version detail.
