### ISSUE TITLE
Pepys failing on laptop

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#460]
Pepys has been installed onto a MS-Windows 10 laptop.

After some minor troubles related to PEPYS_CONFIG_FILE env variable, the analyst was able to open PepysAdmin from the command-line, with visual confirmation it was connected to the SQLite snapshot captured yesterday, and was running Pepys 0.0.16.

## (2. Status) error
When she ran (2. Status) it reported that:
```
SQL Exception details
SQL Error when communicating with database
Please check your database structure is up to date with the version of Pepys you have installed.
```
Pepys-Admin then exited.

## (5. Migrate) error
She re-entered Pepys-Admin.  This time she pressed (5. Migrate).  It showed this message:
```
Alembic migration command running. See output below
Exception details:
[SQLIte3.operational error]
Unable to open database file
Background on this error at: http://sqlalchemy.me/e3a8
Alembic error when migrating the database!
```
Pepys-Admin then exited

It looked like there was an issue with the database
## Empty database error
So, I moved away from the snapshot database - and want to try a blank one.  So, I asked her to rename the snapshot-database.  Now, when Pepys-Admin opens, it should create a new,empty database.

We went back into `python -m pepys_admin.cli`.  Pepys-Admin opened. But, when we did (2. Status) we still got the error to check your database structure.  I was expecting to see `Database tables not found`.

**Comment by BarisSari** [comment]
It seems like both `Status` and `Migrate` errors happened when Alembic commands ran. According to the error, which says "`unable to open database file`", SQLite database couldn't be opened. I think there might be issues about the path of the database or the permission of the file. I'll search for possible problems and write my findings.

What surprises me is that we added a try/except clause for migrate option and it basically catches all exceptions. So, Pepys Admin shouldn't have exited.

I'll test the empty database error. As you said, it should have printed "`Database tables not found`"

**Comment by BarisSari** [comment]
Hello, @IanMayo . I tested the third error as well. Here are the steps I've followed:

- Open Pepys-Admin with the default config file.
- Run `Status`. It prints `Database tables are not found!`.
- Run `Migrate`. It runs successfully.
- Run `Status` again. It prints table summary and database version.
- Close Pepys-Admin
- Rename the created database `pepys_test.sqlite` to `test.sqlite`.
- Open Pepys-Admin
- Run `Status`. It prints `Database tables are not found!`.

It seems like there is a problem with the analyst's config file. Is it possible to learn the `db_name` field?

**Comment by IanMayo** [comment]
@BarisSari - will send `db_name` via Slack

**Comment by robintw** [comment]
Have we resolved this @IanMayo? I think we found it was because her environment variables kept being reset - is that correct?

**Comment by IanMayo** [comment]
Yes, @robintw - I'm happy that the cause was the PEPYS_CONFIG_FILE being changed at unpredicted moments.
