### ISSUE TITLE
Platform-Types and Sensor-Types not offered in CLI

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#469]
This morning I worked with the analyst to load some sample data.

We worked with the file called `sen_tracks.rep`.

The CLI ran as expected, but she was not offered the existing items for `sensor-type` or `platform-type`.  We opened pepys-Admin and verified that both tables contained values - which they did.  So, she used `Search for platform-type`, which worked fine, and `Search for sensor-type`, which also worked ok.

I see that these tables don't have "priority" column.  I do think they both contain more than 7 entries. Maybe that's the issue.  Maybe we only provide the choices when there are 7 or less.

It may be better to offer the first 7 in this instances.  In the longer term we should probably introduce a "priority" table, to let the analysts select the 7 most likely values in these types tables.

**Comment by BarisSari** [comment]
> Maybe we only provide the choices when there are 7 or less.

Yes, @IanMayo . That's the implementation for now.

> It may be better to offer the first 7 in this instances.

Okay, I'll make changes and open a PR.
