### ISSUE TITLE
Add testing of imports using command-line resolver

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#482]
All our testing of the importers currently use the default resolver, because that's far easier for tests. However, this means that we're not testing the main way that users will import files - which is through the command-line resolver. The command-line resolver has good tests itself, but it isn't tested in an 'end-to-end' way.

I think it'd be good to have some tests that do an import of a file using the command-line importer. Ideally we'd do this once for each importer type.

**Comment by IanMayo** [comment]
Yes good idea.

It will be fragile to importer modifications (including wording).

But, if the wording comes from a constant (or Python f"" string) - then we should also be able use that constant in the unit tests.
