### ISSUE TITLE
Add Pepys Admin option to delete a datafile

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#488]
This will need a UI to enable search by datafile reference, and to select from a list (bear in mind we may have multiple datafiles with the same reference: so we should display size and date imported too).

One question is whether we want to delete all metadata imported as part of importing that datafile? If so, we look for all log entries related to the change_id for importing that datafile, and delete all of those. Otherwise we just search for all measurement entries with that source_id, and delete those - or update the schema to use cascading deletes.

Once we've added this functionality, we should update the 'verifying the installation' section of the docs, as we'd now be able to do an import and then delete the import we just did

**Comment by IanMayo** [comment]
Done.
