### ISSUE TITLE
File importers should all have datafile-type parameter

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#494]
In our reference data we have `datafile-type`.  The strategy for how to organise data into types wasn't fully thought through.

We've just agreed that it should come from the name of the importer. So, it will be terms like `Replay`, `GPX`, `NMEA`.  

We have 3 separate Replay file importers, they will all declare the content as `Replay`.

I suggest this new parameter/attribute becomes part of our file-handling API.

Note: we won't need clients to seed these values in their database, since we'll create the entry when necessary.

**Comment by BarisSari** [comment]
Hello @IanMayo . I have a question. Let's say we have a datafile that can be imported by 2 importers (Importer A, Importer B). What should we do if these two importers have different datafile-types? Or is it an impossible case? We are using file extension right now and there is only one value no matter which importer(s) import it.

**Comment by IanMayo** [comment]
Good point @BarisSari .

I guess that if we encounter that situation then we'll have to come up with a name for the composite file type, and include logic in the child data-file type importers that can recognise it as the composite file type, and declare the datafile type accordingly.

But, I that's only if we encounter that situation.

**Comment by BarisSari** [comment]
Do you have any suggestions, @robintw ?

**Comment by robintw** [comment]
Sorry, I somehow completely missed this notification.

I'm not sure what the best way to solve this would be. I think we're probably ok to implement it assuming that won't be a problem at the moment, and 'cross that bridge when we come to it'. Importers are completely standalone at the moment (ie. they don't need to know anything about what any other importer does), and it'd be good to keep it that way - and I think making importers know if the datafile type needs to be a composite type would be breaking that a bit.

So, I think we go ahead assuming this won't be a problem for now, and make a note in the code that there will be problems if that occurs, and deal with it if it comes up.

**Comment by BarisSari** [comment]
Thanks @robintw . Okay, I'll add notes to #503 and finalize the PR today.
