### ISSUE TITLE
Increase character limit for Comment content field?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#496]
In the database schema, the `content` field for the `Comment` table is defined as having a maximum length of 150.

On Slack, @IanMayo suggested that the new Nisida data might have 'narrative' entries (stored as comments) that are a paragraph long. To be able to store this length of data we'd need to increase the maximum length of the field.

What length do you think we should extend it to?

(It seems like the number of characters we define doesn't matter for SQLite - see [here](https://www.sqlite.org/faq.html#:~:text=SQLite%20does%20not%20enforce%20the,all%20500%2Dmillion%20characters%20intact.) but will do for Postgres)

**Comment by IanMayo** [comment]
Great thinking @robintw 

The above issue is 496 chars long.  Based on that, I'm sure we've got to allow 2000 chars.

But, if we can increase the length without increasing the database size (through the use of VARCHAR) it would be great if it could be unlimited.

**Comment by robintw** [comment]
It looks like we should switch to the TEXT field for Postgres. As mentioned above, SQLite doesn't enforce character limits anyway - so it should be ok to switch to the SQLAlchemy `Text` type (https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.Text)

**Comment by IanMayo** [comment]
Just done some Googling - yes, it looks like the perfect type.

**Comment by robintw** [comment]
Fixed by #493
