### ISSUE TITLE
Add check constraints to ensure field values are not empty strings

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#497]
We've already added SQL CHECK constraints to ensure that string fields that we're using as part of the uniqueness criteria for tables (eg. `name` or `identifier`) aren't set to the empty string (see #473). Should we also do this for many (or all) other string fields that are set to `nullable=False`?

For example, empty strings for the `name` fields of the reference tables make no sense, and the same applies for fields in `Synonym` and others.

**Comment by IanMayo** [comment]
Yes, good suggestion @robintw .
