### ISSUE TITLE
Generic database API

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#5]
We currently have a database-specific APIs.  This means our business logic would have to target either SQLite or Postgres:

![image](https://user-images.githubusercontent.com/1108513/68137547-143b2400-ff1f-11e9-9f1a-49811561808e.png)

I'm unsure of the best strategy, but I'd like us to either have both implementations _extend_ a parent interface, or to hide the two implementations behind a single API.

**Comment by BarisSari** [comment]
I think we already have a generic database API "**DataStore**", where we import PostgreSQL or SQLite models according to the given _db_type_. 
![Screenshot from 2019-11-07 13-43-54](https://user-images.githubusercontent.com/41292272/68382402-b009a180-0164-11ea-9fce-9a5e042926d1.png)

If you mean something else, please explain it to me and we can discuss it. If not, I think I can change my naming style and solve the issue :-) (We can always name DataStore objects like "**_self.data_store_**" no matter it uses PostgreSQL or SQLite)

**Comment by IanMayo** [comment]
Sure, let me explain a little more. Here's a snippet from a test, but it's similar to business logic for configuring/loading data:

![image](https://user-images.githubusercontent.com/1108513/68383598-de2fb700-014d-11ea-9a9a-197c1309c210.png)

After creating the database, in the snippet we:
* initialise the database (in `setUp`)
* populate the reference data
* retrieve some nationalities

The three steps all use `sqlite` specific calls.   So, if we wanted to run this logic using PostGres, we'd have to duplicate the code, and swap `sqlite` for `postgres`.

Hold on, I realise I've got it wrong. Instead of `sqlite` we could have `data_store`.  We're not referring to a particular version of the library, it's just a placeholder.

I _think_ there never was a problem :-) 

Let me test my understanding by renaming the field in `test_data_store_populate`

**Comment by IanMayo** [comment]
Aah, it's ok - I was worried about nothing:

![image](https://user-images.githubusercontent.com/1108513/68384037-a412e500-014e-11ea-8089-bdfa768dc078.png)

Closing issue :-)
