### ISSUE TITLE
Create indexes for various database columns

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#500]
As far as I can see, we don't have any indexes defined for our database - except for the spatial fields where R-tree indexes are automatically created.

This is fine for the small amounts of data that we're testing with at the moment, but the database could get quite large once the client starts using it 'in the real world'.

We should think about which fields we are often searching by, and create indexes for those fields. Off the top of my head, this could be useful for the name column on the larger reference tables (eg. Nationality), plus the key fields for tables like Platform and Sensor, as we search those often. Depending how often the user will be selecting all State values with a specific `source_id` (eg. I imagine that the Debrief interface will be doing this?) then it'd be worth indexing on that too, and similarly for the other measurement tables.

**Comment by IanMayo** [comment]
Yes, I fully expect us to have to introduce more ~indices~ indexes in the future.

I may be mistaken, but I believe each index adds a slight _WRITE_ performance cost. So, so far I've been deferring the task, until we encounter a bottleneck.  

If there is an instance where we do know of a bottleneck, then it would be an opportunity to learn about indexes, and learn about the performance improvement.  We do have a large set of sample data: https://github.com/debrief/pepys-import/issues/45

We could load that and run some test queries.  If adding an index improves performance then we know it's worth adding.

Debrief runs queries like this:
* All states between start and end dates
* All states with a location within rectangular bounds
* All contacts between start and end dates

**Comment by robintw** [comment]
I've done some experimenting with selecting all states between a start and end timestamp on both SQLite and Postgres, using around 243,000 State entries imported from the bulk data dump. Adding an index does decrease the time taken for the query to search, but all the times are measured in milliseconds anyway, so it doesn't really make much difference to the user. The main thing taking the time from the user's perspective is transferring the actual data (eg. the difference between `SELECT COUNT(*) FROM States WHERE...` and `SELECT * FROM States WHERE...` is that it's actually having to transfer a lot of data for the latter).

Given those results, I'll close this for the moment, and if the clients have trouble with speed later on we can fairly easily add an index at that point.
