### ISSUE TITLE
What is the current status of the privacy_id field on measurement tables?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#501]
Currently the `privacy_id` field on tables like `States` and `Comments` is nullable - ie. it can be left blank.

Should we make this non-nullable, so we have to provide a privacy value for each measurement @IanMayo?

**Comment by robintw** [comment]
Ahh, actually - an update to this: it seems that the privacy_id field in the measurement tables isn't used. It isn't set anywhere in the code as far as I can see, and testing some of the standard importers (REP, NMEA) shows that they are all set to NULL.

So, it looks like we aren't using this field. The question then becomes, should we be using this field? Or should we remove it? Or leave it for use later?

**Comment by IanMayo** [comment]
It's an issue that we can expect to arise in the future.

In many file formats, the whole file is at the same privacy level.

But, some formats allow for individual lines to have their own privacy. When this is the case, the datafile privacy will be the highest one, and individual measurements will have their own individual ones.

We haven't created/encountered any of these importers yet.

**Comment by robintw** [comment]
That makes sense, I'll close this issue then.
