### ISSUE TITLE
How to run merge with databases that might be at different versions?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#508]
This has become a higher priority issue now, as we're doing various schema alterations in our work at the moment, and these could be applied to the master database before the analyst gets back from sea with her SQLite database to merge.

The simplest thing to do would be just to tell the users to do a database migration to the latest version for both the master and the slave before merging. This would require us to make sure that all our migrations were working properly - which is something we've had some issues with in the past.

In terms of checking this before the merge: it's actually quite difficult to determine whether the databases are at the same version as we'll be merging from a SQLite database into a Postgres database, and they have different migration IDs and different sequences of migrations (ie. one database type can have more or less migrations overall than the other). I'm not sure how we solve this - do you have any ideas @BarisSari?

**Comment by IanMayo** [comment]
Hmm, I guess we could check if the SQLite snapshot alembic is up to the level of the current Pepys installation.  If it isn't, then  we warn the user that we need to modify it.  If they allow it, we run "Migrate" on the snapshot from within Pepys_Admin.

**Comment by robintw** [comment]
Unfortunately that won't work in a simple way, as the Postgres and SQLite alembic migrations have different version IDs - so I don't know how we can tell that they're both at the latest version - it's not as simple as just comparing the version IDs.

@BarisSari do you have any ideas on how best to do this?

**Comment by IanMayo** [comment]
Let me describe my understanding:
* Pepys is installed at 0.0.18
* PepysAdmin is connected to a PG database
* That PG database has been migrated to 0.0.18
* User wants to import SQLite at 0.0.16
* PepysAdmin checks with user, then runs migrations on SQLite snapshot to bring it to 0.0.18
* PepysAdmin imports snapshot into PG

**Comment by robintw** [comment]
Ah, I think we've been talking about different sorts of versions.

I was talking about the alembic versions (hashes like `d5d740c76aa3`), but you're talking about Pepys versions like `0.0.18`. I don't think we currently store the Pepys version used to create/update the database in the database anywhere, so in your suggested flow above we wouldn't be able to find out that the SQLite database was at Pepys version 0.0.16.

I'll have a think about how best to do this. I'm not sure whether we actually want to store the Pepys version in the database, as that can be independent of databases changes (eg. there could be a Pepys version change without any database schema changes). I'll have a think anyway.

**Comment by IanMayo** [comment]
We may be exposing a shortcoming in my understanding of Alembic versions 🤣 

PepysAdmin encounters a SQLite file that the user wants to import.  Before we do that, we apply any pending alembic versions to that data-file. We don't think about 0.0.16, but we just establish that there are pending SQLite migrations to bring it to the "current" state (which happens to be 0.0.18).

**Comment by BarisSari** [comment]
I was thinking that we might use dates in the migration scripts to compare but we have many more migration scripts for SQLite which weren't necessary for Postgres. So, it is not a good option. If we run migrations on SQLite before running merge, I'm afraid that we might break the database if there is any inappropriate data. I'll think about it more next week.

**Comment by robintw** [comment]
Hmm, I'm concerned about this - because I can't see a way forward here apart from running a migration on a SQLite database. In what way do you think this might break the database?

If the Postgres db is at version X and the SQLite database is at version X - 2, then what choice do we have apart from to migrate the SQLite database?

It'd be good if you could prioritise thinking about this @BarisSari, as I believe the client is intending to merge databases fairly soon.

**Comment by BarisSari** [comment]
Actually, I think I couldn't explain it well. What I'm concerning is as follows: 

The database will be in a state between one migration script and we should traceback in which line the migration failed. Otherwise, we can't continue to migrate. When Alembic runs again, it will say "_XXX already in the database_" etc. In this kind of problem, I do the followings: 
 1. Check the alembic error. 
 2. Comment out the applied lines in the migration script 
 3. Find a solution (checking which table/entity might cause this problem)
 4. Run the migration again. 

But the client will have huge data in the tables and I think we will not able to reach the database. 

So, migration scripts won't break the database. However, they might break the migration workflow.

**Comment by robintw** [comment]
Are we likely to end up in a situation in which the migration has failed though? I guess we aren't always testing our migration scripts on databases full of lots of data - which might make them fail.

I'm not sure how we deal with talking the clients through a migration problem - it could be tricky.

As an interim step, do we need to come up with some (fairly strict) instructions for doing a merge. Something like:

1. Take a copy of the SQLite database you're going to merge from, as a backup.
2. Open that SQLite database in Pepys Admin and run the migration option
3. Open the Postgres database in Pepys Admin and run the merge option, choosing the SQLite database that you just migrated.

Do we want to automate any of this (eg. forcing a migration before the merge is performed in Pepys Admin), or do you think it'd be better to just give instructions (then we can get to use to do different bits in between the steps of the instructions if things go wrong)?

@IanMayo Any thoughts?

**Comment by BarisSari** [comment]
> Are we likely to end up in a situation in which the migration has failed though? I guess we aren't always testing our migration scripts on databases full of lots of data - which might make them fail.

I'm not sure whether it's likely or not. We have only one test for now, and that runs the migration option for an empty SQLite database in Pepys Admin. I think we -at least- might load sample data first and run the migration option.

I'm up for both automating the steps and giving instructions. Let's wait for @IanMayo's thoughts.

**Comment by IanMayo** [comment]
@robintw - yes, I think we should clearly document the merge steps - and yes, your steps seem fine.

I also think we should check the SQLite snapshot schema is up to date before doing the merge - and only allow it to happen if it's up to date.

Yes, @BarisSari - it seems a good idea to test the migration on a populated database.  We do try to have sample data for all the entity-types that we encounter in data-files.  So, loading all the sample data would give us a broad range of data (though we may wish to skip the really large 100Mb datafile).

**Comment by robintw** [comment]
@BarisSari Is there a way to check that a SQLite database is at the latest version of the schema as of that release, without trying to upgrade it? Is there an alembic command that will give the version identifier of HEAD, and then we can compare it to the alembic version stored in the database? Or a --dry-run argument for alembic upgrade?

**Comment by robintw** [comment]
@BarisSari I guess what I was thinking was whether we could add some code to the merge function which just tells us whether the SQLite database schema is fully up-to-date, _without_ actually doing a migration (because we want the user to have control over whether to do the migration or not).

By 'fully up-to-date' above I mean that the SQLite database is at the latest migration for the release of Pepys that is installed at the master database location. I suppose one way of doing this would be to add code to the merge option to create a new SQLite database and initialise it, then compare the alembic version stored in that database with the alembic version stored in the slave database that we want to merge - but there is probably a better way of doing this with alembic commands/API.

**Comment by BarisSari** [comment]
> @BarisSari I guess what I was thinking was whether we could add some code to the merge function which just tells us whether the SQLite database schema is fully up-to-date, _without_ actually doing a migration (because we want the user to have control over whether to do the migration or not).
> 
> By 'fully up-to-date' above I mean that the SQLite database is at the latest migration for the release of Pepys that is installed at the master database location. I suppose one way of doing this would be to add code to the merge option to create a new SQLite database and initialise it, then compare the alembic version stored in that database with the alembic version stored in the slave database that we want to merge - but there is probably a better way of doing this with alembic commands/API.

Thanks for the explanation, @robintw . If I understand it correctly, I think I have a better idea. Why don't we use `latest_revisions.json` to check the latest migration for the release of Pepys at the master database location? Isn't it have the latest migration script's revision ID? We can compare it with the slave database's alembic version. I don't think that we need to create a new database and initialise it because when we do that, we will stamp the `alembic_version` table using the value from the JSON file I mentioned.

**Comment by robintw** [comment]
Of course - I don't know why I didn't think of that. I'll get on with implementing this - thanks!

**Comment by robintw** [comment]
This was fixed by #545.
