### ISSUE TITLE
Make CSV import of reference/metadata more robust

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#517]
At the moment, we're likely to get crashes in various situations such as column names being incorrect, or formatting of the CSV generally being incorrect.

The code that needs a lot more error checking in it is in `import_from_csv` in `data_store_utils.py`.

**Comment by BarisSari** [comment]
Do you think #519 fixed this issue, @robintw ?

**Comment by robintw** [comment]
Yes, I think it did.
