### ISSUE TITLE
Case sensitivity of names

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#527]
I've realised that currently we could create platforms with names of `Dolphin`, `dolphin`, and `DOLPHIN` and they would be considered to be different platforms. The same applies for all other places where a string field is used as part of an identifier - for example `name` in a lot of places (including reference tables like Privacy and Nationality), `identifier` for Platforms and so on.

I don't know if there is a way to resolve this in the database - saying that the unique clause should be case insensitive?

Regardless whether we do something in the database, we should probably change some things in the code to compare things in all upper-case or similar. Doing this naively would make the interface look worse, as everything would be in uppercase - so we might need to do some combining of comparing in UPPERCASE and displaying in Title Case.

Thoughts?

**Comment by IanMayo** [comment]
Yes, good thinking. 

> comparing in UPPERCASE and displaying in Title Case

I guess we could compare in U/CASE and display in the original case (as originally entered by the analyst).

> unique clause should be case insensitive

This looks possible in PG, though maybe not in SQLite. The analysts may be able to live with that _constraint_.
