### ISSUE TITLE
Pepys Admin application

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#53]
In the current phase of development, we will have to introduce the `Pepys-Admin` application.

The only function of it to start with, will be to export data.  But, we can usefully include a database status command to.

Note: this is a python project with an interactive command-line loop: https://docs.python.org/3/library/cmd.html

The application will take an optional command-line parameter, `-db`.  If provided, the application will open that SQLite database.  Otherwise, the application will connect to the PostGres instance that's used in the rest of Pepys-Import.

When the application opens, it will display `Pepys-Admin` banner text, similar to how we do in Pepys-Import.  It will then show the database connection settings (again, like import), then the available commands:
* e - Export (to start the export process)
* i - Initialise (import different sets of stock data)
* s - Status (to report on the database contents)
* x - Exit (to exit the application)

<h2 id="export">Export</h2>

In Release-1, we export by datafile name. So, after selecting `Export` we will use the fuzzy search to let the user search for a datafile by name.
In Release-2, we export by platform name and date. So, start with fuzzy search for platform name, then display a numbered list of datafiles/sensors that contain data for this platform. The user then selected an index number of a data-file, and we export data for datafile, for that sensor.  So, I guess the view will look like:
```
1) GPS File_a 12/07/20 14:22-13/07/20 13:43
2) GPS File_b 13/07/20 14:22-13/07/20 16:43
3) SINS File_c 11/07/20 14:22-13/07/20 17:43
4) WECDIS-GPS File_d 10/07/20 14:22-13/07/20 18:43
5) WECDIS-GPS File_e 15/07/20 14:22-13/07/20 12:43
0) Cancel
```
Selecting 1 to 5 will then ask the user for the filename (offer platform name as default), then export that datafile to the current folder.
Selecting 0 will cancel
After either, we return to the top level command loop.

<h2 id="initialise">Initialise</h2>

This will allow the currently connected database to be configured, using a range of commands - the existing functionality is shown in the code snippet shown below.

In order to allow a "fresh" start, a command will be provided that removes all tables (and data) in the current database.

Then the user will be able to create the Pepys tables within the database.  Then the user is able to pull in a range of types of background data, as shown below.  But, instead of TEST_DATA_PATH, the relevant files are taken from the current directory.

```
   self.store.initialise()
   self.store.populate_reference(TEST_DATA_PATH)
   self.store.populate_metadata(TEST_DATA_PATH)
   self.store.populate_measurement(TEST_DATA_PATH)
```

1. Clear database
2. Create Pepys schema
3. Import Reference  data
4. Import Metadata
5. Import Sample Measurements
0. Cancel

<h2 id="status">Status</h2>

*Note:* see the `TableSummarySet` class, and it's usage in the unittests.

Show a tabular summary of the database:
```
## Measurements
States: 2023
Contacts: 2342
Comments: 234
## Metadata
Platforms:  5
Datafiles: 12
(etc)
```
On completion, return to the command loop.
### Exit
Exit the application.

**Comment by IanMayo** [comment]
@tahirs95 - we need some more error checking in the admin_cli, please.

1.  If the database doesn't exist, the scripts should report that in an error message to the CLI, the scripts should not fail.
2. In the `clear database` action, the scripts should not fail if the database is empty. So, check each table exists, before trying to clear it.

Note: I also get this error when existing the Admin_CLI:
```
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Apps\20200303_pepys-import\pepys_admin\admin_cli.py", line 210, in <module>
    AdminShell(datastore).cmdloop()
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cmd.py", line 138, in cmdloop
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cmd.py", line 216, in onecmd
  File "C:\Apps\20200303_pepys-import\pepys_admin\admin_cli.py", line 185, in default
    self.aliases[cmd](arg)
  File "C:\Apps\20200303_pepys-import\pepys_admin\admin_cli.py", line 174, in do_exit
    self.close()
  File "C:\Apps\20200303_pepys-import\pepys_admin\admin_cli.py", line 178, in close
    if self.file:
AttributeError: 'AdminShell' object has no attribute 'file'
```

**Comment by robintw** [comment]
Looking at the original comment in this PR, I think all this functionality is implemented now. Do you agree @BarisSari, @IanMayo?
