### ISSUE TITLE
More capable REP Parser

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#54]
The existing REP parser only handles the simplest REP formats.

This document details the format: https://debrief.github.io/tutorial/reference.html#replay_track_format

We should verify/test that the parser handles these idiosyncracies:
* [ ] Decimal degrees, with zeros for mins/seconds
* [ ] Decimal minutes, with zeroes for seconds
* [ ] `NaN` for depth
* [ ] Presence of extended symbology fields (just ignore them)

**Comment by robintw** [comment]
I've been working on this in #258, and have a question:

In the REP parser we say:

```
if depth_token == "NaN":
                self.depth = 0.0
```

Do we actually want to do this? Surely if the depth is set to NaN then we want to record depth as None - ie. a missing value?

**Comment by IanMayo** [comment]
Yes - you're completely right.  

But, I'm not sure whether we should `set value as None` or `not set the value`.  I wonder how the database handles it.  If we fail to set a value, I wonder if it gets initialised as zero?

Any thoughts @robintw  or @BarisSari ?

**Comment by robintw** [comment]
Fixed by #258 and #261
