### ISSUE TITLE
Export database content to CSV

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#557]
On Monday a user is going to create a CSV file that will be used to add a "GPS" Sensor to each surface ship.

I'd like to take some steps to help out.

The analyst will need to produce a CSV with every surface platform, and the essential identifiers for those platforms (id, nationality).

This is a lot of work, but would be easier if the "View data" commands had versions that output to CSV.

So, could we modify `pepys_admin` so that Option 6 `View Data` had:
```
1. View table
2. Output table to CSV
3. Run SQL
4. Output SQL results to CSV
```

For the CSV commands, the user will be offered a CSV filename to use.  For "Output table to CSV" it will be "Pepys_Output_`TableName`.csv".  For "Run SQL" it will be "Pepys_Output_`SQL Query`.csv"

The CSV file would be created in the current working directory.  Aah, for `Pepys Admin` from Start Menu - it doesn't have a working directory (I don't think it does...).  In that case it should be the Windows Desktop folder.  On other systems, the user's home folder.

**Comment by robintw** [comment]
Note from Slack: We want to export _all_ columns (as they can always be modified in Excel later if necessary), not just the columns that are displayed in the UI (which are only the non `deferred` columns).
