### ISSUE TITLE
Allow Enhanced Validator to be relaxed

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#562]
Sometimes our analysis are doing "Fast Analysis" - which does not require a deep analysis of the data.

For this, they just want to create a plot of where the ships were, and the course/speed data isn't important.

Our enhanced validator is causing them a pain in this mode.

We agreed this strategy:
1. Load/parse data as present
2. Run enhanced validator (if applicable for that loader)
3. At the first enhanced validator error, report it to the user, and ask if they want to:
    a. Skip enhanced validator for this file
    b. Carry on running the validator, logging errors

**Comment by BarisSari** [comment]
I'm working on it, @IanMayo .
