### ISSUE TITLE
Trouble cloning Pepys-Import repo

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#563]
Developer intends to write new parser.  Has started by cloning repo. Got error:
```
sudo git clone git@github.com:debrief/pepys-import.git
Cloning into 'pepys-import'...
Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Switched to `https` and it _just worked_: `git clone https://github.com/debrief/pepys-import`

I get the same error when running git clone _without_ the leading `sudo` on macos.

We should probably understand the problem, and correct the documentation here: https://pepys-import.readthedocs.io/en/latest/developer_guide.html#clone-the-repository

**Comment by robintw** [comment]
This is a fairly common git problem. To clone using the `git@github...` syntax you need to have SSH keys set up and shared with Github. Many developers will have these set up (as they are useful in various other ways too), but I imagine many of the developers at the client will not. It's less important if you're not going to be contributing back to Github anyway.

So, I think we can change the docs - and any experienced developers who want to use the `git@github` way will probably know what to do anyway.

**Comment by IanMayo** [comment]
@robintw - yes please, I'd appreciate you updating the docs (no rush).
