### ISSUE TITLE
GeoPDF - high frequency time steps

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#567]
We have an initial dynamic track plot on GeoPDF working. 

There is merit in investigating how many time-step layers Acrobat Reader can support.  This will inform whether we enforce a maximum number of time steps when exporting from Debrief, or we let analyst produce a plot at any time interval, but encourage them to "test-drive" the exported PDF.

One constraint may be the number of pixels for each hover-button for the time-bar.  Once a button is less than one pixel wide they're effectively wasted.

**Comment by robintw** [comment]
This has been completed in the latest GeoPDF work.
