### ISSUE TITLE
GeoPDF - display narrative entries

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#568]
Value can be added to a dynamic plot by displaying text messages at relevant points in time.

These will typically be generated by a subject-matter-expert, and describe significant events.

One way of doing this would be for the analyst to put a rectangle on a _dull_ part of the plot prior to exporting.

If there is only one rectangle visible on the plot, then this set of bounds would be used to display the series of time-stamped data objects.

As the user moves through the time period, the rectangular box will display most recent narrative comment at or before the current time.

We may have to experiment with whether the rectangular box should be geo-referenced (fixed lat/long bounds) or in screen coordinates (like our time controls).

**Comment by robintw** [comment]
I think this is completed now.
