### ISSUE TITLE
Validation error on REP data

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#583]
We have a very large file of REP data.  The data was computer generated, without (obvious) room for human error.

But, it fails enhanced validation: 
![image (3)](https://user-images.githubusercontent.com/1108513/93997530-67ae9e80-fd8b-11ea-8c76-e0de0867b843.png)

We should investigate the cause of the error, in case it represents some edge case.

Test data: 
[bulk_tracks.rep.zip](https://github.com/debrief/pepys-import/files/5267218/bulk_tracks.rep.zip)

This issue is relatively low priority.

**Comment by robintw** [comment]
Fixed in #650.
