### ISSUE TITLE
Referential integrity with bulk data

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#586]
> Parsing hundreds of white shipping [*] units got too tedious - analysts gave up and just dragged their rep files directly into debrief. It's suggested to have default sensor, sensor types per Importer and the cli ability to bulk 'just import the names, however silly'.

Maybe the use of _RESOLVER:DEFAULT_ would have overcome the above issue.  

Hmm, but resolver:default values may be hard-coded in Pepys, and analysts may wish to use different defaults in different scenarios.

A defaults config file may be preferable.    So, for a folder of white-shipping data-files, they create a single defaults config file that provides nationality, sensor, privacy, etc.  Then use `-RESOLVER:white_config.ini`.   (Maybe not `.ini` files, I don't mind - but we use them already)

Aah, we can probably grow something quite useful here.  If the default value isn't found in the config file, then Pepys asks at the command line.  So, an analyst may create a defaults file with nationality and sensor privacy, platform privacy.  For all data loaded with that config file in the root folder, those values get auto-filled, but the analyst still provides platform name, platform type, sensor name, sensor type, etc.

[*] White shipping = general shipping that is unrelated to the exercise.  Ferries, fishing boats, cargo ships etc.

**Comment by IanMayo** [comment]
Subsequent thoughts.  

Hmm, we 'could' allow the resolver file to be used on the command line. But, the analysts have got used to `right-click` > `Send to Pepys`.  We don't have ability to use command line options in that flow. An alternative strategy would be to look for a file with a particular filename in the folder containing each datafile: `pepys_defaults.ini`.

**Comment by IanMayo** [comment]
CF to consider. IM suggested improved support for AIS-source.

**Comment by IanMayo** [comment]
I think it may be worth talking this issue through with analysts. How can we streamline the time to load bulk data? When can defaults be used?  Can we auto-generate some ID values?
This _could_ overlap with the use of `pending` values for nationality & platform-type, plus some kind of defaults/unique-ids for platform identifiers when they're not currently known.

**Comment by IanMayo** [comment]
@robintw and I just discussed this.  We came up with this two-fold strategy.

## General concept
* We can't  introduce an `unknown` platform instance, since tracks in a datafile each need to be treated as a separate platform - in order to generate tracks
* But, we could introduce `Unknown` values for Nationality and PlatformTypes.  Bulk tracks for which the Pepys metadata may never be known (or isn't relevant to analysis) could be assigned to this nationality/data-type.
* For data-formats where the platform metadata isn't available, the importer could create the tracks/platforms as normal, but assign the platform nationality and platform-type as Unknown
* For other importers modify the platform resolver so that the analyst gains these options:
    * Store this platform with default `Unknown` values for Nationality and PlatformType
    * Store this and all other remaining platforms from this datafile as `Unknown` for Nationality and PlatformType

In other situations, the metadata for a platform may not be available at the point of import, but the analyst may know that it will arrive later in the day, or at some point in the future.  This _could_ be handled through the above `Unknown` practice.  But, alternatively we could introduce Nationality and PlatformType of `Pending`.   With this specific value, analysts can quickly return to `Pending` platforms when the data arrives.  I _guess_ we could also support `Mark this and other remaining platforms as Pending`.

## Implementation
The above logic would sit inside the command-line platform resolver. This would gain a toggle that indicates if the platform should be treated as `Unknown` (or, potentially, `Pending`).  
For importers that handle bulk data, this would be set to `Unknown` in the platform resolver - which just creates the platform as `Unknown` nationality and platform-type.
For importers that don't handle bulk data, the platform resolver logic would offer `Create as Unknown` and/or `Create as Pending` when it encounters a new platform name.
This embeds the logic for `unknown` and `pending` inside the resolver logic, instead of in most of the importers.

If the user selects 'All further platforms as unknown` or `All further platforms as pending` then the resolver must remember their answer - in order to correctly handle subsequent platforms.

**Comment by robintw** [comment]
That all sounds good @IanMayo.

My only minor concern is how we tell the resolver to mark all future platforms as unknown/pending, without making the resolver too tightly coupled to the FileProcessor/datafile. At the moment they're completely separate, but we'd need a way of letting the resolver know that we've finished processing a file, so that we can 'reset' the flag so it doesn't mark all platforms as unknown for the next datafile too. That's definitely solvable though.

**Comment by IanMayo** [comment]
Good point.  We _Could_ handle the flag as meaning for the rest of the import (not just the rest of the file).

**Comment by robintw** [comment]
I can imagine both would probably be useful - but then we start to give the user too many options (unknown/pending and for both of those for this file/for all files).

**Comment by IanMayo** [comment]
The analysts have endorsed the strategy found here:
https://docs.google.com/presentation/d/1uNFjWXxvI01TYL8aS1g2Tf9QnexQJq4v0A8JWvFN2qc/edit#slide=id.p

Let's defer `Pending` - and stick with unknown nationality/platform-type for now.

**Comment by robintw** [comment]
I've been having a think about this tonight, and working out how I'm going to implement it. A couple of questions:

1. If the data file has platform names in it (some do, some don't), then we end up with a platform name passed to the platform resolver. If a name is passed _and_ we need to treat it as an unknown platform (ie. the flag is set to treat this as an unknown platform, or the user chose 'Store as unknown'), then should we use the name that has been passed, or should we generate a random UUID-based name?

The benefits of using the name that is given is that if that name is a unique ID for the vessel (eg. an IMO ID) then all of the entries for that platform will end up linked together (even if they came from separate data files imported at separate times). However, we also have the problem that if the name in the data file is a non-unique name then all those unrelated vessels will be linked into one Platform object.

What do you think @IanMayo?

2. Once we've created a Platform, we need to create Sensors on that platform. These sometimes need input from the user to choose what sort of sensor it is, or the name of the sensor etc. If we're trying to reduce user interaction for these unknown platforms, then we don't want to be asking the user about the sensors. Therefore, do we need to introduce an unknown sensor type too? And create these 'unknown Sensors' if they're being created on an unknown Platform?

**Comment by IanMayo** [comment]
Sure, @robintw 

1.  Let's leave it down to the importer-writer.  If they know the platform-name/ID in this file type is unique to that platform, then they provide it.  If they don't know it's unique then they store it as identifier with a UUID as platform name.  (or with a blank platform name for which Pepys inserts a UUID).

2. Hmm, good question.  I agree that we should avoid the interactions for sensor.  Part of me thinks that the source for these positions will always be GPS.  But, I guess it could be radar.  So yes - we'll need an `Unknown` sensor of `Unknown` sensor-type.  I propose that the `Sensor` privacy will be the first (lowest) value in the privacy column - same for the platform.  So, it's may just be the `Datafile` that gets a user-specified privacy.

**Comment by robintw** [comment]
Ok - one more:

In response to your answer to Q1: what do we do when its an importer which expects the user to be entering details for the platform, and so provides the platform name to help the user choose which platform entry to select - but instead the user chooses to store the platform as unknown. What should happen there? Should we use the platform name provided by the importer or not? There will be lots of situations in importers where the name is provided from the file, but that name isn't unique.

**Comment by IanMayo** [comment]
Hmm, tricky.

If a name is present, but the user wants to treat the platform as `Unknown`, then I guess we store the platform name, provide a UUID as identifier, and use the `Unknown` entries for `Nationality` and `Platform-Type`.
