### ISSUE TITLE
EAG parser - action on error

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#587]
> The eag parser might fail to import any states due to an error, but will still store the file in pepys, causing 'file already imported' behaviour when the analysts fixes the file and puts it back through

We need to investigate this.   It looks like the EAG parser should not create the data-file if there is an error.

Hmm, but I think we create the datafile in the database before we start loading the rows.  

Hmm.  Maybe we need to delete the datafile record if there's a testing failure.  Or, we only create the datafile once we've passed the tests.

**Comment by robintw** [comment]
I've investigated this a bit, and it's a broader problem than just EAG files - but also a bit complicated. If an import entirely fails then the Datafile object is still created and put into the database. If we try and import exactly the same file again (same size and hash) then we will get an error saying that the file has already been imported. However, if we fix the errors in the file then the hash and size will change - meaning that it should be accepted as it counts as a different file.

So:

1. I'm not sure how the clients are finding this problem - as the hash _must_ change when they fix the file.

2. We probably do still have a problem, as if the import entirely failed then we probably don't want to have an entry for this file cluttering up the Datafiles table. @IanMayo is that correct? I can see some potential situations in which we might want it to be kept (eg. we're repeatedly trying to import a folder of 500 files, if there is a file which has already been attempted and gave no valid data, and we haven't changed the file, then maybe we don't want to waste time trying to import it again)

Anyway, in terms of the code, we create a Datafile entry before we do any checks on the files at all - at https://github.com/debrief/pepys-import/blob/develop/pepys_import/file/file_processor.py#L269

We need that datafile object to do any of the rest of the importing - as we use methods on that objects. Therefore, if we do want to make sure we don't have a Datafile entry for files that completely failed import, then it's probably best that we take the second of the options suggested above, and delete that datafile entry if all the tests fail.

Thoughts @IanMayo @BarisSari?

**Comment by IanMayo** [comment]
@robintw - we only hash the first megabyte.  So, if the fix is later in the file, the hash could be unchanged:

![image](https://user-images.githubusercontent.com/1108513/97974627-c4a46800-1dbf-11eb-8a2f-1f40278dfc96.png)

Yes,  I think we should adopt option 2.   

I don't think the 500-file-folder scenario is an issue. If we keep the processed (but effectively empty) datafile, Pepys will report a "File already loaded" error next time around. It does seem legitimate to delete the datafile when Pepys establishes that it contains no content.

**Comment by robintw** [comment]
That's interesting - I'd forgotten we were only hashing the first 1 Mb of the file. I assume that's for speed reasons

I'll go ahead and add the deletion of the datafile entry.
