### ISSUE TITLE
Wrong number of planned turns displayed

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#589]
The WorldState panel shows the number of planned steps displayed on the map, which frequently is clipped to just one.

The Routes object should have another parameter, that stores the total number of planned steps, regardless of if future steps is capped.

![screencast](https://i.gyazo.com/b4286432d8e59e3bcabc461183ad9421.gif)

**Comment by robintw** [comment]
Should this issue have been created on the Debrief repo? It doesn't seem to relate to pepys-import.

**Comment by IanMayo** [comment]
Oops, thanks for that @robintw

**Comment by IanMayo** [comment]
Closing. Created in wrong repo.
