### ISSUE TITLE
Set up CI on Windows too

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#592]
I think it would be useful to have Continuous Integration running on Windows too - as that is the platform that our clients use (and it's very easy to accidentally write some code that won't work properly on Windows - eg when dealing with path separators).

I've recently been experimenting with Github Actions on one of my other projects, and it makes it quite easy to have cross-platform CI.

How do you feel about me trying to set this up for this repo @IanMayo?

**Comment by IanMayo** [comment]
That's great @robintw  - thanks.  

The continuous build on MS-Windows would be useful for both verification and convenience of release.

I guess it's worth you doing some research first, then the 3 of us discussing the options, if necessary.

**Comment by robintw** [comment]
Completed in #598
