### ISSUE TITLE
Offer interactive demos of PRs

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#597]
As discussed on Slack, we're looking to find a way to offer interactive demos of new features in PRs with minimal effort. This will help people like @clenoble and the clients to give useful feedback on the UI design of new features.

This issue will put forward a rough proposal (to be fleshed out in more detail as we go forward) as to how we could do this using Binder.

## Aim:
Provide a link in a comment on a PR that loads an interactive environment where the user can interact with a demo showing the new feature that is implemented in the PR.

Specifically, this should be:

 - quick (the user shouldn't have to wait ages for builds to complete when they click on the link)
 - easy to use (the user shouldn't have to remember Pepys command-line syntax, or decide how to set things up to get to a situation where the feature is usable)

## Potential solution
[Binder](https://mybinder.org/) can provide an interactive Python environment through a Jupyter notebook. We already have this set up for running the [Getting Started notebook](https://mybinder.org/v2/gh/debrief/pepys-import/develop?filepath=docs%2FPepys%20Getting%20Started%20-%20Binder.ipynb) (click that link to go to Binder and test it). We have already extended the `notebook_xterm` Jupyter extension to work better for embedding terminals in notebooks.

A preliminary process flow could go something like this:

1. The Pepys developers create a PR implementing a new feature (the example we will use here is adding the ability to merge two entities - such as Platforms or Sensors - in the database).
2. As part of the PR they push a Jupyter notebook to the `demos` folder. This will have some Markdown text at the top explaining what the notebook is demoing, and what steps the user should take to use it. It will then have a number of cells setting up a situation in which the user can experiment (in this case, for example, it would be some code to create multiple platforms that can then be merged). After that it will have a cell containing the Pepys command that the user should run to experiment with the UI in a terminal in the notebook - for example to run Pepys Admin it would be a cell containing `%xterm python -m pepys_admin.cli`.
3. Once the PR is ready for review by the users, a developer posts a specially coded comment, something like `!build PATH_TO_NOTEBOOK`. This runs a Github Action that triggers a Binder build (using either https://github.com/marketplace/actions/trigger-binder-build or https://github.com/jupyterhub/repo2docker-action) - this means that when the user clicks the link to Binder they won't have to wait for a build, instead it will open almost immediately. The Github Action will then post a comment to the PR including a link to Binder which will open the correct notebook automatically (if a comment has already been posted with the link, then this comment will just be updated with a new link if necessary).
4. The user can then click the link in the PR comments, which will take them to Binder. They will then have to run the cells in the notebook (or just click the 'Run all' button) and the final cell will take them to an interactive terminal session, running the correct Pepys command. They can then experiment and provide feedback.

**Notes:**

1. We could skip step 3 and run builds automatically for each push to the PR, but there are two problems with that:
    - We won't know which demo notebook to open automatically in Binder (I guess we could have a naming convention or something)
    - We will hammer Binder's servers by building a lot of Binder images that probably won't be used. Binder specifically asks users not to do this.
2. This is separate to the other issue for running CI on Windows (#592), but we could integrate them by providing a link at the top of the Binder notebook that would allow the user to download a pre-built Windows deployment image of the PR for local testing.
3. I've looked for alternatives to Binder, but there really don't seem to be any other services out there that would do what we want. I think the only other options would be creating an entire web service of our own to allow us to run Pepys online, which would be a huge amount of work, or doing some sort of complicated web-based SSH to a server that ran batch scripts to run Pepys with the relevant setup - which would again be a lot of work.

## Feasibility
From the research I've done, I'm confident that I can get this working. As linked above, there are already Github Actions that will do the Binder builds. We just need to put the plumbing together to trigger by comments, build the right thing, etc.

What do you think @IanMayo @BarisSari?

**Comment by IanMayo** [comment]
Yes, this all sounds fine.

I was prompted in this aspiration due to the `Heroku` integration we have for a web-based app.   See the `View deployment` button near the bottom of this PR:
https://github.com/serge-web/serge/pull/550

For each commit to each PR, Heroku takes a copy of the relevant branch, and builds a virtual server.

Our challenge is slightly different, since we want to lead the user/reviewer to a specific notebook - so it's more complex than plain `View deployment`.

Note: I _think_ we need the binder to rebuild for each commit produced after the _special comment_ is provided.  I know the _separate_comment_ is required if we're need the demo file path to be specified.  But, the transition from `Draft PR` to `PR` could be used as the trigger to start creating Binder builds.

Anyway - please go for it, I look forward to having a play.

**Comment by IanMayo** [comment]
Note: while looking at a PR I was playing around with, I saw that our ReviewNB integration means we get reviewable Notebooks, through they're not presented in RISE form.

But, while ReviewNB provides a visual comparison of two versions of a Notebook, it doesn't allow them to be run, which is what we're after in this PR.

![image](https://user-images.githubusercontent.com/1108513/99096579-5b4a0380-25ce-11eb-87e1-a48fcfbef0cd.png)

**Comment by robintw** [comment]
Completed in #635 and #637
