### ISSUE TITLE
Different ordering of file processing on different platforms/systems

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#599]
## Version
HEAD

## 🐞 Description
When a folder path is passed to Pepys, it processes all files in that folder. It seems that on different systems, it can process the files in different orders - which can lead to some tests failing if they depend on the order.

## ⚙️ Current behavior
The order in which files are processed differs between OS X and Linux, and possibly also between Travis Linux and Github Actions Linux. This causes problems when, for example, the first entry of a list is checked - but because the files were processed in a different order, it is actually the 3rd entry (for example) which is the one that should be checked.

## ⚙️ Expected behavior
Files should be processed in the same order regardless of platform and operating system, or tests should be designed which are not dependent on the ordering of files. Possibly both approaches should be taken.

## 🔢 Steps to Reproduce
It's easiest just to look at the [test results on Github Actions](https://github.com/debrief/pepys-import/actions/runs/347925850) which show three test failures. I've resolved these by getting each of these tests to just process a single file rather than a folder - which is probably a good thing to do anyway, as they don't need to process multiple files, and this speeds up the tests anyway.

## Discussion
I'm open to input as to whether we should do something with the file processing code to sort the file lists in Python before going through them, as the Python sorting functions should be platform-independent.

**Comment by IanMayo** [comment]
Yes, it seems a good idea to pre-sort the files so that they're processed in a predicable (and repeatable) order.

_Maybe_ the strategy to fix this is to reinstate Robin's test that processes a whole folder, then checking that the GitHub action test fails.  Then, apply the fix, to make the test succeed.

**Comment by BarisSari** [comment]
Hello, all. I didn't know that `os.scandir()` and `os.listdir()` returns arbitratry order lists: [link](https://docs.python.org/3/library/os.html#os.scandir)

> Return an iterator of os.DirEntry objects corresponding to the entries in the directory given by path. The entries are yielded in arbitrary order, and the special entries '.' and '..' are not included.

As you both suggested, I'm going to add sorting of the files before running file processor.

**Comment by IanMayo** [comment]
We still seem to have an issue here.  

There are two files in `tutorial\data` - `sample2.dsf` and `sample3.rep`.  In the tutorial, we instruct the user to run `Pepys-Import` on the folder.

On Macos `sample3.rep` gets processed first.
![image](https://user-images.githubusercontent.com/1108513/101653886-c228d400-3a37-11eb-8f1f-6881e7cb58cd.png)

On Windows `sample2.dsf` gets processed first.
![image](https://user-images.githubusercontent.com/1108513/101653934-d40a7700-3a37-11eb-9b1b-fa4d776e06a1.png)

We have this covered by unit tests - which aren't failing. Maybe this test is doing an operating-system specific sort to produce the "valid" answer, which could result in different orders on different operating systems:
https://github.com/debrief/pepys-import/pull/604/files#diff-b25c6f26510c122745fe8ad9c766d5975c794375e3726793c59ce4551bf63e6dR10
