### ISSUE TITLE
Give Celine ability to run Pepys

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#603]
## 🐞 Overview

We're hoping that @clenoble will be able to provide:
*  training materials to users
* UX design of new features
* review & feedback on new features during development

To get to that point we need to:
- [ ] educate Celine in the big picture of the [data model](https://docs.google.com/drawings/d/17DMS1SuTOC3ciARtMpAmARRSloeiAUFphYqm5O60KFs/edit)
- [ ] educate Celine in the big picture on data flows / business processes
- [x] let Celine experience the current user perspective (MS-Windows install, send-to, pepys-admin)
- [x] identify technology/toolchain that offers online running of new features

## 🔗 Feature

Supports #595

## 🔢 Acceptance criteria
- [ ] Celine understands necessary concepts
- [x] Celine has working local Pepys installation
- [ ] Celine able to provide UX feedback on Pull Requests

**Comment by robintw** [comment]
I think this is complete now that we've got interactive PR demos working. Do you agree @IanMayo, @clenoble?

**Comment by clenoble** [comment]
@robintw yes, I think I understand well enough.
