### ISSUE TITLE
Import fails with ? as letter in identifier

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#606]
## Version

0.0.23

## 🐞 Description

I've just run `pepys-import` from the `getting started` notebook.  For the platform identifier I entered `!234`.  At the platform creation step the app fell over, reporting an error.

Sadly, I can't now reproduce this.  Maybe it wasn't a `!` character. I've re-run the binder a few times, but can't find the offending character to use.

We should investigate what constraints there are on the types of character we use in the `identifier` field, and verify the user has entered acceptable characters in the input process.

## ⚙️ Current behavior

Import fell over when using _some_ special character as platform identifier.
## ⚙️ Expected behavior

App should either accept all special characters, or warn user that an identifier is using an unacceptable character.

## 🖥️ Screenshots

Sadly, I can't reproduce it.

**Comment by BarisSari** [comment]
I'm trying to reproduce it, @IanMayo. If I can't reproduce it, I'll at least write tests to check all special characters.

**Comment by BarisSari** [comment]
We're using the default character set (UTF-8) for the PostgreSQL:

```sql
(base) baris@bariss-MacBook-Pro ~ % psql pepys -c "SHOW SERVER_ENCODING"
Password for user baris: 
 server_encoding 
-----------------
 UTF8
(1 row)
```

I checked the `Command Line Resolver` and `DataStore`, but I couldn't find anything which might cause a failure. Then, I tested these characters and they all worked fine: `')/_!->|*]$,(\'^"%[.+{=~:<#}?&;@`. I will make further investigation tomorrow.

**Comment by IanMayo** [comment]
Thanks @BarisSari . It's probably not relevant, but I was using a SQLite backend.  I was running the `getting started with pepys` Jupyter notebook - which connects to a local sqlite file.

**Comment by BarisSari** [comment]
I used the same environment, @IanMayo. I hope I can find something tomorrow.

**Comment by IanMayo** [comment]
Lesson learned - I should have screenshotted the error as soon as I saw it.

**Comment by BarisSari** [comment]
Hello @IanMayo. I suggest closing this issue for now. I tried to reproduce it today but I couldn't. I thought more about writing tests for special characters but I don't think it will help us. Because we already know that [SQLAlchemy](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine.params.encoding), PostgreSQL, and SQLite use UTF-8 encoding as default.

**Comment by IanMayo** [comment]
Good advice @BarisSari - thanks for investigating.
