### ISSUE TITLE
Import - show delta of rows added after import.

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#609]
## 🐞 Overview
In Pepys Import, we show the number of rows present in some important tables before and after the import process.

It would be more important if the number of rows added was shown instead.

Actually, the _after_ could show a list of all tables that have received new rows (well, except for the admin-related tables, `extractions`, `logs`, `changes`).

**Update** in the client meeting on Friday, we discussed this feature. The client requested that the table be used as part of an _approval_ process.  So, we display the deltas table for each file, then ask the user if they want to add the data to the database.  The user story for this is that the user may be expecting 100s (or 1000s) of states in the datafile. But, if there are only 10, then something is wrong.  Or, if the analyst knows the datafile is for just one platform, but 3 are shown in the table, then there may be some typos to fix [*].   I appreciate this makes the task more complex, since we can't just do a delta on database contents.  I _guess_ we need to introduce counters for the objects that are about to be added to the database.

[*] Hmm, this feature is a pain. In _normal_ processing, we add new metadata items to the database as they arise (platforms, sensors).   But, we only add states once they have passed verification.  The above feature clashes with that practice - since the analyst may wish to not add the platforms.  This could require more thought, or some compromise.

![image](https://user-images.githubusercontent.com/1108513/98943445-6a09bb00-24e7-11eb-9162-6b30da6b6203.png)

## 🔗 Feature

None.

## 🔢 Acceptance criteria

- [ ] For datafiles covering a range of measurement types, the table at the end of `pepys_import` shows the increase in rows for all `measurement` and `metadata` tables that received new data.

**Comment by BarisSari** [comment]
I converted PR into the draft mode again. I'll continue my work when the feature is clear.

**Comment by IanMayo** [comment]
Ok @BarisSari - have just heard from clients.

    I think the 'interruption' is worth it to avoid corrupt data going into the database - I think that 
    far outweighs it personally. 

    I think it makes sense to write as many ‘checks and balances’ into the process as possible.

So, after each file we will show a table of number of rows about to be added.   Well, (if possible) we'll show two tables side by side. On the left hand will be a list of changed metadata tables, and on the right hand side will be a list of changed measurement tables (each with the number of rows to be added).

Hmm, if the numbers of items added to the Metadata tables are less than (say) 6 items, we should list those items instead of the count.

The user can select:
```
1. Import metadata
2. Import metadata and measurements
3. Don't import data from this file.
```
Option `1.` above will avoid analyst having to go through platform/sensor creation when the file is re-processed.

Note: if the defaults resolver is being used, we'll just effectively use option 2.

@robintw warned that:
     if we don't import the files themselves: we could easily end up with lots of 
    unused (and potentially invalid) Platforms, Sensors and so on

But, this review step (including listing new items) is the opportunity to decide whether the correct metadata items are about to be created.

Here is an illustration of how I think the "Just import metadata" would bring benefit:
* For the first (aborted) cycle, the user may have created platform (with type, identifier, trigraph, type, nationality, privacy) then sensor (with type, privacy). 
* Once the file has been fixed, the importer will look for the platform name.  The dialog will offer the above platform, and with one click it will be accepted & used.

When discussing this feature earlier, I suggested we may have to build up the objects in memory before this process, then only pushing them to database when user says to.  Since each import relates to one datafile, we _could_ just delete all measurements from that datafile if the user doesn't want to load them.

**Comment by BarisSari** [comment]
> Note: if the defaults resolver is being used, we'll just effectively use option 2.

@IanMayo, does this note mean that we need to change something to make option 2 _effective_? If yes, I think I missed what I should do for default resolver 🙂

**Comment by IanMayo** [comment]
@BarisSari - the important step is that when the defaults resolver is in use, we will not stop to ask the user whether to load the datafile.

There are a number of ways of doing this. One way would be for the `DataResolver` interface to have a method like this:
```
    class FileResponses(Enum): 
        ONLY_META
        META_AND_MEASUREMENTS
        SKIP_FILE

    def load_file(metadata_deltas, measurement_deltas) -> FileResponse
```

Our defaults resolver will always return `META_AND_MEASUREMENTS`, but our command-line resolver will display the tables, and ask the user which option to use.

**Comment by BarisSari** [comment]
Okay, thanks for the explanation 👍

**Comment by BarisSari** [comment]
@IanMayo, I have just realised that we keep metadata for failing files. I'm adding some codes for cleaning up metadata objects but it's only for the validated files. I mean I offer the menu above only if there's no validation error for that datafile. 

Do you want me to delete metadata objects of failing files?

**Comment by IanMayo** [comment]
Hello @BarisSari .  I know it's unusual, but that behaviour is by intention.  It is so that the user doesn't have to answer the questions when they re-process the fixed file.

Hmm, I think you are right.  If there is a validation error, we should still display the metadata tables delta, plus the choice of whether to load the metadata, or skip the file.

**Comment by BarisSari** [comment]
> Hmm, I think you are right. If there is a validation error, we should still display the metadata tables delta, plus the choice of whether to load the metadata, or skip the file.

Yes, I think it's more sensible. I'm going to do it after I complete the menu for the validated files.
