### ISSUE TITLE
Introduce new `Pepys-Viewer` app

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#610]
## 🐞 Overview
For some users, we wish to let them use Pepys-Admin to view data, but not to have access (or require training in) the rest of the Admin operations.

This could be met by providing a command-line parameter that gives an (apparently) different application:
* different welcome ASCII art (Pepys Viewer)
* application goes straight into the `6. View data` command mode
* exiting from this menu exits the application, rather than going back up to root level

The `View` menu may grow in the future as we add support for custom queries.

![image](https://user-images.githubusercontent.com/1108513/98944453-f8cb0780-24e8-11eb-9fc2-75f3041a194c.png)

**Note** this task will require both some Python changes, plus some MS-Windows trickery to create the new shortcut.

In the future the clients could choose to restrict who has access to `Pepys-Admin`.

## 🔗 Feature

N/A

**Comment by robintw** [comment]
Just a thought: do we want the user to be able to access the `Status` option from Pepys Admin too? If so, we'll need to think about how we provide access to that.

**Comment by IanMayo** [comment]
Thanks @robintw - I think _maybe not_ in the first version.  As the custom app loads it would show the version.  Plus we're not expecting this type of user to be interested in the Alembic version.

Was there some other piece of `Status` information you thought they would benefit from?

**Comment by robintw** [comment]
Just that it gives the number of items in each table etc, which may be useful.

We'll have to be careful if we're instructing non-technical users to view database tables from the View Data menu, as many fields are missed out of the view there (because of space limitations) so it might confuse them.

**Comment by robintw** [comment]
Just a reminder: when this is implemented, we must implement a training-mode version of Pepys Viewer too (see #614)

**Comment by IanMayo** [comment]
Fixed in #642
