### ISSUE TITLE
Add 'Training Mode' shortcuts on Windows

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#614]
## 🐞 Overview
Add Start Menu and Send To shortcuts for using Pepys in 'Training mode', where data is saved to a temporary SQLite file rather than to the configured Pepys database.

## 🔗 Feature
#595

## 🔢 Acceptance criteria
- [ ] Shortcuts are present and tested on Windows
- [ ] Tests show that training mode works without affecting the 'real' configuration or 'real' database

**Comment by robintw** [comment]
Various parts of this feature need discussion:

 - How 'temporary' do we want the database files to be? It would be useful if a user could start the training one day and finish it another day, so we don't want to put the database file anywhere it could be automatically wiped on logon/logoff. However, we may want a way for the user to reset the database file to 'blank' (or to a pre-populated state)
 - Do we implement this purely by setting the `PEPYS_CONFIG_FILE` environment variable in the batch script that runs Pepys - or do we want to add a `--training` command line parameter to the Pepys calls. The former is simpler, but the latter gives us more flexibility to choose where to put the file, wipe it if necessary etc.

It is potentially getting a bit too complicated, but I can see something like the following working:

- Using the `--training` parameter looks for a database file in a `Pepys Training` folder in the user's home directory, and uses that as the database.
- If that file doesn't exist, then it creates it and pre-populates it with some example data from the `sample_data` folder (ideally hiding the standard output from the import process, so all the user sees is `Populating initial training data...`.
- If the user wants to reset their training database, they either delete it manually, or we could offer a simple Start Menu shortcut called 'Clear Training Data'

Any thoughts @IanMayo @BarisSari?

**Comment by IanMayo** [comment]
> Temporary

Yes, it should be more persistent than the `/tmp` folder.  Yes, using the users home folder avoids cluttering the Pepys installation folder.

> `--training`

Yes, having this mode means we can introduce some extra steps at the start.  What you're suggesting sounds fine.
