### ISSUE TITLE
Don't show default value of new item in "Add a new xxx" question

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#617]
When adding a new platform, the presence of `default name` may lead a user to not realise that they can provide any name they like for the new entity.

![image](https://user-images.githubusercontent.com/1108513/99412083-40d49a80-28ec-11eb-850e-83e89c13db0e.png)

We should trim option `2.`, so that it just says `2. Add a new xxxx`, such as `2. Add a new platform`.

**Comment by BarisSari** [comment]
I have a question, @IanMayo. When we are adding a new platform, we give platform name's first 3 characters for trigraph and first 4 characters for quadgraph. Would you prefer deleting these default values, too?

**Comment by IanMayo** [comment]
Hello @BarisSari - no, once the user has entered a name, it's a _good guess_ that the first 3 or 4 letters are used.  

Aah, I see the confusion. We will still offer the default name, we're just re-phrasing the prompt, to remove `, default name "NELSON"`.

**Comment by BarisSari** [comment]
Okay, I got it 👍
