### ISSUE TITLE
Investigate way of moving `Back` when creating new entity

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#619]
@clenoble gave us some UX guidance:

> Having a back button gives you the reassurance to explore and possibly make 
> wrong choices without consequences. It's one of the most important principles of a good UX.

So, instead of going through all the steps to add a platform, then changing them at the end, Celine would like the user to be able to step back through the questions if, for example, they just realise they've entered the wrong thing.

This task involves investigating if its possible to have a special character (`.`) cause the process to move back a question, including repeatedly specifying it.

My first guess is that we would have to move from specifying the questions one by one in the code, to providing an array of `handlers`, each able to provide the question and store the response.  It would be this list of `handlers` that would be displayed at the end of the `add new item` process.

Note: having the questions in an array would also give us the ability to show `2/6` progress indicator for the user.

I _think_ that `add new item` is the only sequence of questions that would require `back` functionality.

The investigation should include the consideration of if the above can be implemented without introducing additional fragility.

**Comment by BarisSari** [comment]
I think it is possible to do it, @IanMayo. I will make some experiments to find out a way to add this feature with minimum complexity. Command Line Resolver has already a complex structure. I think we shouldn't make it more complex.

**Comment by IanMayo** [comment]
We're going to suspend work on this issue, since we haven't identified a way of delivering it that doesn't introduce complexity (and thus, fragility).

A discussion was held in Slack, but I'll post the significant aspects here, for posterity.

Baris:
I’m working on moving Back when creating new entity  task. I pushed a few commits but actually it’s scaring me a bit :slightly_smiling_face: because I feel like I’m rewriting the whole command line resolver from almost scratch. Here are the steps I have followed:
- Create empty dictionaries for keeping questions, responses, and validations(here)
- Create a new method which asks questions using the dictionary above(here)
- Fill question dictionary with add to platforms questions using this method.
- Fill validation dictionary with add to platforms response validators using this method.
- Create validate_xxx methods for each validation (like platform name is longer than 150, identifier is longer than 10, etc.)
- Change add_to_platforms so that it uses new methods
So, this change was already big (more than 250+ lines added). I gave it a try to see if I broke anything. test_command_line_resolver's tests were passed. But cli end to end tests failed because it gave recursion depth error. So, I believe it got stuck in an endless loop somewhere. Even though, I haven’t added “back” capability yet, So, I broke the system :confused: My question is do you think I should continue to change the code? Or do you think that I can do something else instead of following this plan. I think it would be better to get a second thought.


Robin:
Morning @Baris Sari, @Ian Mayo. I've had a look at Baris's code, and I can see why you're concerned: it has made things a lot more complicated. However, I was never a huge fan of the structure of the command-line resolver in the first place and always found it a bit complicated and wondered if it needed refactoring or rewriting sometime.
I wouldn't be overly concerned that the automaton tests in the end-to-end testing are failing: they are quite closely tied to the details of the implementation, so they may need rewriting if the implementation changes. I'm also intrigued as to why the error is about too much recursion when trying to get the repr of an object - that's interesting (but probably not important to understand at the moment).
I think there are two options as to the way forward now:
1. Don't implement back functionality at the moment - decide it's just too complicated and put it on the back burner for the moment
2. Spend quite a long time discussing and coming up with a new, future-proof design for a new command-line resolver, and then implement that as a complete (or almost complete) re-write. The idea would be that this has the same (or very similar) API, so the rest of the code doesn't need to change, but could be structured completely differently inside. For example (thinking off the top of my head), we could have objects for each question, and a 'stack' of objects which works as the 'back stack', so that when we go back we just pop one off the top of the stack. This would take a long time and a lot of effort, but would probably lead to a nicer and more robust command-line resolver...but it depends what the priorities are.
I think the decision comes down to @Ian Mayo in the end - to decide whether this is important enough to spend a lot of time on, and whether he wants to commit the time of both of us to design and develop a new implementation.

Ian:
Since doing this properly will require a large block of time, it would be wrong to spend budget on a feature they haven’t asked for if it impacts on something they have asked for.
We can keep the issue of “Support Back button”, and let the clients prioritise it.

**Comment by IanMayo** [comment]
Close this.  Team experts decided it introduced too much potential fragility for the UX gains offered.
