### ISSUE TITLE
Access to contextual help from Pepys-Import & Pepys-Admin

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#627]
## 🐞 Overview

The clients are developing best practices for how to word some fields, such as letter case, plus whether to use `HMS` prefix.

We _could_ include this in the UI.  Another option is to provide it a contextual help.  _Maybe_ at any question, entering `?` will open the contextual help for that field.

Please investigate if this is possible.  I propose that the each question is given an ID, and a CSV lookup table maps ID values to browser URLs.  These URLs will typically link to a page (poss with `#` anchor) in the local ReadTheDocs content.

Hmm, as an alternative.  The `CSV lookup table` could contain ID in column one, then the textual guidance in the second column.  After entering `?` or `HELP` this paragraph of text is displayed in the terminal (possibly in another color), with the prompt re-displayed.

Amongst all her other jobs, I'd appreciate @clenoble indicating her preference of content-in-browser, or content-in-terminal.

## Update
I guess we need:
* a method to insert a _New section_ divider. The method will take a `title` parameter, which gets displayed at the centre of the divider. Should look like the first one [here](https://github.com/debrief/pepys-import/issues/627#issuecomment-732243304).   Note the help reminder immediately after the divider
* a "framework" where prompts include an ID string.
* a table for HelpTexts: ID field plus guidance field. Guidance can be up to 2000 chars
* table can be populated from a `.csv` file via `Initialise data` in Pepys-Admin
* entering `HELP` or `?` at a prompt retrieves the guidance, displays it in italics, then provides original prompt.
* test-suite modified to verify that help present for every ID string (this will ensure we provide the new guidance when we add a new prompt).

## 🔗 Feature

#595 Improve user guidance

## 🔢 Acceptance criteria

During import process, entering `?` as answer for any question will either open the contextual help for that field in the browser, or display the content in the terminal.

**Comment by clenoble** [comment]
@IanMayo I definitely prefer the help to be displayed in the terminal in another color. Changing context has always a cost in terms of cognitive load, and it is much easier to copy a naming pattern if it is displayed just above in the same style. We could make screenshots available in the help pages, but there will still be changing from one window to another. 

It is also important that the help given is really specific to the question like you suggested and possibly other data. For example, the identifier convention depends on the platform type. In the current flow, the platform type is entered after the identifier. If the platform type was entered before the identifier, then we could display a much more specific naming convention associated to the relevant platform type.

**Comment by IanMayo** [comment]
Hello @BarisSari & @robintw , here we have a requirement for context-sensitive help in the import app.

This will provide further guidance if the user types ? at any question.

We need to store this guidance somewhere.  These are my first two guesses:
- A CSV file in the repo: ID in the first column, text in second.
- A table in the database (which is probably initially populated from a CSV file)

You’ll be able to guess this as easily as me - but I guess there would only be about 20? entries in the table.

Any preferences?  I guess the second means we can (eventually) let user admin edit the content within Pepys-Admin.

**Comment by BarisSari** [comment]
Hello all. I think the second option is better. We might create a table which has two columns: a unique name of a question and guidance text. 

By the way, prompt toolkit offers many styling options. We might even hold HTML, etc. if necessary. But for a start, we might just print it in a different colour. You can the possible formatting options [here](https://python-prompt-toolkit.readthedocs.io/en/master/pages/printing_text.html) and gallery [here](https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html)

**Comment by robintw** [comment]
Yeah, I agree - a table in the database sounds sensible, then we can let the users edit it if necessary. It can be populated from a CSV file in the `database` folder.

**Comment by IanMayo** [comment]
Ok. I guess we need:
* a "framework" where prompts include an ID string.
* a table for HelpTexts: ID field plus guidance field. Guidance can be up to 2000 chars
* table can be populated from a `.csv` file via `Initialise data` in Pepys-Admin
* entering `?` at a prompt retrieves the guidance, displays it in italics, then provides original prompt.
* test-suite modified to verify that help present for every ID string (this will ensure we provide the new guidance when we add a new prompt).

The above is _initially_ only for `Pepys-Import`.  The number-choice menus in `Pepys-Admin` mean a prompt could relate to, say, 6 options - so we don't know which one the help would be for.  But, there could be a place for the context-sensitive help as we grow more maintenance tasks.

I have a couple of questions for @clenoble:
1. We need to make users aware that the help is available. But, it would seem wasteful to include it at every prompt. See mockup below.
2. Do you an idea of how the context sensitive help should be displayed.  Attempt below.

```
Adding a platform
Please enter a name, or ? for help: NELSON
```

```
Please enter a name: ?
----------------------------
The name for the platform is the common name used when referring to that platform.  It should be 
in mixed case, and does not need the leading Ship Prefix (HMS, USS, etc).
Examples: Richmond, Arctic Fisher
----------------------------
Please enter a name:
```

**Comment by clenoble** [comment]
@IanMayo You should make use of styling and display the help in another color (not green, not red).
The 2nd prompt should repeat exactly the previous one, no reason to delete the suggestion.

@BarisSari @robintw @IanMayo 
One ID per question will not allow for very specific guidance (like the identifier convention specific to a platform-type). Is there no way to take into account more context information? and start the flow with the platform-type?

**Comment by BarisSari** [comment]
@clenoble we might change the flow however we like. We might put some placeholders to the guidance string and replace it with the user input value.

**Comment by IanMayo** [comment]
Thanks for that @clenoble .

All clear. One unanswered query.  How should we make user aware that ? will provide more help?  It's just that it seems a bit cluttered to have it on every prompt:

```
Ok, adding new platform.
Please enter a name, or ? for help: SPLENDID                                                                        
Please enter identifier (pennant or tail number), or ? for help: wer                                                
Please enter trigraph (optional), or ? for help: SPL                                                                
Please enter quadgraph (optional), or ? for help: SPLE     
```


I think that for now I'd like to defer the "platform-type-sensitive context help".  Pepys doesn't currently know about any individual values for platform-type, it just knows they exist.  The set of values in use by the clients are currently still evolving.  I'll create an issue for it.

**Comment by clenoble** [comment]
sorry I forgot the first part of your question. The standard way of summoning help in command line is to write "help" at any point. I think we could keep this to be consistent with other languages. Maybe we could remind users of this possibility in the first screen, and in each new screen or section*.

```
Ok, adding new platform.
**Type HELP at any time to display contextual help** (cyan for example)
Please enter a name: SPLENDID                                                                        
Please enter identifier (pennant or tail number): wer                                                
Please enter trigraph (optional): SPL                                                                
Please enter quadgraph (optional): SPLE 
```

* I thought about introducing a new screen for each major step (new file, new platform, new sensor). that would have the merit to unclutter the UI a bit. One thing that makes terminal UI scary for users is the length of text. They are not used to parse it quickly and ignore most of it.

**Comment by IanMayo** [comment]
> new screen for each major step

Sure. Yes - a "new section" marker would break what they see on the command line down into smaller chunks.

I guess something like this would break up the screen:
```
#################################
#                               #
#       Select Platform         #
#                               #
#################################
Type HELP at any time to display contextual help.
Do you wish to:
1) Search for existing platform
2) Add a new platform
.) Cancel import
```

Or we could fill the area with more dense shading that takes up less space, but has greater contrast:
```
#################################
########  Select Platform #######
#################################
```

**Comment by robintw** [comment]
We should be able to use a terminal command that clears the screen before printing the new section header - I know there is a terminal escape command that does that, and I assume our prompt toolkit would support it - I'll look into it.

> One ID per question will not allow for very specific guidance (like the identifier convention specific to a platform-type). Is there no way to take into account more context information? and start the flow with the platform-type?
I think what @BarisSari was suggesting was having text in the help string that was replaced depending on the context (eg. a `REPLACEHERE` which is replaced with a relevant name, or something) - but @clenoble, were you actually suggesting a deeper configurability? For example, if you had different rules for platform names depending on the platform type, we could give significantly different help text for platform name depending if they had already chosen a platform type of 'Submarine' or 'Fishing boat' or whatever. Is that what you were getting at?

If so, that may require re-ordering things as we ask for name before type at the moment.

**Comment by IanMayo** [comment]
Yes @robintw - we could provide context-sensitive help that relates to particular platform types.  I have a suspicion that we may skip some questions, since for example I _don't think_ aircraft have Trigraph or Quadgraphs.

I've provided a bit more detail on that in #636

**Comment by clenoble** [comment]
@IanMayo For the header display, I prefer the 1st one. I don't think space is an issue really, and empty space provides a greater contrast with the rest of the terminal filled with characters.

**Comment by IanMayo** [comment]
@BarisSari - I've tried to add a summary of what steps are needed up in the Issue description. Hopefully that is firm enough for work to start on it, but I'm quite happy to answer any other questions.

**Comment by BarisSari** [comment]
Thanks, @IanMayo. I think it is clear for now but I'm sure I'll have questions during the development.

**Comment by IanMayo** [comment]
@BarisSari - I've changed the [mockup](https://github.com/debrief/pepys-import/issues/627#issuecomment-732243304) to indicate we allow `?` or `HELP`.
