### ISSUE TITLE
Mac-specific issue

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#63]
This is bound to be an issue with my config, rather than pepys-import, but I'm unable to review code until I fix it :-(

(well, I'm trying to get a MS-Windows VM working, so I can test/review in there).

```
> python3  -m unittest tests/test_parse_etrac.py 
started
Software Version :  0.0.4 
Database Type :  sqlite
Database Name :  :memory:
Database Host :  
---------------------------------
before connect
Segmentation fault: 11
```

The `before connect` debug-line comes from here:
![image](https://user-images.githubusercontent.com/1108513/74638998-ef348f00-5164-11ea-98b6-fec4233e5a53.png)

So, I'm pretty sure it's coming from `self.engine.connect()`.

**Comment by BarisSari** [comment]
@IanMayo , do you still have this issue?

**Comment by IanMayo** [comment]
The problem has gone away :-)

Happy to drop the issue, and re-consider _if_ it comes back.
