### ISSUE TITLE
Initial data in training database

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#630]
## 🐞 Overview

For running Pepys in training mode, it would be more realistic if there was some data in it already.

This task is initially to identify the specific data that should be present: which rows, in which tables.

Once that is done, it will switch to inserting/creating that data.

## 🔗 Feature

#595 

## 🔢 Acceptance criteria

- [ ] Training database created with sensible initial training data.

Note: here is the current reference data: https://docs.google.com/spreadsheets/d/1OlSXwRImHYOU6y62AL6KYQCbTY7ZIcxon17_SoAByGk/edit#gid=0
We should use a simplified version of that

**Comment by clenoble** [comment]
@IanMayo 
Regarding the type of data needed: 
- the basic of reference tables, especially the platform-type used for the exercise (Frigate)

We could split the 1st exercise in two, start with an existing platform (and explore the search feature), then creating a new platform. In this case, we need at least one platform, and the sensor for this platform (GPS).

I think it's a good idea to show that import is going to be really quick once most platforms and sensors are created.
