### ISSUE TITLE
Add "role" to "Participations"

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#631]
## 🐞 Overview

We have a new concept to store/manage within Pepys.

For an exercise, and aircraft may have a `call-sign`.  An example of this is a group of 3 aircraft, and they call themselves "Delta-1", "Delta-2" and "Delta-3".  When they are reporting what's happening, they are doing it by call-sign.

But, for the next exercise (two hours later), they call themselves "Delta-3", "Delta-4" and "Delta-5".

When the records come in at the end of the day, it's one memory-stick per aircraft, by airframe number (`C2344`, `D3553`, `D6665`).

So, we need to store the call-sign, but it can't be used as "identifier" for the platform - since they can get re-used or swapped around.

One solution to this is to store the call-sign in the participations table. Each row in this table is for one platform taking part in one task.  This would handle the above. 

At some point an analyst has to create the participation(s), and to add the call-sign to the relevant participation row, probably via `Pepys-Admin`.

## 🔗 Feature

#600 Database Maintenance.

**Comment by IanMayo** [comment]
I welcome your thoughts on the above, @BarisSari  & @robintw

**Comment by BarisSari** [comment]
Hello, @IanMayo. Storing them in the `Participants` table sounds sensible. I just checked the table and this is the structure:
<img width="186" alt="image" src="https://user-images.githubusercontent.com/41292272/99936904-5a0a9a80-2d75-11eb-9e6f-a5375f6f29fe.png">

`task_id` can't be null. So, an analyst should create a task first, then create rows with the call-sign to the Participants table.

I might add `role` field and necessary methods `DataStore.add_to_participants()`, etc. But I'm not sure about the flow for adding it from the Pepys-Admin. Should we ask questions for each field like `Command Line Resolver`?

**Comment by IanMayo** [comment]
Ok. We have a rough way ahead for this.

We'll defer it until we have a UX flow for maintaining participations - which will probably form part of the larger `Database maintenance` feature.

**Comment by IanMayo** [comment]
This part of the schema has been re-organised, and this feature is no longer necessary.
