### ISSUE TITLE
README Instructions 

### ISSUE THREAD

**Issue by BarisSari** [debrief/pepys-import#64]
Readme instructions are not clear for now. Therefore, the project should be set up in a new environment and each step should be written.

**Comment by IanMayo** [comment]
Yes, if we start with a Ubuntu version, we can then write MS-Windows/MacOS versions too, if necesssary.

**Comment by robintw** [comment]
I think we definitely need a Windows version of this too - but this comes as part of the work I'm doing on deployment on Windows (as to deploy to Windows I need to get it running on Windows in the first place!).

If it's ok, I'll finish some of my work on Windows today and tomorrow, and then put together a part of the README for how to set it up for development on Windows.

**Comment by IanMayo** [comment]
Yes, @robintw - I fully agree.
