### ISSUE TITLE
Defaults resolver should include answer for "Skip enhanced validator"

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#640]
I'm doing a bulk data import of dummy data.  Some of it is failing validation, but I don't mind that 😱 

I'm using the defaults resolver - but where it fails enhanced validation the import pauses for an answer.
![image](https://user-images.githubusercontent.com/1108513/100272895-cb07a900-2f53-11eb-8e94-49e447231b00.png)

## Part one

Introduce new `--skip-validation` command line parameter.  This will skip the validation steps, and would be used when loading dummy/test data. 

I _don't think_ we should use it in our test-suite other than specific tests for that feature.  Keeping validation in our existing tests will help to catch regression problems.

The command-line documentation and user documentation should be updated to describe the new feature.

I've attached a sample folder of files:
[SampleFiles.zip](https://github.com/debrief/pepys-import/files/5598845/SampleFiles.zip)

## Part two

My pain would have been eased if there was an option to "Skip enhanced validation for remaining files".  We should add it.

**Comment by robintw** [comment]
For Part 1, do we want this to be a default part of the DefaultResolver, or do we want to specify a separate option - something like `--validation skip` to deal with validation, so we can keep it separate? I think it might be useful for it to be separate.

**Comment by IanMayo** [comment]
Sure, good idea @robintw . Will update description.

**Comment by BarisSari** [comment]
@IanMayo, Should we skip the validation steps even user only passes `--resolver default` parameter?

**Comment by IanMayo** [comment]
Hmm, I think @Robin suggested making it a command line parameter.

I think that _logically_ we should only skip validation if the parameter was there.  This is _just in case_ a user wants to use defaults, but with validation.
