### ISSUE TITLE
Remove datafile name question in Pepys Import

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#641]
## 🐞 Overview
We've decided the user is never going to want to change the datafile name - so there's no point asking them to confirm it. We can just remove the question, and there is one less thing for them to have to do!

## 🔢 Acceptance criteria
Pepys Import no longer asks about the datafile name.

**Comment by IanMayo** [comment]
Let's hold back from implementing this for a day or so, please @robintw 

I'm just double-checking with the users.

**Comment by IanMayo** [comment]
Ok, @robintw  - they've agreed it's ok to remove the filename question.

Note: there was some too & fro about them wanting to use the step to rename the data-file with date, platform, exercise.  This is so they have a "master copy" of the original data that is easy to fine.  But I warned them about the fragility of human typed content. I also talked through how the Pepys archive process means that the datafile is kept securely, and that they can use Pepys to navigate/find datafiles using any metadata.

**Comment by robintw** [comment]
Ok, I'll start on that soon.

In terms of them trying to find datafiles, there is the potential for more features to help the user. We could rename files automatically in the archive based on things like date, platform, exercise - or we could add features to Pepys Admin/Pepys Viewer to help them find a datafile that contains specific data. Just something to keep in mind for future features.

**Comment by IanMayo** [comment]
> rename automatically

Yes, but that would only really be allow search using free-text filename search Windows Explorer.  By looking for datafiles from `Pepys-Admin` we can let them use our fuzzy search across the full set of Pepys metadata (in the future...).

**Comment by IanMayo** [comment]
Fixed in #644
