### ISSUE TITLE
Capture requirement for sample data

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#657]
## Capture the issues we want to demonstrate with sample data
1. Loading data from file
2. Loading a folder of data
3. Experiencing, then correcting a file error (invalid hemisphere letter?)
4. Data in non-position format (contact/comment)
5. Viewing highlighted import report

## Produce sample data
```
  - sample1.txt
  + sample_folder
     -  sample2.dsf
     -  sample3.rep
  - sample4.gpx
```

## Import sequence:
1. import `sample1.txt`
2. import `sample_folder`.  `Sample3.rep` fails validation, but still import metadata (platform & sensor)
3. fix `sample3.rep` (swap `0.0002` for `2.0` in second line)
4. re-import `sample_folder`
5. Import `sample4.gpx`

**Comment by clenoble** [comment]
1st exercise: load a GPS track for a new platform (but existing platform-type, Frigate suggested)

2nd exercise: load a folder with multiples files (.rep and other format to reflect the type of data analysts will likely use)
Most files should be processed with minimal inputs (if platforms and sensors already exist in database, only provide file classification for each?)
1 file should trigger a type of error analysts are likely to encounter and is easy to correct.

3rd exercise: load a file with 2 - 3 platforms and sensor types.
Format not yet used in the previous training files. 
Include example of contact data?

**Comment by IanMayo** [comment]
Exercise 1:  Intro to loading data.  GPX format.  No (platform/sensor) metadata in Pepys
Exercise 2: Multiple files and fixing data. .REP plus one other format).  Platform/Sensor data should be in database
Exercise 3: File with multiple tracks & sensor types.  Platforms present in system. but as another name.

**Comment by IanMayo** [comment]
Structure doesn't match tutorial narrative.
