### ISSUE TITLE
Triplication of results when searching for a platform

### ISSUE THREAD

**Issue by clenoble** [debrief/pepys-import#658]
## 🐞 Description
Search suggestions include 3 times a given platform using different IDs.

## ⚙️ Current behavior
When searching for a platform name, a given platform is listed 3 times in the suggestions, once with the name, once with the trigraph, once with the quadgraph. 

## ⚙️ Expected behavior
A given platform should appear only once in the list of suggestions, in a way that includes the name, trigraph, quadgraph and synonyms if they exist.

## 🔢 Steps to Reproduce
In training mode, create a first platform.
For the 2nd platform, search using the 1st letter of the 1st platform created.
The 1st platform appears 3 times in the suggestion

## 🖥️ Screenshots
![Screenshot_2020-12-02 Demo Training Mode - Jupyter Notebook](https://user-images.githubusercontent.com/22282418/100892745-f2fa8d80-34ba-11eb-8d62-4587e7602c24.png)

**Comment by BarisSari** [comment]
I think removing these 3 suggestions and having only one of them is the easy part of this task. It doesn't need much change. 

We created suggestions according to our current uniqueness for Platform. But we might have this format:
`Platform name / trigraph / quadgraph / synonyms as list / identifier / nationality`
It will cause some long suggestion lines. If we remove identifier and nationality, then there might be different platforms with the same name/trigraph/quadgraph/synonym. So, the user can't select the correct one. I think before anything, we should decide the uniqueness criteria.

**Comment by IanMayo** [comment]
Thanks for that @BarisSari 

I was going to suggest "drop the nationality" - but if the analyst wants to find a platform from a nation they don't encounter very often, they could just type `Sweden` (for example) and quickly find the platform they're looking for.

Hmm.  After thinking about it, I think we should let the line get really wide. Once we exceed 80 chars we could start to omit the last few chars off the longest values, to keep them under 80 chars.  It's normally the start of words that users would try to match.

**Comment by BarisSari** [comment]
@IanMayo, I looked for a smart search, where you type something which is not shown in the completer and match with the relevant information (like dropping Nationality and then searching platforms by typing a nationality), but I couldn't find much information. But I can make a thorough search if you think we need it.

> Hmm. After thinking about it, I think we should let the line get really wide. Once we exceed 80 chars we could start to omit the last few chars off the longest values, to keep them under 80 chars. It's normally the start of words that users would try to match.

Okay, I will omit characters and the lines will be at most 80 chars.

**Comment by IanMayo** [comment]
> But I can make a thorough search if you think we need it.

@BarisSari - no, let's stick with the current search, until we identify an issue with.
