### ISSUE TITLE
Enhanced validation doesn't fail when speed too fast

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#659]
I'm playing around with sample data.  I want a data-file to change.

I've modified this file to have a speed that is too much for the time step (200, rather than 2):
![image](https://user-images.githubusercontent.com/1108513/100891993-c3935300-34b1-11eb-89d3-6567077ae5d7.png)

I'm _mocking_ the fact that a zero went in, instead of a decimal point in the highlighted line.

But, it passes enhanced validation.  It fails validation if I use a value of 0.0002

So, it looks like we're testing speeds that are too small, but not speeds that are too large.

Note: the above test file is in branch `feature/657_tutorial_data`

**Comment by IanMayo** [comment]
@robintw if you're available, it would be useful to have a fix for this in the next few days, since we're using the sample data for the workshop.

**Comment by robintw** [comment]
What thresholds would you like to use for accepting a speed value @IanMayo?

At the moment, we compare the speed in the file (`speed`) and the speed calculated from the location data (`calculated_speed`) and accept it if:
 - `speed` is None, OR
 - `calculated_speed <= speed * 10`
 - `calculated_speed <= 1 m/s`

The second condition will catch situations where the speed value in the file is too small.

Do we want to extend the second condition to check that the calculated speed is between two values (calculated based on the `speed` variable)? We could do something like `speed / 10 >= calculated_speed <= speed * 10` - but we're just picking thresholds at (semi) random here.

Thoughts?

**Comment by IanMayo** [comment]
> thresholds at random

Yes. But a factor of 10 doesn't seem unreasonable.

Yes, I think we should extend the second case in the way you describe.  Well, or introduce another case that check the speed isn't a lot less than the recorded one.
