### ISSUE TITLE
Stuck in loop adding sensor

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#661]
I'm adding a sensor, but I can't assign it to an existing sensor.

I'm using test data in branch `feature/657_tutorial_data`

Steps to reproduce:
1. Import `sample1.txt` - answer questions as necessary. Note: this import creates a PER sensor.
2. import `sample_folder\sample2.dsf` - for `Periscope` sensor, use existing `PER` sensor.

But, when I click on `5`, the menu cycles around. I was expecting `PERI` to become a synonym for `Periscope`

![Screencast](https://i.gyazo.com/fb4bb4eb2bb54e50dc4f8c0ef0d2487e.gif)

**Comment by BarisSari** [comment]
I'm debugging it now, @IanMayo. It's quite unexpected :/
