### ISSUE TITLE
Progress counter through series of files.

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#669]
I'm loading a folder of data-files, using the default resolver.

It would be useful to see how far through the process we are.  Here is a full processing of a datafile (with defaults resolver):
![image](https://user-images.githubusercontent.com/1108513/101063695-ffe6b200-358a-11eb-9558-71afc3aa8c65.png)

When we're running cli resolver, there will be the step when a user processes the next data-file.  So in interactive mode, _maybe_ we should highlight the title block when we start a new data-file.

Aahh, hold on. I should re-consider this once we've got the context sensitive help in - since that's where these title blocks get introduced.

**Comment by robintw** [comment]
Adding a new header for each file that we process is fairly easy. How does the following look:

```
==METADATA REPORT==
+--------------+---------+
| Table name   | Names   |
+==============+=========+
| Platforms    | NELSON  |
+--------------+---------+

==MEASUREMENT REPORT==
+--------------+------------------+----------------------------+
| Table name   |   Number of rows | Last item added            |
+==============+==================+============================+
| States       |                5 | 2021-09-13 08:57:35.539705 |
+--------------+------------------+----------------------------+



Would you like to
   1) Import metadata
   2) Import metadata and measurements
   3) Don't import data from this file.
3
✔ Measurements cleared
✔ Metadata cleared

############################################################
#       Importing new file: gpx_1_0_InvalidSpeed.gpx       #
############################################################
Type HELP or ? at any time to display contextual help.

############################################################
#                     Resolve Datafile                     #
############################################################
Type HELP or ? at any time to display contextual help.
Ok, adding new datafile gpx_1_0_InvalidSpeed.gpx.


Ok, please provide classification for new Datafile named 'gpx_1_0_InvalidSpeed.gpx': 
   1) Search an existing classification
   2) Select: Public
   3) Select: Public Sensitive
   4) Select: Private
   5) Select: Private UK/IE
   6) Select: Very Private UK/IE
   7) Select: Private UK/IE/FR
   8) Select: Very Private UK/IE/FR
   9) Select: Very Private
   .) Cancel import (Please contact an expert user if you need a new classification to be added)
 > 
```

**Comment by robintw** [comment]
Right, we now have a counter working - see screenshot below:

![image](https://user-images.githubusercontent.com/296686/133058581-1e411527-942c-495a-bb4b-482ce62f4002.png)

I should note that the counter counts _all_ files in the folder - even if a load of them won't be picked up by any of the importers. We can't know at the beginning how many files will be picked up by importers, as we do all the complicated checks (filename, first line, contents etc) on a file-by-file basis. Therefore, it could say "Importing file 1 of 500" but only 3 files will actually be imported, as the rest of the files in the list are ones that Pepys doesn't recognise. However, even if this situation, it gives a rough idea of how far along the process you are.
