### ISSUE TITLE
Spatialite DLL not registered for MS-Windows

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#68]
When we run spatialite tests on MS-Windows, they fail with this error
```
  File "C:\git\pepys-import\pepys_import\utils\geoalchemy_utils.py", line 15, in load_spatialite
    connection.load_extension(EXTENSION_PATH)
TypeError: argument 1 must be str, not None
```

I now recognise that the error is because the `EXTENSION_PATH` isn't being provided, we only do it for Linux & Macos.

**Comment by robintw** [comment]
Fixed in #67
