### ISSUE TITLE
Methods to prepare/populate database

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#7]
This task is to introduce methods to prepare the datastore:
https://docs.google.com/drawings/d/1CXE6pW6lvAKcCP8O1spRNSYBwl6ajJ3HX9dCSRm7nK0/edit

* initialise() . `already present`
* populateReference()
* populateMetadata()
* populateMeasurements()

The repo currently contains Python scripts to populate the data-store.  The commands will be moved to an `initialise` method.

The other commands will insert data into the reference and/or metadata/measurements tables.

If `.csv` files are created with a few dummy lines, I will step in and provide more data to them.  The `.csv` files are to be structured with the field name in the header row, suitable for reading with the Python `csv` library.

Initially, measurements are only required for the `State` and `Contacts` tables.

**Comment by BarisSari** [comment]
I think we can close the issue now. What do you think @IanMayo ?
