### ISSUE TITLE
Use RED for error messages

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#706]
We should show error messages in red text.

If we don't get enough contrast for red shade in MS-Windows, we could experiment with just putting `ERROR` in red, or even just `!!` at the start of the line.

**Comment by BarisSari** [comment]
one question, @IanMayo. What is the scope of this task? Should I change all errors for Pepys Import & Pepys Admin & Pepys Viewer?

**Comment by IanMayo** [comment]
I did only think about errors appearing in Pepys Import.

Do we show any errors in admin/viewer (I can only think of the stack-trace on a crash).

**Comment by BarisSari** [comment]
We print some errors like that:

- Unknown syntax
- Schema errors in `cli.py` files.
- Invalid option, file already exists kind of errors for export cli and snapshot cli
- Database version errors
etc.

**Comment by IanMayo** [comment]
Aah, sure.  Yes - lets use Red in all apps, please.

**Comment by BarisSari** [comment]
Okay, I'm working on it 👍
