### ISSUE TITLE
Research existing examples of interfaces to design queries

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#722]
## 🐞 Overview

This issue is a placeholder to collect (and discuss) existing examples of user interfaces used to create custom queries, potentially including these capabilities:
- selection of where to look for data
- specification of filter criteria
- what is to be output
- how output is to be sorted
- any operations to apply to the results

## 🔗 Feature

#600 - maintenance capabilities

**Comment by IanMayo** [comment]
Let me start us off:
Access expression builder:
![image](https://user-images.githubusercontent.com/1108513/102490257-78a73d00-4066-11eb-8eed-83ead110acdc.png)

and the Access Query Designer:
![image](https://user-images.githubusercontent.com/1108513/102490331-9674a200-4066-11eb-97a1-6ac69a50a6a9.png)

a web-based query builder:
![image](https://user-images.githubusercontent.com/1108513/102490423-b86e2480-4066-11eb-95cb-fe9242589521.png)

And here is a walk-through session of a graphical editor:
https://www.tutorialgateway.org/sql-query-builder/

**Comment by IanMayo** [comment]
@robintw - here is a Python library for a Qt-based GUI query builder: https://github.com/JarkoDubbeldam/SQL-builder

**Comment by clenoble** [comment]
@IanMayo  @robintw All these examples are in GUI and even so appear to me far too complex for our users, except possibly for the web-based one. Plus, there are far fewer tables than in our case. In the Access Query Designer screenshot, there are only 5 tables. 

Maybe we could use something similar to dropdown in command line? Currently when searching, a list of suggestions appears that we can navigate using arrows and select an option. 

If it's possible, I was thinking of having a general query template like this: 

<action> <search criteria(s)> in <data sources: table(s)> 

<action> means any kind of operations, including export and format

<search criteria(s)> include full-text search, metadata filter, sort criteria

<data sources: table(s)> list of tables where to search

Then a wizard-like conversation where the user can build each part independently.

**Comment by IanMayo** [comment]
Yes, that sounds reasonable.  While walking just I did start to develop a pattern for what's happening in the maintenance tasks.
The user is selecting a type of data they're interested in (a table), then they're developing a set of criteria to find the rows of interest, then they're choosing an action - where the action _may_ be sensitive to the data in question. i.e. if the table is of measurements they may wish to export the data, view a graph of availability, or (one-day) smooth the data. If the table is of metadata or reference data they may wish to merge the items.
So, maybe an `Output` pane could have tabs for:
*  `Count` - just dumb count of matching records. Runs very quickly
* `View` - tabular view of first xxx matches
* `Export` - export to CSV, or REP/GPX is relevant
* `Actions` - list of actions to apply to the matching data. 
* `Plot` - view a graph of the data. ASCII art in the panel, but with export to image.
* `Save` - provide Custom Query name and brief description.

**Comment by robintw** [comment]
I've done some research today into other query interfaces. It's actually remarkably difficult to find query interfaces that are along the lines of what we want - so we may have to come up with a lot of the design ourselves. However, there are a few interesting resources:

[Mitzasql](https://vladbalmos.github.io/mitzasql/screenshots/) - a console app for querying databases. The actual query interface is mostly just typing in SQL, but there are some nice interface touches in the rest of the app (also, the video of the interface doesn't seem to work for me, but the screenshots show most of the app).

This [blog post](https://medium.com/active-query-builder/make-a-better-visual-query-building-ui-83729fb471bb) describes some of the plans for a query interface that is implemented in a [library](https://www.activequerybuilder.com/) for various platforms/languages (not Python though). I like their idea of right-clicking (could be altered for a text interface) an item in a structured view of a database to add a WHERE clause based on it. In another blog post on their site they mention allowing users to right-click on a value in a view of results from a query to create a WHERE clause based on that value - eg. right-click on a platform name to then choose to restrict to just that vessel. They also mention various things about GROUP BYs and so on - we probably don't need those for queries where users are selecting data to merge, but we may need them for writing generic queries to save for re-use later. Some of these UI approaches may be rather complicated to implement in a text-based interface using things like prompt_toolkit.

**Comment by IanMayo** [comment]
Aah, @robintw  - we do have one luxury in comparison with those apps/articles.  I _think_ they aim to support universal set of SQL interactions.  We have a (relatively) fixed set of tables, with some fairly predictable sets of interactions.

That is to our benefit - since we can "lead" the user along pathways that may hinder a "universal" SQL query generator.

**Comment by IanMayo** [comment]
Closing this. We now have our Figma UI

**Comment by IanMayo** [comment]
This doesn't relate to us, but I saw this interesting fresh perspective on designing SQL queries.
https://www.dbinf.informatik.uni-wuerzburg.de/google-blockly-4efa0da/sql/index.html

At the end of the day the use is still producing pure SQL, but via building blocks. As I said, interesting.

![image](https://user-images.githubusercontent.com/1108513/105492562-056d9800-5cb0-11eb-9928-43aa348c8810.png)
