### ISSUE TITLE
Denormalised Platforms Table

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#742]
## 🐞 Overview
View of Platform data with foreign key labels/names included.

![image](https://user-images.githubusercontent.com/1108513/105736880-33abdb80-5f2d-11eb-889b-32ce0f7f2fec.png)

## 🔗 Feature

#600 - Database Maintenance

## 🔢 Acceptance criteria

Produce a query that includes all of the fields in the above diagram

Provide a link to an SQL-Fiddle that demonstrates the above.

**Comment by arunlal-v** [comment]
This should do. The link has app specific and SQLFiddle specific queries.

http://sqlfiddle.com/#!17/3ae4f/35

**Comment by IanMayo** [comment]
Completed.
