### ISSUE TITLE
Low contrast in Pepys-Admin error reporting

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#748]
## 🐞 Description

Windows command-prompt error messages aren't legible to me. the shade of red is too dark (first screenshot)

I do note that we have access to a higher contrast red-shade that we use in Pepys-Maintenance (second screenshot).

Could we make the error reporting use the lighter shade?

## 🖥️ Screenshots

![image](https://user-images.githubusercontent.com/1108513/106605952-6b340c80-6559-11eb-8909-7dc61e6e185e.png)

![image](https://user-images.githubusercontent.com/1108513/106606033-8acb3500-6559-11eb-93d7-0db93d7173ad.png)

**Comment by IanMayo** [comment]
@clenoble  - are you ok with this colour change?

I'm using a MS-Windows virtual machine, rather than a real PC, but I _expect_ the issue is still valid on a real PC.

**Comment by clenoble** [comment]
@IanMayo Yes, no issue with using the lighter red, on the contrary.

**Comment by robintw** [comment]
Fixed in da6a222 (sorry @BarisSari - I thought it'd be easier for me to fix as I know exactly how we're specifying the colour in the GUI).

![image](https://user-images.githubusercontent.com/296686/106620836-df76ac00-6569-11eb-9604-9caf0959c7e3.png)

**Comment by BarisSari** [comment]
That's fine, Robin 👍
