### ISSUE TITLE
"Select all" ability in preview table for Pepys Maintenance

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#750]
I'm able to put the cursor into the header row of the table preview.

![image](https://user-images.githubusercontent.com/1108513/106613560-3d9f9100-6562-11eb-909c-773cd0432b6f.png)

It would be great if there was a checkbox in this cell that could be used to `Select all` or `Select none`.

Hmm, from memory of checkboxes like this in the past, I think it _normally_ takes a greyed-out _in-between_ shade if _some_ rows are selected.  
* Enter cell (empty), click to select
* All rows selected, header cell filled
* Click on header cell again, click to clear
* No rows selected, header cell clear
* Click on a row, header goes grey

Does this set of interactions look right to you @clenoble ?

**Comment by clenoble** [comment]
All good!

**Comment by robintw** [comment]
Fixed in 9a17e74d.

It looks like this:

![MaintenanceGUI_2021-02-02](https://user-images.githubusercontent.com/296686/106652928-0fd04180-658e-11eb-8a4f-fb086a6a7591.gif)

I used a `:` (colon) character as the half-way character between a space for not selected and a `x` for selected.
