### ISSUE TITLE
Purpose of few nondescript columns

### ISSUE THREAD

**Issue by arunlal-v** [debrief/pepys-import#752]
What do the following columns capture in **pepys** database?

Table Name|Column Name
-|-
Contacts|mla
Contacts|soa
Extractions|chars

**Comment by IanMayo** [comment]
mla - Mean Line of Advance
soa - Speed of Advance
chars - characters

**Comment by arunlal-v** [comment]
Thanks Ian. I'll update it in the Postgres recommendation issue.
