### ISSUE TITLE
Stored Procedure for large queries

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#753]
@arunlal-v has produced queries for getting a list of matching datafiles, plus queries for getting matching states, contacts and comments (attached).

This task is to cover moving one or more of them to PostGres stored procedures.
[Measurements-v0.6.txt](https://github.com/debrief/pepys-import/files/5927206/Measurements-v0.6.txt)
[Comments_DemoScript_v0.5.txt](https://github.com/debrief/pepys-import/files/5927216/Comments_DemoScript_v0.5.txt)
[Contacts_DemoScript_v0.5.txt](https://github.com/debrief/pepys-import/files/5927217/Contacts_DemoScript_v0.5.txt)
[States_DemoScript_v0.5.txt](https://github.com/debrief/pepys-import/files/5927218/States_DemoScript_v0.5.txt)

## Pros of Stored Procedures
* database doesn't have to "plan" how to resolve query for stored procedures. Could save up to two seconds
* reduced volume of data travelling from client to database (though poss insignificant in comparison to data travelling from server in results)

## Cons of Stored Procedures
* not available for SQLite
* not in sync with rest of schema that is maintained with SQLAlchemy. This means the StoredProcedure may _break_ if there is a SQLAlchemy schema change.  Note: we can protect ourselves from this by including call to Stored Procedure (s) in Pepys automated testing.

**Comment by arunlal-v** [comment]
First draft of the procedures to extract Datafile records and subsequent Comments, Contacts, and States.

[States_for-v0.1.txt](https://github.com/debrief/pepys-import/files/5945301/States_for-v0.1.txt)
[Contacts_for-v0.1.txt](https://github.com/debrief/pepys-import/files/5945302/Contacts_for-v0.1.txt)
[Comments_for-v0.1.txt](https://github.com/debrief/pepys-import/files/5945303/Comments_for-v0.1.txt)
[Datafiles_for-v0.1.txt](https://github.com/debrief/pepys-import/files/5945304/Datafiles_for-v0.1.txt)

**Comment by arunlal-v** [comment]
Updated versions of the functions are as below.

[States_for-v0.5.txt](https://github.com/debrief/pepys-import/files/5945679/States_for-v0.5.txt)
[Datafiles_for-v0.5.txt](https://github.com/debrief/pepys-import/files/5945680/Datafiles_for-v0.5.txt)
[Contacts_for-v0.5.txt](https://github.com/debrief/pepys-import/files/5945681/Contacts_for-v0.5.txt)
[Comments_for-v0.5.txt](https://github.com/debrief/pepys-import/files/5945683/Comments_for-v0.5.txt)


Following are the list of changes to be performed at client end.

1) Create the functions by executing the attached files.
2) Make sure the tracstor_view user has the privilege to execute these functions (Handled from Alembic/SQLAlchemy)
3) Make the corresponding java/jar updates

**Comment by arunlal-v** [comment]
Here are the latest versions of the functions to be used to fetch Datafiles and measurements data.


[States_for-v0.12.txt](https://github.com/debrief/pepys-import/files/5958686/States_for-v0.12.txt)
[Datafiles_for-v0.12.txt](https://github.com/debrief/pepys-import/files/5958687/Datafiles_for-v0.12.txt)
[Contacts_for-v0.12.txt](https://github.com/debrief/pepys-import/files/5958688/Contacts_for-v0.12.txt)
[Comments_for-v0.12.txt](https://github.com/debrief/pepys-import/files/5958689/Comments_for-v0.12.txt)

**Comment by arunlal-v** [comment]
Sample queries:

1) Searching for datafiles with only comments criteria

select * from pepys.datafiles_for(null,null,null,'COMMENTS','fishing');

Description of function arguments: 

Argument Position|Argument Parameter|Argument value|Defaulted value in function (in case of blank or null)
-|-|-|-
1|Start time|null|1000-01-01 00:00:00.000000
2|End time|null|9999-12-12 23:59:59.000000
3|Location|null|N.A.
4|Datafile type|'COMMENTS'|N.A.
5|Comment Text to be searched|'fishing'|N.A.


![Query1](https://user-images.githubusercontent.com/77854924/107524050-5e5b8c80-6bdb-11eb-983c-2160f1c88c8d.png)

**Comment by arunlal-v** [comment]
3. A *location-* and *time-bound* search of all **STATES** and *time-bound* search of all **COMMENTS** for the given search term.

select * from pepys.datafiles_for('2012-12-12 23:59:59.000000','2020-12-12 23:59:59.000000','SRID=4326;POLYGON((-125.0 65.0,-125.0 -45.0,80.0 -45.0,80.0 65.0,-125.0 65.0))','COMMENTS,STATES','fishing');

Description of function arguments: 

Argument Position|Argument Parameter|Argument value|Defaulted value in function (in case of blank or null)
-|-|-|-
1|Start time|'2012-12-12 23:59:59.000000'|N.A.
2|End time|'2020-12-12 23:59:59.000000'|N.A.
3|Location|'SRID=4326;POLYGON((-125.0 65.0,-125.0 -45.0,80.0 -45.0,80.0 65.0,-125.0 65.0))'|N.A.
4|Datafile type|'COMMENTS,STATES'|N.A.
5|Comment Text to be searched|'fishing'|N.A.

Here,

Location is any string that can be passed to the below Postgis function to return a Geometry object.
[geometry ST_GeomFromText(text WKT);](https://postgis.net/docs/ST_GeomFromText.html)
In the example shared above, the text indicates a Spatial Reference System Id 4326 quadrilateral.

Notes on Datafile type input
* Only non-null and non-zero length values are expected and they must be of **text** data type
* All values adhering to the above are expected to be made up from one or more of the following string literals
  separated by single comma (,) without any spaces, in any order and case: STATES, CONTACTS, COMMENTS
* Some examples of valid entries:
        * 'CONTACTS' or 'Contacts'  ==> Select only Contact measurements
        * 'CONTACTS,STATES' or 'STATES,COMMENTS'  ==> Select State and Contact measurements
        * 'STATES,COMMENTS,CONTACTS' ==> Select all 3 measurements
* Some examples of invalid entries:
        * 'Contacts/States' ==> / used as delimiter instead of comma
        * 'Contact' ==> Undefined string literal for "Data Type" filter

![Query3](https://user-images.githubusercontent.com/77854924/107530450-e04eb400-6be1-11eb-9bdb-3a992c731ca1.png)

**Comment by arunlal-v** [comment]
The queries shared above are for datafiles only. Once the datafiles are identified, the specific measurements (States/Contacts/Comments) have to be queried for. Following samples describe these queries.

Sample 4. Queries for specific States
```SQL
select * from pepys.states_for('2012-12-12 23:59:59.000000','2020-12-12 23:59:59.000000','SRID=4326;POLYGON((-125.0 65.0,-125.0 -45.0,80.0 -45.0,80.0 65.0,-125.0 65.0))','d75c1766-3cda-4c47-a5b0-1882a863a368','7d199bac-ef5a-4732-8c5a-dcc0fd195617','21fcfe84-a770-4921-8c4b-4520eebe61ff',1,100);
```
Description of function arguments: 

Argument Position|Argument Parameter|Argument value|Defaulted value in function (in case of blank or null)
-|-|-|-
1|Start time|'2012-12-12 23:59:59.000000'|N.A.
2|End time|'2020-12-12 23:59:59.000000'|N.A.
3|Location|'SRID=4326;POLYGON((-125.0 65.0,-125.0 -45.0,80.0 -45.0,80.0 65.0,-125.0 65.0))'|N.A.
4|Sensor Id|'d75c1766-3cda-4c47-a5b0-1882a863a368'|N.A.
5|Source Id|'7d199bac-ef5a-4732-8c5a-dcc0fd195617'|N.A.
6|Platform Id|'21fcfe84-a770-4921-8c4b-4520eebe61ff'|N.A.
7|Page No.|1|1
8|Page Size|100|100

This query corresponds to importing the **STATES** measurement specified in the following record in the Sample 3 query.
 
platform_name | platform_id   | datatype | sensor_name | sensor_id   |  reference  |   datafile_id   | agg_count 
-|-|-|-|-|-|-|-
ADRI   | 21fcfe84-a770-4921-8c4b-4520eebe61ff | STATES  | GPS   | d75c1766-3cda-4c47-a5b0-1882a863a368 | nisida_invalid_header_line.txt  | 7d199bac-ef5a-4732-8c5a-dcc0fd195617 |   5


The Start time, End time, and Location parameters should be the same as the ones provided for **pepys.datafiles_for** function.

Sensor Id, Source Id, Platform Id fields specify their respective values as fetched from the **pepys.datafiles_for** function call. They can be either
a) null/blank
b) single uuid value
c) list of comma-separated uuid values.

This query returns 5 rows. This is known ahead from the **pepys.datafiles_for**.agg_count field.

The Page no. and Page size fields are used for pagination.
If there are 1000 records (as determined from **pepys.datafiles_for** query call) paginated into pages of 100 records each (page size), 1 here will return the first page or first 100 (page size) records.


![Query4](https://user-images.githubusercontent.com/77854924/107541340-0af23a00-6bed-11eb-90b1-2d482dd523a7.png)

**Comment by arunlal-v** [comment]
5. Following sample describes a scenario where multiple **STATES** measurements are to be imported using **pepys.states_for** function using the results obtained from Sample 3.

For example, consider importing all measurements corresponding to the following 4 records from **pepys.datafiles_for** query.

platform_name|platform_id|datatype|sensor_name|sensor_id|reference|datafile_id|agg_count
-|-|-|-|-|-|-|-
ADRI|21fcfe84-a770-4921-8c4b-4520eebe61ff|STATES|GPS|d75c1766-3cda-4c47-a5b0-1882a863a368|nisida_invalid_header_line.txt|7d199bac-ef5a-4732-8c5a-dcc0fd195617|5
BOEU2_FR|063a47d8-9b51-408a-af7e-27c5cded2bd8|STATES|SENSOR-1|86eca7cb-0e69-4ee5-bb24-c655b17039ca|ForceProt_3_22_201130_111731.902.rep|42c00877-7193-4cd8-bd44-f7c94b6cbfb3|11521
BOEU2_FR|063a47d8-9b51-408a-af7e-27c5cded2bd8|STATES|SENSOR-1|86eca7cb-0e69-4ee5-bb24-c655b17039ca|ForceProt_3_30_201130_111755.872.rep|e4545cfb-7a87-492d-b1ea-9960ac92f74a|11521
BOEU2_FR|063a47d8-9b51-408a-af7e-27c5cded2bd8|STATES|SENSOR-1|86eca7cb-0e69-4ee5-bb24-c655b17039ca|ForceProt_3_37_201130_111817.293.rep|18938505-682a-4c9b-b25f-8a0c160637aa|11521

The import query will return 34,568 records (5+11521+11521+11521 from agg_count)

The import query will need to specify multiple sensor ids, multiple source ids, multiple platform ids. 
Here's how the import query will be. *(Ignore the selection and pagination clauses)*

```SQL
select count(*) from pepys.states_for('2012-12-12 23:59:59.000000','2020-12-12 23:59:59.000000','SRID=4326;POLYGON((-125.0 65.0,-125.0 -45.0,80.0 -45.0,80.0 65.0,-125.0 65.0))','d75c1766-3cda-4c47-a5b0-1882a863a368,86eca7cb-0e69-4ee5-bb24-c655b17039ca','7d199bac-ef5a-4732-8c5a-dcc0fd195617,42c00877-7193-4cd8-bd44-f7c94b6cbfb3,e4545cfb-7a87-492d-b1ea-9960ac92f74a,18938505-682a-4c9b-b25f-8a0c160637aa','21fcfe84-a770-4921-8c4b-4520eebe61ff,063a47d8-9b51-408a-af7e-27c5cded2bd8',1,500000);
```
![Query5](https://user-images.githubusercontent.com/77854924/107548741-0b8ece80-6bf5-11eb-96c9-d2635824b347.png)

**Comment by arunlal-v** [comment]
###) A note on  pagination parameters.

The Page No. and Page Size. parameters can be any non-negative integer values. Its purpose is to prevent the import client from freezing when importing huge number of records in one go. Pagination gives an elegant approach where the records can be fetched in pages using multiple calls.

The first call can be with (page_no, page_size) = (1,100), the second call can be with (2,100). At this point if the client determines that the network can handle additional load, the third call can be with (2,200), in other words, return records 201 to 400.

**Comment by IanMayo** [comment]
> Make sure the tracstor_view user has the privilege to execute these functions (Handled from Alembic/SQLAlchemy)

@arunlal-v - I don't think we'll always know the user name.  Would it be possible to give all registered users the privilege to run them?

**Comment by arunlal-v** [comment]
> > Make sure the tracstor_view user has the privilege to execute these functions (Handled from Alembic/SQLAlchemy)
> 
> @arunlal-v - I don't think we'll always know the user name. Would it be possible to give all registered users the privilege to run them?

It's possible @IanMayo . [Postgres 10 allows function execution for all users by default](https://www.postgresql.org/docs/10/sql-grant.html). If we need to explicitly do this, the following command will help.

```SQL
GRANT EXECUTE ON FUNCTION PEPYS.STATES_FOR TO PUBLIC;
```

This is granted by default. But, mostly this is not recommended as standard. Since these functions are just **SELECT** only and don't have any other side-effects, it should be fine.

**Comment by arunlal-v** [comment]
Sample 6. Fetching **COMMENTS** measurement data
```SQL
select * from pepys.comments_for('2012-12-12 23:59:59.000000','2020-12-12 23:59:59.000000','fishing',array['7d199bac-ef5a-4732-8c5a-dcc0fd195617','42c00877-7193-4cd8-bd44-f7c94b6cbfb3','e4545cfb-7a87-492d-b1ea-9960ac92f74a','18938505-682a-4c9b-b25f-8a0c160637aa'],array['21fcfe84-a770-4921-8c4b-4520eebe61ff','063a47d8-9b51-408a-af7e-27c5cded2bd8'],1,100);
```
Description of function arguments: 

Argument Position|Parameter Name::Data type|Argument value|Defaulted value in function (in case of blank or null)
-|-|-|-
1|Start time::text|'2012-12-12 23:59:59.000000'|1000-01-01 00:00:00.000000
2|End time::text|'2020-12-12 23:59:59.000000'|9999-12-12 23:59:59.000000
3|Comment Text to be searched::text|'fishing'|N.A.
4|Source Id::text[]|array['7d199bac-ef5a-4732-8c5a-dcc0fd195617','42c00877-7193-4cd8-bd44-f7c94b6cbfb3','e4545cfb-7a87-492d-b1ea-9960ac92f74a','18938505-682a-4c9b-b25f-8a0c160637aa']|N.A.
5|Platform Id::text[]|array['21fcfe84-a770-4921-8c4b-4520eebe61ff','063a47d8-9b51-408a-af7e-27c5cded2bd8']|N.A.
6|Page No.|1|1
7|Page Size|500000|100

Compared to pepys.states_for function, this function does not require the **location** and **sensor_id** arguments.

![Query6](https://user-images.githubusercontent.com/77854924/107793805-bd0c3c00-6d7c-11eb-8131-8745e347f2d9.png)

**Comment by arunlal-v** [comment]
Sample 7. Fetching **CONTACTS** measurement data
```SQL
select * from pepys.contacts_for('2012-12-12 23:59:59.000000','2020-12-12 23:59:59.000000',null,array['f0f96e4b-5d99-4204-969d-c5d65372db5e'],array['7d199bac-ef5a-4732-8c5a-dcc0fd195617'],array['21fcfe84-a770-4921-8c4b-4520eebe61ff'],1,100);
```
Description of function arguments: 

Argument Position|Parameter Name::Data type|Argument value|Defaulted value in function (in case of blank or null)
-|-|-|-
1|Start time::text|'2012-12-12 23:59:59.000000'|1000-01-01 00:00:00.000000
2|End time::text|'2020-12-12 23:59:59.000000'|9999-12-12 23:59:59.000000
3|Location::text|null|N.A.
4|Sensor Id::text[]|array['f0f96e4b-5d99-4204-969d-c5d65372db5e']|N.A.
5|Source Id::text[]|array['7d199bac-ef5a-4732-8c5a-dcc0fd195617']|N.A.
6|Platform Id::text[]|array['21fcfe84-a770-4921-8c4b-4520eebe61ff']|N.A.
7|Page No.|1|1
8|Page Size|100|100


This is similar to **pepys.states_for** function.

![Query7](https://user-images.githubusercontent.com/77854924/107794097-08264f00-6d7d-11eb-808d-8427e9617a0c.png)

**Comment by IanMayo** [comment]
@arunlal-v  - could you give us the SQL necessary to create the procedures, and to give all current users permission to run them?

**Comment by arunlal-v** [comment]
@IanMayo - The files are already [checked in.](https://github.com/debrief/pepys-import/tree/develop/pepys_import/database/stored_procedures) Also, the [grants are implicitly granted.](https://github.com/debrief/pepys-import/issues/753#issuecomment-778282339) Please let me know if you need additional information.

**Comment by IanMayo** [comment]
Done.
