### ISSUE TITLE
Performance when changing Data Source in Maintainer Panel

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#768]
On my (quite slow) MS-Windows virtual machine there is a 5 second pause when I select the `Sensors` table.  A progress window is shown.

It would be useful to understand what is taking time, and potentially working with our SQL expert if it's a database issue.

Or, as previously discussed, cacheing may also be an option, certainly for the Reference Tables.

This task is relatively low priority.  We deliver more value right now by continuing to add Maintenance Actions.

**Comment by robintw** [comment]
This has been speeded up in various other PRs, and I think it is now as fast as we can reasonably get it.
