### ISSUE TITLE
Produce large SQLite database

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#769]
@arunlal-v could do with a large SQLite database, in order to test the performance of SQLite queries.

The project would benefit from @arunlal-v having wider understanding of the application.

So, I'd like @arunlal-v  to run install Pepys locally, and work through the tutorial here: https://pepys-import.readthedocs.io/en/latest/getting_started.html

Once he has done that he can import higher volumes of data from the tests/sample_data/tracks folder in the root of Pepys.  Note: when doing this, it will be quicker if he runs Pepys from the command-line, and uses the default resolver, as documented here: https://pepys-import.readthedocs.io/en/latest/usage.html

The route for a non-MS-Windows setup is to follow the developer setup steps, as recorded [here](https://pepys-import.readthedocs.io/en/latest/developer_guide.html)

**Comment by arunlal-v** [comment]
Thanks for sharing the Linux installation steps, @IanMayo 

https://pepys-import.readthedocs.io/en/latest/developer_guide.html

**Comment by arunlal-v** [comment]
Installation notes (to be updated in [the guide](https://pepys-import.readthedocs.io/en/latest/developer_guide.html))

##### 1) Just like python3.6, **pip** can also be accessed as **pip3.6** or **pip3.7** depending on the system

**Comment by arunlal-v** [comment]
Lot of dependencies were missing for my OS (Centos 8), but was able to proceed after deploying the required dependencies as stated in various error messages of the **make** process.

**Comment by arunlal-v** [comment]
Installation complete.

Tests are failing: 
                                                                                                                                                   

tests/test_admin_cli.py ........................................FFFFFF...

**Comment by arunlal-v** [comment]
Tests are still in progress. Postgis has some issues. Will check into it.

ests/test_admin_cli.py ........................................FFFFFF...
.....................                                                                  [  8%]
tests/test_admin_utils.py .......                                                                                                                               [  9%]
tests/test_basic_validator.py ....                                                                                                                              [  9%]
tests/test_command_line_resolver.py ..........................................................                                                                  [ 16%]
tests/test_constraints.py ......................FFFF                                                                                                            [ 20%]
tests/test_data_store_api_postgis.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.                                                                                           [ 24%]
tests/test_data_store_api_spatialite.py ....................................                                                                                    [ 28%]
tests/test_data_store_clear_db.py s.s.                                                                                                                          [ 28%]
tests/test_data_store_edit.py .......                                                                                                                           [ 29%]
tests/test_data_store_export_datafile.py s.........                                                                                                             [ 31%]
tests/test_data_store_initialise.py sss...                                                                                                                      [ 31%]
tests/test_data_store_merge_operations.py ...............                                                                                                       [ 33%]
tests/test_data_store_populate.py ..FF..........                                                                                                                [ 35%]
tests/test_data_store_split_operations.py ..                                                                                                                    [ 35%]
tests/test_datafile.py ......                                                                                                                                   [ 36%]
tests/test_default_resolver.py ........                                                                                                                         [ 37%]
tests/test_duplicates.py ..............                                                                                                                         [ 38%]
tests/test_enhanced_validator.py .......                                                                                                                        [ 39%]
tests/test_filter_widget_output_to_query.py ........                                                                                                            [ 40%]
tests/test_help_texts.py ......................                                                                                                                 [ 43%]
tests/test_import_cli.py .FF.........                                                                                                                           [ 44%]
tests/test_import_cli_end_to_end.py ......................                                                                                                      [ 47%]
tests/test_importer_utils.py .                                                                                                                                  [ 47%]
tests/test_importers.py ......................                                                                                                                  [ 50%]
tests/test_importers_postgis.py ..                                                                                                                              [ 50%]
tests/test_load_eag.py ....                                                                                                                                     [ 51%]
tests/test_load_etrac.py .                                                                                                                                      [ 51%]
tests/test_load_gpx.py F                                                                                                                                        [ 51%]
tests/test_load_nisida.py ...                                                                                                                                   [ 51%]
tests/test_load_nmea.py .                                                                                                                                       [ 51%]
tests/test_load_rep.py ..                                                                                                                                       [ 52%]
tests/test_load_rep_comment.py ..                                                                                                                               [ 52%]
tests/test_load_rep_contact.py ....                                                                                                                             [ 52%]
tests/test_location.py ..................................                                                                                                       [ 57%]

**Comment by arunlal-v** [comment]
=================================================
 72 failed, 729 passed, 14 skipped, 3 xfailed in 2697.45s (0:44:57) ==================================================

**Comment by IanMayo** [comment]
Hmm, another strategy for this would be to dump the PostGres database to SQL, translate SQL to SQLite, run that SQLite.

**Comment by arunlal-v** [comment]
The hex import is failing. I'm trying to ascertain the proper format to convert postgis data to spatialite.

spatialite> select st_distance(didp,makepoint(0,1,4326)) from bb where did =2;

spatialite> select st_distance(location, makepoint(1,1,4326)) from states;
31.0491948759209
31.1905327909433
30.9653995553571
30.9761670695861
30.8240025999692
35.5277695784892
36.0540501808666
36.0540501808666
35.1796902219322
35.6129880154543

**Comment by arunlal-v** [comment]
The following query should export Postgis records in pepys."States" table to Spatialite 

select 
	'('''||
	translate(state_id::varchar,'-','') ||''','|| --State_Id
	case when "time" is null then 'null' else ''''|| upper(to_char(("time" at time zone 'UTC'),'YYYY-MM-DDtHH24:MI:SS.SS'))||'Z''' end ||','|| --time
	case when sensor_id is null then 'null' else ''''||translate(sensor_id::varchar,'-','') || '''' end ||','|| --sensor_id
	case when elevation is null then 'null' else elevation::text end || ','|| --elevation
	case when heading is null then 'null' else heading::text end || ','|| --heading
	case when course is null then 'null' else course::text end  || ',' || --course
	case when speed is null then 'null' else speed::text end  || ',' || --speed
	case when source_id is null then 'null' else ''''||translate(source_id::varchar,'-','') || '''' end ||','|| --source_id
	case when privacy_id is null then 'null' else ''''||translate(privacy_id::varchar,'-','') || '''' end ||','|| --privacy_id
	case when remarks is null then 'null' else ''''||remarks || '''' end ||','|| --remarks
	case when "created_date" is null then 'null' else ''''|| upper(to_char(("created_date" at time zone 'UTC'),'YYYY-MM-DDtHH24:MI:SS.SS'))||'Z''' end ||','|| --created_date
	case when "location" is null then 'null' else 'geomfromewkb('''||encode(st_asewkb(location),'hex') || ''')'end --location
	|| '),'  --location -> it's assumed that source and destination have same endian setting
from pepys."States";

**Comment by arunlal-v** [comment]
This is a basic script that will generate the large Spatialite DB. This worked fine when I tested with one table. I'll integrate the other [queries shared earlier](https://github.com/debrief/pepys-import/files/6111528/Postgis2Spatialite.txt)

I'll also be refactoring the code to remove hard-coded db information, add in some exception handling, and some filter options to be specified to limit the number of records being exported.

[postgis2spatialite_exp.txt](https://github.com/debrief/pepys-import/files/6131816/postgis2spatialite_exp.txt)

**Comment by arunlal-v** [comment]
Here's a sample db with 10000 records for each of the measurements table.
[sample.db.tar.gz](https://github.com/debrief/pepys-import/files/6144698/sample.db.tar.gz)

**Comment by IanMayo** [comment]
Hmm, I see 10k `State` records, but not for `Comments` or `Contacts`.   But, that's not a problem - this will still be useful for performance experiments.

**Comment by arunlal-v** [comment]
Attached is the setup to transfer records from Postgis to Spatialite. (Limit for Measurements tables is set to 10000 records)

[setup.tar.gz](https://github.com/debrief/pepys-import/files/6150738/setup.tar.gz)

**Comment by IanMayo** [comment]
Done.
