### ISSUE TITLE
Merge Platforms - clear cache before select default

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#776]
## Version

https://github.com/debrief/pepys-import/releases/download/maintenance_gui_beta2/20210212_pepys-import.zip
## 🐞 Description

Users are doing a series of `Merge` operations.  But, when they filter for a new set of platforms, and select the ones to merge, the popup for `Select Target` includes selected platforms and those that were present for the previous merge.

Users worked around it by repeatedly doing `Esc` to go out of maintenance mode, and then back in.

User's words:
```
One complaint/concern: We were doing a 'mass merge' - so doing a number of separate merges of 
platforms. But after we pressed F8 and Merge platforms the 'select target platform' pop up box showed
 us the ones we wanted to merge (and the ones from previous). We weren't sure whether it simply 
doesn't clear the 'memory' or whether we would unwittingly merge all of those platforms together. 
And so we had to ESC and go back to the menu, press 8 for maintenance and go back into it. 

It's fine because these 'mass merge' fixes aren't going to be a frequent thing, but it did make the 
process a little more arduous than it needed to be. 
```

**Comment by robintw** [comment]
Ah yes, that's already been fixed @IanMayo - in b98f25282b921c9749e3706d3c0735adbfd65d81 which was in the PR for the GUI Phase 2. We could do another beta release from the current state of develop?

**Comment by IanMayo** [comment]
They're not doing Pepys work until next Tuesday, and are looking forward to Splitting Platforms then.

So, my preference is for us to get Split Platforms done, and then push GUI 3 to them.

They're also looking forward to editing Platform data, since some have identifier as name, or vice-versa, so I was pleased to say that's due in the following release.

**Comment by IanMayo** [comment]
Closing, fixed in: https://github.com/debrief/pepys-import/commit/b98f25282b921c9749e3706d3c0735adbfd65d81
