### ISSUE TITLE
Need datafile reference in stored procedures

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#778]
Analysts load Pepys measurements into the Debrief application.

As the data is loaded, it is arranged in folders according to the original datafile.

So the [Stored Procedures & SQLite queries](https://github.com/debrief/pepys-import/tree/develop/pepys_import/database) need `Datafile.Reference` to be included in the results, for @saulhidalgoaular to use.

**Comment by arunlal-v** [comment]
Right now, these are the output structures of measurement queries. I'll append ```Datafile.Reference``` to the end in all the queries.

**Comments:**

Column Name|Column Type
-|-
comment_id|UUID
comment_time|TIMESTAMP WITHOUT TIME ZONE
platform_name|varchar(150)
platformtype_name|varchar(150)
nationality_name|varchar(150)
content|text
comment_type_name|varchar(150))

**Contacts:**

Column Name|Column Type
-|-
contact_id|UUID
contact_time|TIMESTAMP WITHOUT TIME ZONE
sensor_name|varchar(150)
platform_name|varchar(150)
platformtype_name|varchar(150)
nationality_name|varchar(150)
bearing|double precision
range|double precision
contact_location|public.geometry(Point4326))

**States:**

Column Name|Column Type
-|-
state_id|UUID
state_time|TIMESTAMP WITHOUT TIME ZONE
sensor_name|varchar(150)
platform_name|varchar(150)
platformtype_name|varchar(150)
nationality_name|varchar(150)
state_location|public.geometry(Point4326)
elevation|double precision
heading|double precision
course|double precision
speed|double precision)

**Comment by arunlal-v** [comment]
[Pull request](https://github.com/debrief/pepys-import/pull/782) created for the same.

**Comment by IanMayo** [comment]
Done.
