### ISSUE TITLE
Need number of records in Datafile in phase 1 query

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#781]
Some datafiles contain huge amounts of data. 

Analysts will understand if it takes these files a long time to load into Debrief.

But, from the UI it isn't clear how many rows they contain.  

When we display the available data, in the Phase 1 of the query we could label each block with the number of records.

Further to that, I'd like us to show a progress monitor as we import. To do that, we need to know how many rows are to be be imported, and then update the monitor after each `page` of results.

We do know the total number of rows in the selected datafiles (well we will once the data is in the Phase 1 query). But, the search filters may only pull in some of the data from each data.

So, I _think_ we need to fire a `count()` query to each measurement type before the import process.

Do you think this is achievable, @arunlal-v ?

**Comment by arunlal-v** [comment]
I don't think a separate **count()** query is required prior to each import measurement call.

The following is a sample resultset for a phase 1 query.

platform_name|platform_id|datatype|sensor_name|sensor_id|reference|datafile_id|agg_count
-|-|-|-|-|-|-|-
ADRI|21fcfe84-a770-4921-8c4b-4520eebe61ff|STATES|GPS|d75c1766-3cda-4c47-a5b0-1882a863a368|nisida_invalid_header_line.txt|7d199bac-ef5a-4732-8c5a-dcc0fd195617|5
BOEU2_FR|063a47d8-9b51-408a-af7e-27c5cded2bd8|STATES|SENSOR-1|86eca7cb-0e69-4ee5-bb24-c655b17039ca|ForceProt_3_22_201130_111731.902.rep|42c00877-7193-4cd8-bd44-f7c94b6cbfb3|11521
BOEU2_FR|063a47d8-9b51-408a-af7e-27c5cded2bd8|STATES|SENSOR-1|86eca7cb-0e69-4ee5-bb24-c655b17039ca|ForceProt_3_30_201130_111755.872.rep|e4545cfb-7a87-492d-b1ea-9960ac92f74a|11521
BOEU2_FR|063a47d8-9b51-408a-af7e-27c5cded2bd8|STATES|SENSOR-1|86eca7cb-0e69-4ee5-bb24-c655b17039ca|ForceProt_3_37_201130_111817.293.rep|18938505-682a-4c9b-b25f-8a0c160637aa|11521

If the **States_for** procedure is called for Platform Id, Sensor Id, and Datafile Id corresponding only to the first records, then only 5 records can be expected.The 5 in this case is the number indicated by **agg_count** column.

If a special case import requires all records belonging to sensor SENSOR-1 (sensor Id: 86eca7cb-0e69-4ee5-bb24-c655b17039ca) irrespective of **Platforms** or **Datafiles**, then the count of expected records can be calculated by summing up all **agg_count** values having that sensor id. In this case, the number of records will be 34563 (i.e. 11521+11521+11521)

Java Streams (available from Java 8, Debrief is on Java 11 as seen from pom.xml) should be able to [perform similar calculations in a jiffy](https://www.baeldung.com/java-stream-sum), even for [plain resultset objects](https://stackoverflow.com/questions/42840747/java-streams-to-iterate-over-a-resultset-object).

**Comment by IanMayo** [comment]
Aah, ok.  So the `agg_count` value is the number of matching measurements.  It's not the length of that datafile. Is that right?

**Comment by arunlal-v** [comment]
Exactly. ```agg_count``` is the number of matching measurements.

**Comment by IanMayo** [comment]
Great. Issue closed.
