### ISSUE TITLE
Maintenance Actions - context sensitive enable

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#785]
## 🐞 Overview
Some actions are only applicable in some circumstances.

We can make users aware of what actions are available by greying options that don't apply to the current situation.

But. rather than disabling irrelevant actions we'll grey them out, but still allow them to be clicked.  Clicking an irrelevant action will provide guidance/feedback on what data must be selected for that action to be run.

## 🔗 Feature

#600

**Comment by robintw** [comment]
Fixed in #784.
