### ISSUE TITLE
Method to delete records from a table

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#788]
## 🐞 Overview
As part of the Maintenance GUI, we need a 'delete' action that will delete the selected records from a specific table. For example, we might have selected multiple Platforms and want to delete them. Actually doing the delete is easy - just run a SQLAlchemy delete operation - but we need to work out what to do about the items that depend on them.

For example, when deleting a Platform, we may have Sensor, Comment, Participation etc objects that link to that Platform. What should we do about those objects? Similarly, when deleting a Nationality or PlatformType object we may have Platforms that depend on that object - and so on, for all the other tables.

I'm genuinely not sure what to do about this - I don't know how users would expect to deal with this situation, and how much they would understand the situation itself. @IanMayo @clenoble Your advice here would be great.

Once we've established how this should work, I would suggest @BarisSari works on the method, while I work on some of the other GUI stuff.

## 🔗 Feature
#600, specifically supporting #786.

## 🔢 Acceptance criteria
A new method on DataStore that deletes items given a list of IDs (or item objects)
Tests showing that the delete method works correctly given various database objects with various dependencies between them

**Comment by robintw** [comment]
I've been thinking about this a bit more, and have a few thoughts:

 - I was wondering whether we actually need a 'switch' method, that switches all references to Platform X to Platform Y, and then allows you to delete Platform X. Then I realised that this is basically a merge of Platform X and Platform Y, with Platform Y being the target - and we already support merges. So, we might not need to deal with dependent objects when deleting, because the user can just do a merge instead (which would also delete Platform X once it has been merged
 - It might be useful to have a 'Delete, but only if no references elsewhere in the database' option, to deal with entries that have been added by mistake and genuinely have no references or uses in the database. That would be fairly easy to implement

What do you think?

**Comment by IanMayo** [comment]
Hello @robintw  - when I thought about this last night, the second option seemed the right one, to avoid "hanging data".

I'll ask the clients. I guess their choice is:
1. provide cascading deletes, where all linked/dependent data is also deleted
2. only allow delete if no references

**Comment by robintw** [comment]
Yes, I agree. We'll have to be very careful with giving them extra information on what is going to be deleted if they do a cascading delete though: potentially deleting one Nationality could delete tens of thousands of measurements (all the measurements of all the sensors of all the platforms that have that nationality)

**Comment by BarisSari** [comment]
Hello @robintw and @IanMayo . You're right about the cascading delete @robintw. I think we use it for (almost) all foreign key relationships. And one reference could delete lots of entities. 

Maybe we can show an extra dialogue, which says: "there are XXXX entities depend on the selected objects. Are you sure to delete all of them?". If they say yes, we can use cascading delete.

**Comment by IanMayo** [comment]
Hello @robintw  & @BarisSari.

I'm writing the question for the users.  They have the option of two patterns for delete. One is "Cascading Deletes".  I'm struggling to come up with a name for the other - where we only allow something to be deleted if nothing refers to it. "Only delete unreferenced" ?  Is there a database name for the pattern?

**Comment by robintw** [comment]
I'm not sure whether we actually need a question or not: we can work out whether there are any dependent objects for the record and if there are no dependent objects then we can popup a dialog asking them to confirm deleting this single object, but if there are dependent objects then we can pop up a dialog saying that this would delete X number of dependent objects (possibly even split into different types - X Platforms, Y Sensors etc). How does that sound?

**Comment by IanMayo** [comment]
Thanks @robintw .

I recognise the merits of the latter, but it would seem to require a lot of code, unless SQLAlchemy introspection allows it to be performed in a generic way.

I'll include the option in the question to them.

**Comment by robintw** [comment]
I think we can do it fairly easily using the sqlalchemy-utils `dependent_objects` function that Baris found - that should get us a list of objects, and we can then separate them out into types if we want.

**Comment by BarisSari** [comment]
Yes, I think I can do it easily, @IanMayo.

**Comment by IanMayo** [comment]
That's great, thanks @BarisSari & @robintw .  I've still asked the question, but I've suggested we allow cascading deletes, but make sure the user is aware of what else will be deleted.

**Comment by IanMayo** [comment]
Update for @BarisSari : clients happy with Cascading Delete with confirmation of what else will be deleted.

**Comment by BarisSari** [comment]
I have two questions for you, @robintw :
1. When we find dependent objects, one dependent object (a sensor of a platform) might also have many dependent objects (measurements of the sensor). Do you want me to include them, too? Or is it enough to say that 1 Sensor and its related objects will be deleted with the given Platform?
2. I'm returning a dictionary in this format: `{"Platforms": 1, "Sensors": 2}`. Do you want me to create a string from this dictionary, or would you prefer doing it in the GUI code?

**Comment by robintw** [comment]
1. I think we need to have _all_ dependent objects - because some of the most important things that might be deleted are things like States or Contacts, and they will be 'second-order dependencies', and we need to warn the user about these being delete.

2. A dict is great, then I can format it nicely in the GUI.
