### ISSUE TITLE
Switch Travis to 3.7

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#79]
Travis is currently running the test/build on 3.8, which is the newest version of Python.

But, our deployment target is 3.7, so it would be sensible to always run our test suite against that version.

**Comment by BarisSari** [comment]
I think it would be better if we also change our test command to **_pytest tests_**.

**Comment by IanMayo** [comment]
But, currently Travis is doing code-coverage at the same time as unit-tests.

We could switch to `pytest`, but wouldn't we then have to call `coverage` too?

**Comment by BarisSari** [comment]
This command should work without a problem: `coverage3 run -m pytest tests`

**Comment by IanMayo** [comment]
Good suggestion @BarisSari (& @robintw ) , much cleaner:
![image](https://user-images.githubusercontent.com/1108513/74837968-898a0380-531a-11ea-8f52-653a4e49b570.png)
