### ISSUE TITLE
Issues around measurement table filtering and editing

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#791]
_Note: The text below is copied from comments on #786, the original PR for doing these changes. That PR was re-scoped to just Add/View/Delete functionality and not dealing with measurement tables, so I've copied the comments here so they're easier to access once that PR is merged._

**Robin:**
We're making good progress with the add and delete functionality, but I've got a number of questions about starting to include measurement tables (State, Contact etc) in the GUI. I've got the very basics working (you can view the States table, for example), but there are lots of things we need to decide about:

Filtering measurement tables
What sort of fields do we need to be able to filter by? For example, do we need to be able to:

filter by location? If so, we'll need some way of specifying something like a bounding box, or a point and a radius or something - and we're going to start getting into complicated GUIs for specifying these, plus more complicated geospatial queries for querying the data. Definitely not impossible, but quite a lot of work - so we need to consider whether the user needs it.
filter by measurement values - such as speed, bearing, elevation and so on. This would definitely be easier, but we'd need to work out what we were doing about units: do we force the user to query in the units the database uses internally (m/s, radians etc), or do we allow them to specify their units and do the conversions ourselves. Again, that requires the relevant GUI and backend code to deal with it.
It makes sense that we would want to be able to filter by the Platform or Sensor that the measurement was obtained from - but this actually gets a bit difficult. There can (and probably will) be multiple Platforms/Sensors etc with the same name - so just having a dropdown of name won't be very useful (if there are 5 items with the same name, which do you choose). What we really need to do is to provide a dropdown with all the distinguishing criteria used for that table in it - so a dropdown showing something like HMS BLAH - 123 - United Kingdom (name, identifier and nationality). However, if we do that then we're creating our own representation of data from the database and can't easily do things like LIKE queries on it (and LIKE queries would be weird anyway, as they would match in the nationality name as well).

The same problem appears when we are editing measurement tables: we need a way of choosing a new Sensor for a State object, or assigning one from scratch if we're adding rather than editing. In fact, this will get even more complex for some measurement tables, as we want to be able to search on the Platform that is linked to a State, but we can't let the user edit the Platform value directly, as it is indirectly referenced through the assigned Sensor (a State has a Sensor, and each Sensor has a Platform).

Actually, these issues also already apply to the Sensors table, which even though it is a metadata table, has a foreign key to the Platforms table, so suffers from the same problems.

What do you think @IanMayo? Do we have some use cases from the clients on what they actually want to do with the GUI when it comes to filtering and editing measurement tables? If not, I think these would be helpful, as it would save us spending a lot of effort implementing functionality that may not be used (although I can understand the desire to have all of the Add/Edit/etc functions work for measurement tables, for completeness sake).

**Ian:**
filter by location

Yes, let's defer this.

filter by measurement values

Yes, let's defer this until we're clear on it.

I do see the value - It could let them do some elementary analysis. I think we can be more restrictive in units, at first. We could only take values in the existing units for an attribute. We could defer being flexible with units.

Yes, there are some interesting issues there. I think we can't avoid the multi-field drop-down entries. I'd hope that the type-to-filter practice that we use in import data would also work within the form. I think in most cases the user will type the platform name, and if multiple nations have a platform with that name then the user will select the relevant one.

Maybe the sensor/platform issue is simpler. If we are editing a State object, then the Sensor field will contain values that represent the Sensor and the Platform (sadly we would need the 3 platform unique identifiers). Again, I would expect the user to trim the matches down using the platform name first, then click/select the relevant sensor from the reduced list.

** Filtering/editing measurements.**
Once we have a graphing capability I look forward to them producing their own tim-variable graphs. Editing measurements should be rare. I think the "change" sensor processing may actually be a "merge" operation, though that would only transfer all measurements from one to another. Aah, another (future) operation could be tagging measurements. For some type of analysis they may want to know periods when a platform is travelling within a set speed bracket. They'll use maintenance tools to find the data, then add a tag to the State rows (well, create TaggedItem entries).

For the bigger picture regarding measurements, I don't think they're thinking at that level yet. They're focussing on the metadata, and just using Debrief to handle (view) measurements. But, as they move away from spatial analysis, they will need new tools/capabilities.

**Comment by robintw** [comment]
@IanMayo Can you clarify what you meant by this bit in your comment:

> I think the "change" sensor processing may actually be a "merge" operation, though that would only transfer all measurements from one to another.

**Comment by IanMayo** [comment]
Sure. We have a group of `State` measurements, and we wish to change their `Sensor` from `SensorA` to `SensorB`.  I was proposing that this could alternately be conducted by `merge` of `SensorA` to `SensorB`.  But, that's only feasible if all of the `States` from `SensorA` were to be moved over.
