### ISSUE TITLE
Welcome banner

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#8]
When the command line app opens, it would strengthen our branding if we had some ascii text.

I suggest we display `Pepys_import` in the `Doom` font, like in this app:
http://patorjk.com/software/taag/#p=display&f=Doom&t=Pepys_import

It should look like this:
![image](https://user-images.githubusercontent.com/1108513/68322714-ce679280-00bb-11ea-83e1-866eadff154e.png)

Aah, we should also show the software build version, plus some summary of the database connection (SQLite vs PostGres, SQLite filename, PostGres hostname/db-name)

The API for creating a new data-store includes boolean flags for welcome banner & initial status.

**Comment by tahirs95** [comment]
Is it looking good?
![welcome_banner](https://user-images.githubusercontent.com/29951703/68424778-900aca00-01c6-11ea-920a-1a49e334ca6e.png)

Q1: Do we need to display sofware version, database details etc as fancy text or normal?
Q2: Can you please elaborate "The API for creating a new data-store includes boolean flags for welcome banner & initial status."?

**Comment by IanMayo** [comment]
Q1 - normal text
Q2 - the API is described here: https://docs.google.com/document/d/1RW148XW4Iqr1mwEk5TezmgBf8z9zhZ-T88flk9stFiY/edit#bookmark=id.4mv8tg71ogm4

**Comment by IanMayo** [comment]
Fixed in #20
