### ISSUE TITLE
Escape key delay in GUI

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#801]
One of the previous minor comments from @IanMayo was that there seems to be a delay between pressing the Escape key, and the actual action occurring.

I was going to ask Jonathan about it, but decided to do a bit of searching of the prompt toolkit code before asking him, and I found the following code:

```
#: When to flush the input (For flushing escape keys.) This is important
#: on terminals that use vt100 input. We can't distinguish the escape
#: key from for instance the left-arrow key, if we don't know what follows
#: after "\x1b". This little timer will consider "\x1b" to be escape if
#: nothing did follow in this time span.
#: This seems to work like the `ttimeoutlen` option in Vim.
self.ttimeoutlen = 0.5  # Seconds.
```

Basically, it seems that the way that escape codes work in VT100 terminals (ie. most of them), is that they send `\xb1` potentially followed by something else. If there is nothing else following it, then it just the escape key, but if something is following it then it could be any other special key (arrow key, F-key etc).

Given that, I don't think there is anything we can do about the delay with escape. I can go ahead and ask Jonathan if you want, but I suspect there won't be anything we can do.

What do you think @IanMayo?

**Comment by IanMayo** [comment]
I that case I'm quite happy to live with it, thanks.
