### ISSUE TITLE
Maintenance GUI needs "2. Status" before it will allow "8. Maintenance Tools"

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#802]
I've entered Pepys-Admin to verify new maintenance tools.

If I try to go straight to maintenance tools, it tells me the database isn't initialised.

But if I run "2. Status" first, it's then possible to go into maintenance tools.

Video recording here: https://i.gyazo.com/191ede19fa4fb7e77d375c9292ea7cd6.mp4

(video link provided rather than GIF, since GIF was too small to be readable)

**Comment by robintw** [comment]
That's _really_ strange.

Is this repeatable with the same database file? I mean, if you go through this process, and then exit Pepys Admin, and then run Pepys Admin again with the same database file, do you still have to go through Status first before being able to run the GUI?

If so, can you send me the SQLite file so I can investigate?

**Comment by robintw** [comment]
Ah hang on, I think I've worked out what might be going on. I'll do a hotfix later and you can test.

**Comment by IanMayo** [comment]
Sorry, I did intend to attach the database file.  Yes, it's reproducible - it took several attempts to capture the video :-)

It's the Nov 2020 database that had to be migrated before use. This is the migrated version.
[pepys_test.sqlite.zip](https://github.com/debrief/pepys-import/files/6103191/pepys_test.sqlite.zip)
