### ISSUE TITLE
Error from logging table

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#805]
## Version

Rel 5a

## 🐞 Description

Errors thrown during attempted merge and split of platforms.

The errors seem to refer to "New_value", but we've changed that field to be "previous value".

Aah, this could highlight an error we discussed last week.  To test a beta they may run a migration. But the sources for the "Current" (non-beta) release will then be working to the wrong (pre-migration) schema.

Hmm, this does look like a version control issue. Maybe the users aren't using Rel 5a.

## 🔢 Steps to Reproduce
[waiting for reproducible steps]
## 🖥️ Screenshots

![For Ian 3](https://user-images.githubusercontent.com/1108513/110493602-adb5af80-80ea-11eb-8393-686bd3ab5bb6.PNG)
![For Ian 2](https://user-images.githubusercontent.com/1108513/110493609-aee6dc80-80ea-11eb-9c9a-63b1b2adb713.PNG)

**Comment by robintw** [comment]
If they've run a migration, then I would expect this error on an old version of Pepys, but not on a new (Rel 5a) version of Pepys.

**Comment by IanMayo** [comment]
Yes, we could expect it when an old Pepys connects to a new database.

#807 may overcome version confusion.

**Comment by IanMayo** [comment]
This error didn't occur with today's tests. As we suspected, it was probably down to inconsistent verisons of Pepys & database.
