### ISSUE TITLE
Setup hosted Apache Superset

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#811]
A hosted Apache Superset will be useful for @nikhilbaby to demonstrate how to implement features, for the Pepys dev team to become familiar with its capabilities, and to get feedback from @clenoble  and the user representatives.

**Comment by nikhilbaby** [comment]
New superset installation completed. 

Host: dashboard-1258843151.us-east-1.elb.amazonaws.com

**Comment by nikhilbaby** [comment]
![Screenshot from 2021-03-11 23-55-57](https://user-images.githubusercontent.com/9347673/110835972-7ea76580-82c5-11eb-90e7-5ad6081685cb.png)

**Comment by nikhilbaby** [comment]
Lets close this as this is complete.

**Comment by IanMayo** [comment]
Yes, done.
