### ISSUE TITLE
Connect Superset to Postgres

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#812]
We're going to feed the dashboard from the hosted PostGres database.

The steps to connect to PostGres should be captured as a series of screenshots to lead client admin through the process.

The screenshots (or screen recording) can be added to this issue.

The task should include the steps to load/install the postgres driver.

Aah, maybe it isn't necessary to install the postgres driver, that's lucky:
![image](https://user-images.githubusercontent.com/1108513/110812409-7b898680-827f-11eb-9ef9-eb6467253f25.png)

**Comment by nikhilbaby** [comment]
@IanMayo Send the database name also. That is required for connection.

**Comment by nikhilbaby** [comment]
Completed connection to clients database

**Comment by nikhilbaby** [comment]
![Uploading Screenshot from 2021-03-11 23-55-57.png…]()

**Comment by nikhilbaby** [comment]
![Screenshot from 2021-03-11 23-55-57](https://user-images.githubusercontent.com/9347673/110836002-8b2bbe00-82c5-11eb-8e1c-70eef00fcf11.png)

**Comment by IanMayo** [comment]
I guess we're to late for this 🤣

Did you capture the screenshots of adding the database?

They will be really useful to the client admins.

If you didn't capture then, could you delete the database & repeat the steps please?

**Comment by nikhilbaby** [comment]
You can follow the steps below to add a database to superset:

1. Click on the Data menu on the top navigator bar after login
2. Click on Databases in the menu. You will be taken to a page that lists all databases. 
3. Click on the add database button on the top right corner.  A new dialog box will appear. 
4. In the dialog enter a name for the database.
5. Pass the SQL URL in the following format: 
```
postgresql+psycopg2://user:password@host:5432/database
```
6. Click on the test button to make sure everything is working fine. 
7. Click on add database. 


Please use the following image for reference:
![Screenshot from 2021-03-12 16-25-52(1)](https://user-images.githubusercontent.com/9347673/110933340-a0026300-8352-11eb-80ad-f18c5475acf5.jpg)

**Comment by IanMayo** [comment]
Complete.
