### ISSUE TITLE
Display most recently added data

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#813]
This is a simplified dashboard, to gather early feedback.

The dashboard should include:
* table of most recently added datafiles, with datafile type
* table of platforms that have most recently received data
* time graph of number of measurements stored in database by date created (imported)

Ideally the task will include providing some definition file that can be passed onto clients, plus steps in how to load the dashboard.

**Comment by nikhilbaby** [comment]
@IanMayo 

I have created this sample dashboard where you can filter data based on time. 

1. The fist row have details of data files created
2. The second line charts show trends of measurements 

You can view the same in: http://dashboard-1258843151.us-east-1.elb.amazonaws.com/superset/dashboard/1/

**Comment by IanMayo** [comment]
I'd like to request a change, please @nikhilbaby 

For the `measurements_view` dataset, could you use the `time` value from the `States` table, rather than the `created_date`.  The latter is the date when it was added to the database, which is mostly around the same time.  The former is the date the GPS position was actually recorded.

**Comment by nikhilbaby** [comment]
@IanMayo 

View updated as per the requirements:
```
create or replace view measurements_view(id, type, created_date) as
SELECT "Activations".activation_id AS id,
       'Activations'::text         AS type,
       "Activations".created_date
FROM pepys."Activations"
UNION
SELECT "States".state_id AS id,
       'States'::text    AS type,
       "States".time as created_date
FROM pepys."States"
UNION
SELECT "Contacts".contact_id AS id,
       'Contacts'::text      AS type,
       "Contacts".created_date
FROM pepys."Contacts";
```

**Comment by nikhilbaby** [comment]
Do you something else on mind to add to this dashboard. If yes we can discuss about this.

**Comment by IanMayo** [comment]
Thanks. Now I view the SQL I realise we should use the `time` field in all 3 tables, rather than `created_date`.

**Comment by nikhilbaby** [comment]
Updated view
```
create or replace view measurements_view(id, type, created_date) as
SELECT "Activations".activation_id AS id,
       'Activations'::text         AS type,
       "Activations".created_date
FROM pepys."Activations"
UNION
SELECT "States".state_id AS id,
       'States'::text    AS type,
       "States".time as created_date
FROM pepys."States"
UNION
SELECT "Contacts".contact_id AS id,
       'Contacts'::text      AS type,
       time as created_date
FROM pepys."Contacts";

```

There is no time column for `Activations`

**Comment by IanMayo** [comment]
Aah, it's States, Contacts and Comments that we are mostly using.  I don't think we have any activations yet.  These 3 tables all have a `time` field.

**Comment by nikhilbaby** [comment]
Updated as per the requirements.

**Comment by IanMayo** [comment]
Great, done.
