### ISSUE TITLE
Only able to save one field at a time

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#816]
It appears that only one field for a row can be edited at a time.

I'll try to reproduce it.
```
After a few error trials, we sussed out after a few try and errors, that we could edit only one field at a 
time. For example when editing a sensor, we could only change the name to GPS  and save successfully. 
We would then go back for another edit to change the sensor type to Location Satellite. However they 
are still a few that still would not work, and I am unsure why.
```

**Comment by robintw** [comment]
Hmm, I can't seem to reproduce this - I've tried editing multiple fields for a Sensor and it works fine.

Can you ask them if they get an error, or whether it just fails silently?

If they're getting an error about constraints then it could well be that they already have a sensor called `GPS` on that platform - but in that case I can't see how they would be able to change it when they're only changing one field at a time.

**Comment by IanMayo** [comment]
Have asked for example of which two fields wouldn't save.

**Comment by IanMayo** [comment]
Ok.  They have lots of GPS sensors, though some are lower case, and there are two sensor-types: `Location-Satellite` and `Location Satellite`

So, they selected the lower case `gps`, did `Edit values`, then tried to correct the name and sensor-type at the same time.

I was able to do this, as below:
![screencast](https://i.gyazo.com/3b399ad704e178b560a8d23b2bc91c64.gif)

**Comment by robintw** [comment]
Did we get any further information on this @IanMayo? And have they managed to do it successfully since then? If so, we could close this and re-open if they have any further issues.

**Comment by IanMayo** [comment]
No, nothing new on this. Agreed, let's close it.
