### ISSUE TITLE
Create really large Postgres database for testing

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#820]
The users are using Pepys with a Postgres database with millions of rows (around 1.5m last time I heard, but probably more now - and I can't remember if that was just 1.5m States, or 1.5m rows across all tables). We're testing with far smaller databases, which means we're far less likely to run into performance issues.

There are a number of places in the GUI where performance might get slow for large databases - but it's difficult to tell where without having a large database to test it on, and it's difficult to test solutions too.

@IanMayo Can you think of any _reasonably easy_ way that we can get a _large_ database to play with? Ideally it would be a local Postgres database rather than using our remote Postgres instance that we use for testing, as the extra delay with the database being over the internet would make it more difficult to work out what the causes of the slowdowns were.

Do you have, or would you be able to create, synthetic data with millions of States? Ideally with a lot of different Platforms too. If you have the data, then I can import it into a local Postgres database, and then potentially export a database dump and keep that for any developers to use in future when they need a large database to test on.

If it's not easy for you to get hold of, or create, such data then we could create some code to create this ourselves - we could create random Platforms and Sensors, and then create random State entries associated with these - and just repeat until we have enough data.

Thoughts? I definitely think this would be useful - not just for testing the GUI, but for testing the dashboard and other things too.

**Comment by IanMayo** [comment]
I think it's 1.5m rows across all tables, but States are by far the most common data-type.  

I guess the route to the local instance is to do a `pg_dump` of the remote database then `pg_restore` to a local one.  It would be interesting to learn how large the dump file was.

Regarding large database performance:  I'd hope that we either let the database do the work (so only processed/aggregated data comes back down the wire) or page the data a segment at time for genuinely high data volumes.  

By coincidence @arunlal-v is working on a task to create a relatively high volume SQLite database instance #769, to allow SQLite optimisation investigations.  His route is partially through a data-dump then Python script to inject data into SQLite. The above _convolution_ is because of the differing SQL dialects.

**Comment by robintw** [comment]
Do we already have a remote postgres database with that sort of amount of data (millions of rows) in it? If so, then yes, it should be fairly simple to just dump it and restore it locally.

But I was under the impression that we didn't have a very large database, and therefore we'd need to find/generate some data to import to get a large database in the first place?

**Comment by IanMayo** [comment]
Yes, the acugis database is large:
![image](https://user-images.githubusercontent.com/1108513/110962255-ad1a5480-8348-11eb-8a1a-cc098739d258.png)

I can provide access details if you don't have them.

**Comment by robintw** [comment]
I didn't realise we had a database like that - that's great! Could you send me access details via Slack or some other method.

**Comment by robintw** [comment]
All sorted now - I have a copy of that large Pepys database running on my local machine. Thanks!

**Comment by arunlal-v** [comment]
@robintw, Postgis to spatialite export tool development is still in progress, but you should be able to use this [bare bones version](https://github.com/debrief/pepys-import/issues/769#issuecomment-797641471) after plugging in the queries and the db parameters to generate a large spatialie db.

**Comment by IanMayo** [comment]
@robintw - did you produce a dump file along the way? How large was it?  If it's not huge then it may be useful to zip it up & attach it to this issue. It may prove useful one day.

**Comment by IanMayo** [comment]
🤣  - no, it's ok. That's prob too big to be useful.
