### ISSUE TITLE
Add more indexes to the database

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#821]
Some of the recent performance issues that the users have experienced may be helped by adding more indexes to the database. We'd need to investigate which ones are most useful to add, as there is a cost for each index (both in storage space, and in extra time when adding a record).

#820 would really help this, with having a large database to test on.

**Comment by IanMayo** [comment]
I think the logical route to doing this is to find an operation that's running too slowly (a bottleneck), then invite @arunlal-v to investigate optimising the performance to remove that bottleneck via indexes.

**Comment by arunlal-v** [comment]
I'm not quite sure on all the Postgis functions that we use in Debrief/Pepys-Import and I shared a [generic recommendation](https://github.com/debrief/pepys-import/issues/745#issuecomment-783614721) for Postgis related bottlenecks. For other bottlenecks, we should be able to analyze the execution plan and come up with indexes and/or rewritten queries.

**Comment by IanMayo** [comment]
I think I can close this @robintw .  There was a performance problem in loading data into Debrief.  We resolved that through a logic change (it was mistakenly trying to load loads and loads of track data).

**Comment by robintw** [comment]
Sounds good - I'm happy with that. We can always investigate later.
