### ISSUE TITLE
Upgrade to SQLAlchemy 1.4 and prepare for SQLAlchemy 2.0

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#830]
SQLAlchemy 1.4 has just been [released](https://www.sqlalchemy.org/blog/2021/03/15/sqlalchemy-1.4.0-released/). The release announcement says:

> This is the most extensive release for SQLAlchemy in at least ten years, featuring a major rethink of the most prominent APIs in Core and ORM, vastly revised internals, and a wide range of significant new features and capabilities.

Version 1.4 is a stepping stone to the changes that will be introduced in 2.0, where a number of things that are deprecated in 1.4 will be removed entirely. There is a detailed migration guide for [migrating to 1.4](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html), and for [migrating to 2.0](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html).

This will require some fairly extensive changes across the Pepys codebase, but it seems like there are thorough guides on the SQLAlchemy website for doing the relevant changes, and there are 'warnings modes' that can be enabled to give warnings or errors when deprecated functionality is used.

We will need to make these changes sometime: the only question is when? My view is that it would be better to make the changes sooner rather than later - as the longer we leave it, the more 'legacy' API use we'll have built up, and the more work we will have to do to update. However, I'm aware that upgrading libraries we use isn't a feature that the clients will be particularly interested in (although this should also lead to better performance, and allows us to continue receiving security updates). The changes can be made gradually, although having a PR with major changes sitting around for a while will lead to lots of merge conflicts - so possibly we should do it in a few large stages, tackling different categories of warnings/errors/deprecations each time.

What do you think? Where do you think this should come in the list of priorities?

**Comment by IanMayo** [comment]
Thanks @robintw 

My first reaction is to save it for when there is a natural pause in the project - which there almost certainly will be as we come to the end of the current development phase.  We should have finished the current features [*] by then, and you can concentrate on the task.

[*] Maintenance Tools, Tasks/Participations, Status board.

**Comment by robintw** [comment]
This is done, by PRs #954 and #957. There is a separate issue for switching to the new-style query API (#970), but that isn't required for the SQLAlchemy upgrade.
