### ISSUE TITLE
Build date in title bar of Pepys-Admin

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#835]
I may have caused some confusion by reporting bugs on a build that had been superseded.

If we put the build-date in the Pepys title bar it may be a step towards preventing this confusion.

The build-version isn't enough, since in development we frequently have lots of builds between formal releases.

It will also mean users are always quite clear on the version that's in use.

**Comment by robintw** [comment]
We don't actually have a title bar for the GUI apps:
![image](https://user-images.githubusercontent.com/296686/112461422-ce6f3d80-8d57-11eb-9075-f7689f8be21a.png)
Would you like an extra bar put at the top of the screen saying something like `Pepys - Maintain Tasks - Release 2021-03-01 01:02:03`? Or would you prefer some sort of 'About' dialog that could be opened by the user (that would mean it wouldn't take up screen space when it wasn't needed)

**Comment by IanMayo** [comment]
We do have a title bar in MS-Windows:
![image](https://user-images.githubusercontent.com/1108513/112462588-235f8380-8d59-11eb-849d-d520d2051f3b.png)

It's probably a MS-Windows "trick" to change the title. Maybe the build version would have to go into the `install_pepys.bat` script.

**Comment by robintw** [comment]
Ahh ok, I'll investigate that.
