### ISSUE TITLE
Introduce "Exercise" field in "Tasks"

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#836]
We currently organise Tasks by the serial name (something like `J06040`).  But while that is the identifier, there normally is a more descriptive phrase that explains what is happening in it. Something like "NAVCOMEX" or "CASEX 432" or "ADEX ALPHA".

The analysts would like to see both the Serial and the Exercise labels in the wall-board, so we'll need to store/handle both.

We should add the (optional) "Exercise" field to the "Tasks" table, and also allow it to be edited for 3rd level Tasks in the "Tasks and Participations" editor.

Once we have the Alembic transition for the new data type, and we've applied it to PostGres then @arunlal-v  should modify our normalised tasks & participations to include this field.

**Comment by robintw** [comment]
No longer relevant, as the Tasks table doesn't exist - and the new Serial table has this exercise field.
