### ISSUE TITLE
Create pepys_import command-line script

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#84]
#44 says that we want to run a pepys_import batch script which will run a Python script to call the file processor with the current directory as an argument. We need to write that Python script.

**Comment by robintw** [comment]
I could probably have a go at this myself, but it might be quicker for @IanMayo or @BarisSari to put something together as they're more familiar with the parsing API at the moment - and that'd allow me to focus on the deployment.

I've seen some examples in the repo, but I'm not sure how up-to-date notebooks like [this](https://github.com/debrief/pepys-import/blob/develop/examples/notebooks/data_store_sqlite.ipynb) are - as I think I've seen commits that look like they've changed this API recently.

**Comment by BarisSari** [comment]
Hi Robin. Unfortunately, these notebooks are not changed completely and they're not working. I was thinking to change all files in the _examples/_ folder when refactoring is completed.

**Comment by IanMayo** [comment]
@BarisSari  - I don't mind if we delete the notebooks.  We can then re-create them once the API has stabilised.

(yes - it would have saved you some refactoring effort if I'd said this two weeks ago, sorry).

**Comment by IanMayo** [comment]
@robintw - are you aware of a best-practice for where we put both the batch-script and the "top-level" python script?

I guess the batch script could sit in the top-level of the repo, or alternatively in a `bin` sub-folder.  I guess the python `import.py` file could sit in the top level of the `pepys-import` module.
