### ISSUE TITLE
What should go in the Logs table for a row deletion?

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#844]
I've realised that at the moment when rows are deleted from the database, nothing is entered in the Logs table. I don't know if this is intentional or not - the only place we delete things so far is in the Maintenance GUI, and I don't remember having the discussion about what to record in Logs.

Do we want to record something in Logs when we delete something?

If so, what should we record in the different columns of Logs? The columns we have available in Logs to record information are:

- table
- row_id,
- field,
- previous_value,
- change_id

Do we want a single entry just listing the table and the row_id, and then putting the string `DELETED` in the `field` field (it's just a string field, with no foreign keys or anything)?

What do you think @IanMayo?

(This will apply to both deleting items from any table in the Maintenance GUI, and deleting Series/Wargames/Serials/Participants from the Tasks GUI)

**Comment by IanMayo** [comment]
Well spotted.  
The general aim of the Logs/Changes are to be able to reconstruct the data.   To do this, I guess we need to insert a serialised version of the row (series of name:value pairs) in to the `previous_value` field.

How does that sound?

**Comment by arunlal-v** [comment]
That'll also depend on how extensive the data reconstruction should be. There are audit tables that exactly mirror the original tables, with two additional fields ```start date``` and ```end date``` that indicates the period during which that particular version of the record was active. This also provides a mechanism to query historical versions of the same record.

If it's simple reconstruction that we're looking into, then a plain audit table will do.

object_type|object_uuid|object_data
-|-|-
pepys."State"|1e0187ca-9146-0794-62fb-c6f1c69c3dee|{ "uuid": "faa18ef7-6823-33dc-0f16-de6e4b2c02f3", "sensor_id": "50d64387-9f91-4c6f-8933-f4e7b1a7d8ab", "time": "2020-11-15 00:00:00", "created": "2020-11-15 23:59:59", "privacy_id": 30 }

**Comment by robintw** [comment]
Fixed in 4e9fa88 in #833.
