### ISSUE TITLE
Create simple example script that parses a file and adds to database

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#85]
I can't see anything quite like this in the repo at the moment, but it's possible I'm not looking in the right place.

What I'm looking for is a script that will exercise a reasonable chunk of the pepys-import library, by taking a file and importing it to a SQLite database. I need some way to test a deployment of pepys-import, without having to have all of the infrastructure around the formal unit tests set up (eg having pytest and testing.postgresql installed, and so on)

This could be strongly related to #84 - as creating the pepys_import Python script, and providing it with a example file to import, could satisfy this issue.

**Comment by IanMayo** [comment]
Ok, @BarisSari has created the Python file, and I've created a quick batch script.  

The PR was here, but it has now been merged: https://github.com/debrief/pepys-import/pull/86

Note: the script can be _driven_ by:
* navigate to `pepys`
* load into virtual env
* go into `pepys-import`
* type: `python -m pepys_import.import`

You should see the welcome banner, then an indication that it's running an in-memory sqlite database, then it importing zero new records.

Now enter some real data:
* `python -m pepys_import.import --path tests\sample_data\track_files`
You will see it load some data.

Now try to put the data into a permanent file:
* `python -m pepys_import.import --path tests\sample_data\track_files --db pepys.db`

*DB Browser For Sqlite* can be used to view the contents of the Sqlite database file.

Lastly, a MS-Windows batch script has been produced, that will call the above module
* `bin\pepys_import --path tests\sample_data\track_files --db pepys.db`

**Comment by IanMayo** [comment]
@robintw - are you happy that we can close this?

**Comment by robintw** [comment]
Yes, that's fine - all done.
