### ISSUE TITLE
Introduce flag for which serials to plot in timeline

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#854]
The analysts have received the serials for the wargame next month.

For some days there will be more than five serials, though the team will only be analysing/viewing a maximum of 5.  But, they may not know which five until they start analysis - some may not happen, or may not provide any data.

In the future, we may be able to offer improve visualisation of this data, possibly a `gantt` of just the serials (not participations).  So, I don't want to filter the Phase 1 query data by `includeInTimeline`.

To support this we will need: 
* [ ] an `includeInTimeline` boolean flag in `Serials` (default true)
* [ ] a boolean control in `Edit serial` in `Maintain Tasks`
* [ ] return the value of the flag in Phase 1 of timeline query
* [ ] modify flask app to only request data for serials flagged as `includeInTimeline`.

**Comment by arunlal-v** [comment]
>So, I don't want to filter the Phase 1 query data by `includeInTimeline`.

So, we'll continue with start and end time input filters for the Phase 1 query, right?

**Comment by IanMayo** [comment]
> > So, I don't want to filter the Phase 1 query data by `includeInTimeline`.
> 
> So, we'll continue with start and end time input filters for the Phase 1 query, right?

Yes please @arunlal-v

**Comment by robintw** [comment]
An update from a Slack conversation: we're going to use the same format for the field name as we do elsewhere in the project, so it will be `include_in_timeline`.
