### ISSUE TITLE
Quick feedback from Maintain Tasks

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#856]
The analysts were using `Maintain Tasks` on Friday, and this morning provided this feedback:

* [x] Could the serials be displayed in serial.start_time order please?  They're currently in the order they were generated
* [x] Could the participants be displayed in alphabetical order too?  (that's the list of participants for a wargame, and the blue/red lists for a serial)
* [x] The analysts are nervous of mistakenly adding a serial twice, or mis-typing and duplicating the serial number. Could pepys please ensure that serial ids are unique for a wargame

**Comment by robintw** [comment]
Ok.

PR for these changes at #858.
