### ISSUE TITLE
Duplicate serial

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#857]
Issue renamed, to use simpler implementation that wouldn't require database changes.

**Update:**

I've just checked with analysts, and `Duplicate task` would be a satisfactory solution to this issue. I propose we duplicate all fields, but append `Copy xx` at the end of the serial number.  Hopefully there is existing logic to handle the sequential (`Copy 1, Copy 2`etc) values.

If we have chance, it would be good to deliver `Duplicate task` in the near-term since they will be able to take immediate advantage of it.

### Former strategy

Groups of units is not required for May 2021.

In a wargame, a group of ships/platforms could be grouped into a Task Group.    This group of ships will be act in many serials, largely without any changes.

It's currently cumbersome to repeatedly add them one-by-one to the serials they take part in.

We need a further discovery stage on this to determine if the composition of a task group changes, do we need to modify the serials?  

One solution would be for Wargame Participants to have a `TaskGroup` field. This _could_ be free text.  When we add a participant to a serial, the listing offers unique partiicpants, and the names of any declared task groups.

Or we could swap the free text for an optional entry from the Task Group Names table.

An alternate strategy that could solve the re-typing issue could be a `Duplicate task` button.

**Comment by robintw** [comment]
Fixed
