### ISSUE TITLE
Potential issue with spatial query

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#864]
I've just been contacted by some analysts.

They're using PGAdmin to query a PostGres instance of Pepys.

They're providing filters for:
* sensor
* start/end date
* spatial coverage using ST_Contains

Without spatial coverage they get 55k state values.
With spatial coverage they get 53 values.

This is a dataset they've used before, and it used to return all 55k values.

They wonder if something has changed in spatial querying.

Could we do some simple investigation to see if this is reproducible?

I suggest you work on the track titled `SPLENDID`.  It's spatial coverage goes from:
* TL: 52N, 6W
* BR: 51N, 5W

**Comment by arunlal-v** [comment]
>Without spatial coverage they get 55k state values.
>With spatial coverage they get 53 values.

This sounds right. This is how filters work :)



>This is a dataset they've used before, and it used to return all 55k values.
>Could we do some simple investigation to see if this is reproducible?

Rather than we trying to reproduce the issue in our DB, it'll be better if we try and analyze the issue in their own system(s). I understand that client systems are off-limits to us and handle very sensitive data, but at the minimum, if we could get the *dubious query* here with the same/obfuscated filter values, then I could come up with  a series of queries that they can execute to debug this issue further.

**Comment by IanMayo** [comment]
Yes, we're waiting for a copy of the query.

**Comment by IanMayo** [comment]
@arunlal-v - here is a copy of the query in use.

Note: it's not from our database instance, so the serial-id values won't work for `tracstor`.

```
SELECT state_id,time,sensor_id,elevation,heading,course,speed,source_id,privacy_id,remarks,created_date,ST_ASTEXT(location) FROM pepys."States" 
WHERE ((time >= '2020-10-06 08:00:00') AND (time <= '2020-10-08 08:00:00')) AND 
ST_Contains(ST_GeomFromText('MULTIPOLYGON(((-0.705798312819094 58.7856725333037,-0.705798312819094 58.8544961007414,-0.609457308574932 58.8544961007414,-0.609457308574932 58.7856725333037,-0.705798312819094 58.7856725333037)))', 4326), pepys."States".location) 
AND sensor_id IN ('564cf94f-50ce-47ca-875a-b952d4c09a1f', 'f2aa6581-967d-4ae7-b41d-ae86e5935bda', 'a7d451d4-f2ff-4fdb-b2ed-1f6cf24718fd', '4d1299cc-607a-4dd2-9d9c-b8c3f7126be2', '0337db9d-deaa-4db4-978a-c0a2c9da5c51', 'cafb9f03-ef2a-4ad3-ab49-0ebef73b8652', 
'c8246bcc-1f2b-4db6-b66d-1225c7cfdff4', '6c44dce9-24a9-40a2-900b-0d47f94fd740', '1354a4b3-1e9d-42c9-89e3-46fc2d728d82', '058f9b4b-9892-4c41-b895-9c3f9c0bb9a7', '6b923165-aecb-426e-aa3d-d750f2b19faf', 'c4260792-60df-4da3-8dfe-4e7162c0387a', '789d220c-feb7-49bc-b840-73fc46378424', 
'fcb0a7a1-e62f-4879-80f1-551d9308b86e', '9203e5d1-f479-4d23-b358-0f04670abf56') 
ORDER BY time ASC;

```

**Comment by robintw** [comment]
That's a strange error - it seems to be saying that `"pepys.States"` doesn't exist, but the query has `pepys."States"` in it, which is the right quotation for the table (I think...)

Also, the place in the SQL string that the error actually seems to be pointing to is the ST_ASTEXT function - so I'm wondering whether there is some sort of PostGIS issue here?

**Comment by IanMayo** [comment]
Confession from IT Support.  They ran query against wrong database. They ran against Pepys, and got 53 records.

**Comment by arunlal-v** [comment]
@IanMayo, can we get the below diagnostic query executed at the client end and results returned?

```SQL
with sensor_ids(sensor_id) as (values
('564cf94f-50ce-47ca-875a-b952d4c09a1f'),
('f2aa6581-967d-4ae7-b41d-ae86e5935bda'),
('a7d451d4-f2ff-4fdb-b2ed-1f6cf24718fd'),
('4d1299cc-607a-4dd2-9d9c-b8c3f7126be2'),
('0337db9d-deaa-4db4-978a-c0a2c9da5c51'),
('cafb9f03-ef2a-4ad3-ab49-0ebef73b8652'),
('c8246bcc-1f2b-4db6-b66d-1225c7cfdff4'),
('6c44dce9-24a9-40a2-900b-0d47f94fd740'),
('1354a4b3-1e9d-42c9-89e3-46fc2d728d82'),
('058f9b4b-9892-4c41-b895-9c3f9c0bb9a7'),
('6b923165-aecb-426e-aa3d-d750f2b19faf'),
('c4260792-60df-4da3-8dfe-4e7162c0387a'),
('789d220c-feb7-49bc-b840-73fc46378424'),
('fcb0a7a1-e62f-4879-80f1-551d9308b86e'),
('9203e5d1-f479-4d23-b358-0f04670abf56'))
select
	'ALL' stat,
	count(1)::text
from
	pepys."States"
union all
select
	'JUST TIME',
	count(1)::text
from
	pepys."States"
where
	((time >= '2020-10-06 08:00:00')
	and (time <= '2020-10-08 08:00:00'))
union all
select
	'JUST SENSORID',
	count(1)::text
from
	pepys."States"
where
	sensor_id in (
	select
		sensor_id::uuid
	from
		sensor_ids)
union all
select
	'SENSORID TIME filters',
	count(1)::text
from
	pepys."States"
where
	((time >= '2020-10-06 08:00:00')
	and (time <= '2020-10-08 08:00:00'))
	and sensor_id in (
	select
		sensor_id::uuid
	from
		sensor_ids)
union all
select
	'ALL CRITERIA',
	count(1)::text
from
	pepys."States"
where
	((time >= '2020-10-06 08:00:00')
	and (time <= '2020-10-08 08:00:00'))
	and sensor_id in (
	select
		sensor_id::uuid
	from
		sensor_ids)
	and ST_Contains(ST_GeomFromText('MULTIPOLYGON(((-0.705798312819094 58.7856725333037,-0.705798312819094 58.8544961007414,-0.609457308574932 58.8544961007414,-0.609457308574932 58.7856725333037,-0.705798312819094 58.7856725333037)))',
	4326),
	pepys."States".location)
union all
select
	'NULL CHECKS',
	count(1)::text
from
	pepys."States"
where
	((time >= '2020-10-06 08:00:00')
	and (time <= '2020-10-08 08:00:00'))
	and sensor_id in (
	select
		sensor_id::uuid
	from
		sensor_ids)
	and
	location is null
union all
select
	'ST CONDITION CHECK: ' ||(ST_Contains(ST_GeomFromText('MULTIPOLYGON(((-0.705798312819094 58.7856725333037,-0.705798312819094 58.8544961007414,-0.609457308574932 58.8544961007414,-0.609457308574932 58.7856725333037,-0.705798312819094 58.7856725333037)))',
	4326),
	pepys."States".location))::text,
	count(1)::text
from
	pepys."States"
where
	((time >= '2020-10-06 08:00:00')
	and (time <= '2020-10-08 08:00:00'))
	and sensor_id in (
	select
		sensor_id::uuid
	from
		sensor_ids)
group by
	'ST CONDITION CHECK: ' ||(ST_Contains(ST_GeomFromText('MULTIPOLYGON(((-0.705798312819094 58.7856725333037,-0.705798312819094 58.8544961007414,-0.609457308574932 58.8544961007414,-0.609457308574932 58.7856725333037,-0.705798312819094 58.7856725333037)))',
	4326),
	pepys."States".location))::text
union all
select
	'PostGis version: ', postgis_version()
union all
select
	'Postgres version: ', version();
```

**Comment by arunlal-v** [comment]
I'll analyze further on the MULTIPOLYGON object that they have defined.

**Comment by IanMayo** [comment]
Sure, but not until Tuesday.

**Comment by IanMayo** [comment]
@arunlal-v - sadly it is quite likely that the users will not be happy giving the results of the query to us.

Particularly, they will not be willing to provide any values from matching data in their instance of Pepys.

But, I expect they would be willing to pass on results that just include metadata, such as counts of records, or information that was originally provided in the query they provided (such as location or serial-ids).

**Comment by arunlal-v** [comment]
The query returns metadata and counts only. This is the output of the query from our tracstor  DB.

ALL	1691980
JUST TIME	0
JUST SENSORID	0
SENSORID TIME filters	0
ALL CRITERIA	0
NULL CHECKS	0
PostGis version: 	2.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
Postgres version: 	PostgreSQL 11.7 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

**Comment by IanMayo** [comment]
Query results below, @arunlal-v .   Significantly, I _think_ we can see the step when 53k results drops down to 53.

stat | count
-- | --
ALL | 1974644
JUST TIME | 80890
JUST SENSORID | 119892
SENSORID TIME filters | 53765
ALL CRITERIA | 53
NULL CHECKS | 0
ST CONDITION CHECK: false | 53712
ST CONDITION CHECK: true | 53
PostGis version: | 3.0 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
Postgres version: | PostgreSQL 12.2, compiled by Visual C++ build 1914, 64-bit


```

**Comment by arunlal-v** [comment]
@IanMayo, as discussed, here's the query to find the bounding box for all the **pepys."States".location** involved in the query.

```SQL
with sensor_ids(sensor_id) as (values
('564cf94f-50ce-47ca-875a-b952d4c09a1f'),
('f2aa6581-967d-4ae7-b41d-ae86e5935bda'),
('a7d451d4-f2ff-4fdb-b2ed-1f6cf24718fd'),
('4d1299cc-607a-4dd2-9d9c-b8c3f7126be2'),
('0337db9d-deaa-4db4-978a-c0a2c9da5c51'),
('cafb9f03-ef2a-4ad3-ab49-0ebef73b8652'),
('c8246bcc-1f2b-4db6-b66d-1225c7cfdff4'),
('6c44dce9-24a9-40a2-900b-0d47f94fd740'),
('1354a4b3-1e9d-42c9-89e3-46fc2d728d82'),
('058f9b4b-9892-4c41-b895-9c3f9c0bb9a7'),
('6b923165-aecb-426e-aa3d-d750f2b19faf'),
('c4260792-60df-4da3-8dfe-4e7162c0387a'),
('789d220c-feb7-49bc-b840-73fc46378424'),
('fcb0a7a1-e62f-4879-80f1-551d9308b86e'),
('9203e5d1-f479-4d23-b358-0f04670abf56'))
select
	'Bounding Box:' stat,
	st_envelope(st_extent(location)) stat_value
from
	pepys."States"
where
	((time >= '2020-10-06 08:00:00')
	and (time <= '2020-10-08 08:00:00'))
	and sensor_id in (
	select
		sensor_id::uuid
	from
		sensor_ids);
```

**Comment by arunlal-v** [comment]
@IanMayo, any updates from analysts?

**Comment by IanMayo** [comment]
nope, sorry.

**Comment by robintw** [comment]
What's the current state of this @IanMayo? Did we ever get a response from the analysts, or shall we close this?

**Comment by IanMayo** [comment]
Yes, I think we should close it.  Analysts have been happy with search results in months since this was first reported.
