### ISSUE TITLE
Alembic Migration failing

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#866]
The users were invited to download/install this release:
https://github.com/debrief/pepys-import/releases/tag/maintain_tasks

They got this error during migration.  In the past we had issues with migration revisions, but we tended to catch them in review.  Is that what happened here?

```
Result: Error.

(pepys-admin) 5
Your database schema is going to be updated. Are you sure to continue? (y/N) y
Alembic migration command running, see output below.
len(table_names)=42
Please run database migration to bring tables up to date.
Database tables are going to be created by Alembic.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Exception details: Requested revision 00116b58f22e overlaps with other requested revisions ff66e16c21ef

ERROR: Alembic error when migrating the database!
```

**Comment by robintw** [comment]
Oh goodness, this is always a difficult thing to debug - particularly remotely with the clients.

This particular error message tends to mean that the database has two entries in the `alembic_version` table telling it what version it is currently in, or that we have multiple HEADs in the alembic version tree. I can't see that the latter is the case - though I'm doing some tests to 'prove' it. So I'm guessing the alembic version table has got two entries in it.

Could you ask them to send the following information:

1. The output of the Alembic bit of the Status output (option 2 in Pepys Admin). It should look like this:
```
## Database Version
len(table_names)=40
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Current revision(s) for postgresql+psycopg2://postgres:XXXXX@localhost:5432/pepys_test1:
Rev: ff4215cb3d30 (head)
Parent: f17f01e2f2c5
Path: /Users/robin/Documents/IanMayo/pepys-import/migrations/postgres_versions/2021-04-26_ff4215cb3d30_add_unique_constraint_for_serials.py

    Add unique constraint for Serials
    
    Revision ID: ff4215cb3d30
    Revises: f17f01e2f2c5
    Create Date: 2021-04-26 15:50:41.368518+00:00
```

2. The contents of the `alembic_version` table - they can get this with `SELECT * from "pepys".alembic_version;` either in something like pgAdmin or in Pepys Admin with option 6 (View Data) then option 3 (Run SQL).

**Comment by robintw** [comment]
Right, I've double-checked that there aren't multiple HEADs in the alembic version tree, and there aren't.

[StackOverflow](https://stackoverflow.com/questions/42424320/how-do-i-fix-alembics-requested-revision-overlaps-with-other-requested-revisio) confirms that the issue is that the `alembic_version` table has multiple entries. I'm not sure how that happened - maybe they accidentally ran 'initialise' on the database again sometime (perhaps to fix another issue?) and it added an extra entry.

Once they get back to us and tell us what the contents of the `alembic_version` table are, then we should be able to tell them which row to delete - it should just be the older one. I _suspect_ (but am not 100% sure - hence wanting to wait to hear from them) that the two entries will be `00116b58f22e` and `ff66e16c21ef`, and we will need to get them to delete `00116b58f22e`.

**Comment by IanMayo** [comment]
Sorted, by user rep deleting incorrect alembic table entry.

@robintw  - would you mind documenting in here what you think the issue was, based on the information/diagnostics we received?

**Comment by robintw** [comment]
Of course - the information here could be useful for future.

Somehow the users had ended up with two rows in their `alembic_version` table. Normally this table has a single row giving the current revision of the database. It could be possible to end up with two rows by running the `data_store.initialise()` function on a database that has already been initialised - and potentially running this with a different version of Pepys.

I don't quite understand how they ended up with quite such an old revision (`00116b58f22e` was from December 2020) being put into that table - maybe they used a very old version of Pepys at one point, which put it there.

Once there are two entries in the `alembic_version` table, alembic doesn't know what version of the database they have, and therefore refuses to run a migration. I admit that the error message from alembic could be more helpful (maybe I'll even submit a PR to improve it sometime).

The solution to this for future is to stop us creating a new row in the `alembic_version` table if there is already one there - and give an error instead. I'm working on a PR for that.
