### ISSUE TITLE
Minor feature: editing Serial.includeInTimeline from maintainer tools

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#868]
I wanted to remove a serial from the timeline. I happened to be in maintainer-tools at the time.

I tried to make the edit, but couldn't produce a value that Pepys-Admin interpreted as a boolean value.  Well, I tried `false` and `False`.

Ideally we'd have a tick-box for edit, but if not then we need to allow true/false in a range of cases, I guess.

**Comment by robintw** [comment]
PR for this now available at #869.

There were actually a surprising number of issues trying to implement this with a checkbox - I've described them in the Developer Notes of that PR, and explained why I've gone for the simple option of using a string.
