### ISSUE TITLE
Options table

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#871]
We have at least two user-configurable options for timelins:
* message of the day (`MessageOfTheDay`)
* timeline update interval (`TimelineUpdateSecs`)

One way of handling this is a ConfigOptions table in Pepys - which contains name:value pairs

Users would use pepys-admin to update the values.

This task covers:
* creation of table, with initial values
* verification of being able to edit table in Pepys-Admn

Hmm, I _guess_ this table would fit in the metadata section.

The data would be used here: https://github.com/debrief/pepys-timeline/issues/24

The data will be retrieved with a query of `select * from ConfigOptions`

Initial table:
| ConfigOptionId | Name | Description | Value |
|-|-|-|-|
| 1234-aaa-123 | MessageOfTheDay | Custom message to display in Timeline header | Today's analysis manager is Greta |
| 4321-zzz-321 | TimelineRefreshSecs | Interval between Timeline/Dashboard refresh (Secs) | 60 |

**Comment by arunlal-v** [comment]
```MessageOfTheDay``` is a unique functionality. So, I believe it deserves a table of it's own. And it can grow on its own.

Configurations like ```TimelineUpdateSecs```  can be handled in a separate table. A widely used design is the configuration tables. It's as follows.

#### Table: Configuration Table

configuration_uuid|configuration
-|-
1|SERIAL_STATUS
2|MISC_CONFIG

#### Table: Configuration Values

configuration_val_uuid|configuration_uuid|config_key|value
-|-|-|-
1|1|ONG|Ongoing Serial
2|1|SCH|Scheduled Serial
3|1|CCL|Concluded Serial
4|2|REFRESH_SCH_SEC|5
5|2|QUERY_SCH_SEC|10
6|2|TIMELINE_SCH|15

The SERIAL_STATUS can be used as a drop down generator.

**Comment by IanMayo** [comment]
Thanks @arunlal-v  - but right now I don't think or requirement justifies this level of complexity.

With the original table users can maintain the data themselves, without needing to understand the information architecture.

If/when there is more complexity in number/type of configuration details then we'll consider the `Configuration Table`.
