### ISSUE TITLE
Issue updating SQLite database

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#873]
This is a fairly unimportant issue,  of low priority.  It's worth considering in case it avoids some future issue.

I've entered Pepys-Admin in training mode.  I've said I don't want to reset the training database.

Then I've asked for a migration.

Then I get this issue:
```
(pepys-admin) 5
Your database schema is going to be updated. Are you sure to continue? (y/N) y
Alembic migration command running, see output below.
len(table_names)=78
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Exception details: Requested revision 4bdeb14c63b5 overlaps with other requested revisions a8c6dfa05c6d

ERROR: Alembic error when migrating the database!
---------------------------------------------------------
```

**Comment by robintw** [comment]
Could you attach your training database? It seems like that database has ended up with the same issue that the users had with two entries in the alembic_version table.

**Comment by IanMayo** [comment]
[Uploading pepys_training_database.db.zip…]()
