### ISSUE TITLE
Highlight on new data added

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#885]
It would help analysts track what is happening if we show a highlight for coverage that has been added within (for example) the last 5 minutes.

Yellow is the _Standard_ shade for this.  I _guess_ we'd introduce a new category of data for `visavail`.

We could _drive_ this in one of these ways:
* SQL query checks `created date-time` against current time, and includes some `new` flag
* Python compares incoming data to current data, and adds highlight if there is something new.  A simple array length check for each participant will probably be enough
* Perform above test in JS.

**Comment by krsnik93** [comment]
@IanMayo @arunlal-v hello, I would like to start working on this issue. There is a `resp_end_time` for each coverage chunk that is returned from dashboard_stats query. Is it just a matter of checking whether the difference between *now* and this `resp_end_time` is less than some constant timedelta that we choose? And assigning a new category to the subset of chunks that fulfill this condition and coloring them with yellow?

**Comment by IanMayo** [comment]
> start working on this
Great.

> resp_end_time
Sadly the data may have been captured yesterday.  We're highlighting data that has just been loaded, not which has just been recorded.

We need the `created` value for the measurement. I _hope_ that's in the data.

**Comment by arunlal-v** [comment]
> @IanMayo @arunlal-v hello, I would like to start working on this issue. There is a `resp_end_time` for each coverage chunk that is returned from dashboard_stats query. Is it just a matter of checking whether the difference between _now_ and this `resp_end_time` is less than some constant timedelta that we choose? And assigning a new category to the subset of chunks that fulfill this condition and coloring them with yellow?

@krsnik93, sorry about the belated reply. As @IanMayo pointed out, this ```resp_end_time``` is just the end time of the coverage, and doesn't indicate anything on when this particular record was loaded into Pepys database. Since we're concerned only about **New Coverage Blocks**, it'll be easier to find the areas of overlap between any previous **Gap** blocks and new **Coverage** blocks, and highlight these intersections as a new category as you mentioned.

@IanMayo, I believe ```created``` field provides only limited value and it'll need additional processing at the UI layer to identify the new **Coverage** added.

**Comment by IanMayo** [comment]
> @IanMayo, I believe created field provides only limited value and it'll need additional processing at the UI layer to identify the new Coverage added.

Yes, additional processing will be required in the UI layer (maybe the Python layer). But, nothing can happen until we have the `created` date.

**Comment by arunlal-v** [comment]
As discussed, we'll be needing the ```created``` field to enable users to identify blocks loaded in the last 15 minutes (or any other configurable amount of time). This development item will be tracked using task #920

**Comment by IanMayo** [comment]
Note for when implementing this.  Here is a sample of how the `created` field is present for periods of coverage, but empty for gaps:
```
{
    "dashboard_stats": [
        {
            "resp_created": null,
            "resp_end_time": "Fri, 27 Apr 2012 17:00:00 GMT",
            "resp_platform_id": "064b0735-43f5-46e5-ad01-85f91855c5b4",
            "resp_range_type": "G",
            "resp_serial_id": "S04310",
            "resp_start_time": "Fri, 27 Apr 2012 15:00:00 GMT"
        },
        {
            "resp_created": null,
            "resp_end_time": "Fri, 27 Apr 2012 15:29:38 GMT",
            "resp_platform_id": "1332e939-951d-43ae-b28a-4085f04099d8",
            "resp_range_type": "G",
            "resp_serial_id": "S04310",
            "resp_start_time": "Fri, 27 Apr 2012 15:00:00 GMT"
        },
        {
            "resp_created": "Thu, 09 Sep 2021 15:58:03 GMT",
            "resp_end_time": "Fri, 27 Apr 2012 15:33:38 GMT",
            "resp_platform_id": "1332e939-951d-43ae-b28a-4085f04099d8",
            "resp_range_type": "C",
            "resp_serial_id": "S04310",
            "resp_start_time": "Fri, 27 Apr 2012 15:29:38 GMT"
        },
        {
            "resp_created": null,
            "resp_end_time": "Fri, 27 Apr 2012 17:00:00 GMT",
            "resp_platform_id": "1332e939-951d-43ae-b28a-4085f04099d8",
            "resp_range_type": "G",
            "resp_serial_id": "S04310",
            "resp_start_time": "Fri, 27 Apr 2012 15:33:38 GMT"
        }
    ]
}
```

**Comment by IanMayo** [comment]
Done.
