### ISSUE TITLE
Robustly handle timeline with SQLite database

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#893]
We've been testing the timeline against PostGres.

Due to our dependency on complex SQL trickery, we're only expecting to support the timeline on PostGres.

So, we should give an explanatory error message if a user tries to open Status Wallboard when connected to SQlite.

**Comment by arunlal-v** [comment]
Json is the only major Postgres specific feature that is being used in the dashboard query. We've workarounds for the all other features that we're using. Even json is supported by a [standard extension](https://www.sqlite.org/json1.html)

Even if json is not supported, we should be able to port this feature to SQLite based installations, if required.
