### ISSUE TITLE
Timeline diagnostics

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#897]
Connectivity for the deployed instance should be fairly solid, and not subject to change.

But, it would help their diagnostics if we did some reporting via the timeline UI, just in case something does go wrong.  Diagnostics could also be useful during development, when things may be a bit more flaky.

I suggest that the `timeline` web-page report these problems:
1. backend not running (REST queries unresponsive)
2. backend running, but database name, role, password or port not set
3. backend running, able to connect, but other database error
4. backend running, able to connect, no serials for specified date period

I _think_ that 1 & 4 can be done purely in JS.  I think 2 & 3 require some level of interaction with Python.  Maybe the `config` endpoint could return some error messages in response to 2 & 3.

**Comment by krsnik93** [comment]
@IanMayo do you think using toasts as here: https://getbootstrap.com/docs/4.3/components/toasts/ would be ok as a temporary popup display until user dismisses them, or did you have in mind a more permanent space where this info is displayed all the time?

**Comment by IanMayo** [comment]
Hello @krsnik93 - I think they're all `catastrophic` failures. So, I think it would be something more permanent - replacing the central body of the page (where the serials would be)

**Comment by IanMayo** [comment]
Hello @krsnik93 - the users still haven't _gone live_ with the timeline view.

The first installation is a time when the error/reporting & feedback could be of great value.  So, I think that right now this issue would bring most value. It would be great if it could be implemented over the weekend.

I guess you'll have to use some mangled login ids, or SQL queries in order to trigger the errors you're looking for.

If you need some database admin support then just ask - though be warned I'm away for the weekend, and response times may be slower.

**Comment by krsnik93** [comment]
@IanMayo Sorry, I neglected this issue. Working on it right now.
