### ISSUE TITLE
Configure database connection from environment variables

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#919]
The database connection parameters used by Pepys are stored in a `.ini` file.

The location of the `.ini` file is specified in an environment variable, or as a command line parameter.

The preferred way of handling sensitive data in Heroku is to configure them as Heroku environment variables.  This would let us specify the location of the `.ini` file - but we still won't have the `.ini` file in the repo.

I _think_ the tidy solution is for `pepys-admin` to be able to retrieve the database connection parameters from environment variables.  Hmm, or as command-line options.  With support for database connection params from command-line-options it would be possible to create a new startup script that inlines the environment variables.

**Comment by krsnik93** [comment]
@IanMayo I think the changes could be added here: https://github.com/debrief/pepys-import/blob/dee24710fad5ffcbf82adc1daec2ebaa7791e8e8/config.py#L31 by adding fallback `os.environ.get`, for example:
```
DB_USERNAME = config.get("database", "db_username", fallback=os.environ.get("DB_USERNAME", ""))
```

**Comment by krsnik93** [comment]
This would result in the following order:

1. looking up the config file
2. looking up the env var
3. defaulting to "" or something else

**Comment by krsnik93** [comment]
Alternative could be leveraging https://pypi.org/project/python-dotenv/ and https://github.com/xavdid/heroku-config

**Comment by IanMayo** [comment]
Thanks for the alternative solutions, but the `environ.get()` solution is a neat (and dicrete) fix, thanks.

Do you have an opinion on this @robintw ?

**Comment by IanMayo** [comment]
Closing this.  As @robintw indicated, we already handle this.

A Heroku config problem was giving the illusion that we weren't able to handle the config properly.

![image](https://user-images.githubusercontent.com/1108513/119035019-03d68700-b9a7-11eb-9545-461bea8bb549.png)
