### ISSUE TITLE
Log database migrations

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#924]
The client postgres database is in an inconsistent state, potentially through a failed database migration (#923)

The clients conduct the migrations.  Since we've experienced Alembic migration issues before, I think we need to provide more support to this process.

From the versions recorded in #923 the migrations are 4-5 steps apart, suggesting a migration started but didn't complete (I may be quite wrong on that).

I welcome suggestions from @robintw on this.  I can think of these:
* log migrations to a text file.   _If_ we have migration issues, the log-file can be inspected.  Hmm, if we ensure it doesn't contain database contents, the clients may be able to forward the log to us. I guess it would be useful to capture:
    * URL of database being updated
    * migration id
    * date/time
    * success/failure
    * current user-name
* more clear messaging on the progress of a migration.  Hmm, color-coding the text in green/red as each migration is performed?

**Comment by IanMayo** [comment]
I expect to be installing a new release tomorrow (or Friday).  

This may be an opportunity to test logging migration steps.   Maybe a `log` folder under `migrations`.  Aah, we won't build up a series of migrations, since each new release is a new `Pepys` folder.  So, we'll typically only have one file in there. But, we will have a predictable location for the migration.

**Comment by robintw** [comment]
The migrations are all done by just calling the alembic code that does migrations - we don't have a loop through the migrations in our code where we could easily put some print statements, we literally just call:

```
command.upgrade(self.cfg, "head")
```
where `command` is an Alembic object, which does it all for us.

I think it would be quite difficult (and not necessarily possible?) to hook into alembic to get extra output for each migration that is run. The output of the command looks like:

```
Alembic migration command running, see output below.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 563e11b30785 -> bfb29dfcef94, Update dashboard stored procedures
```

(with extra rows on the end for any other migrations that are run)

We could probably capture that output and write it to a file in a `log` directory too - then the users would have a single file they could send us. However, it won't have any more content than would be printed out on the screen, so if they're going to have difficult transferring files between networks, then it won't be particularly useful.

What do you think?

**Comment by IanMayo** [comment]
My _fear_ is of the migration failing, but the user(s) not recognising it had failed.  The log-file would have the details on what had succeeded/failed, but also the useful information on who had performed the migration and when it happened.

We _Could_ log it to a database table, but I think it's more robust to do it to file - particularly since it's database changes that we're logging.

**Comment by robintw** [comment]
Ok, I'll look into what we can get done - as you want to do a release soon, I'll prioritise this for this afternoon.
