### ISSUE TITLE
Create platform icons for dashboard - plus nice fallback

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#936]
## 🐞 Overview
The dashboard displays an icon for each platform. When I started using the dashboard today, it couldn't find the relevant icon for the platform type (`Tug`), so it displayed an error. I temporarily fixed this by forcing all icons to be the one that is currently present (called `Warship.svg`).

We should create an icon for each of the default platform types (listed below), plus alter the code to use a fallback icon (a ? maybe...) if it can't find an icon.
```
Naval - aircraft
Naval - frigate
Naval - auxiliary
Naval - destroyer
Naval - survey
Naval - minesweeper
Naval - patrol
Naval - aircraft carrier
Naval - submarine
Naval - miscellaneous
Merchant
Tug
Tanker
Law Enforcement
Pleasure Craft
Search and Rescue
Fishing Vessel
Passenger/Ferry
High Speed Craft
```

The icons for these need to be in SVG format, and be placed in `pepys_timeline/static/image` with _exactly_ the same names as the platform types listed above - eg `Naval - submarine.svg`.

## 🔗 Feature
#602

## 🔢 Acceptance criteria
Correct icons display in the dashboard, even when a platform type without an icon is used.

**Comment by IanMayo** [comment]
The platform-types they're using have matured.  I'll get a copy, and update `tracstor` with it. We can use that for our icon shopping list.

**Comment by IanMayo** [comment]
Here is the up-to-date list of platform types:

```
Attack_Craft
Fishing Vessel
High Speed Craft
Law Enforcement
Medical
Merchant
Naval - aircraft carrier
Naval - amphib
Naval - auxiliary
Naval - destroyer
Naval - ExCon
Naval - fixed wing
Naval - frigate
Naval - minesweeper
Naval - miscellaneous
Naval - patrol
Naval - rotary wing
Naval - submarine
Naval - survey
Naval/Military
Passenger/Ferry
Pleasure Craft
Search and Rescue
Tanker
Tug
```

**Comment by IanMayo** [comment]
Aah, we need to make some code changes to reflect these updates.

The `defaults-resolver` should use `Naval - frigate` rather than `Warship`.
Where we use `Warship` in unit tests we should also switch to `Naval - frigate`.

**Comment by IanMayo** [comment]
Aah, we also need to update the `PlatformTypes` in `platform_types.csv`. I'll do that.

**Comment by robintw** [comment]
@IanMayo Does the PR that closed this issue include a fallback icon for an unknown platform type? I couldn't see it in that PR's code, but it might have already been implemented elsewhere.

**Comment by IanMayo** [comment]
Thanks for chasing that up @robintw .  No, it's my preference to use the "missing icon" image as a prompt to get the analysts to specify a Platform-Type for the platform in Pepys-Admin.
