### ISSUE TITLE
3.1.2 Implement initial import tests

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#94]
We're developing a set of import tests in #93 

We need to both implement the tests, and devise an extensible framework for running the tests.

This implementation is detailed here: https://docs.google.com/document/d/1Wjf2XUOMXBsPavzaH9yHf50h4kLSSNXmi5AXxRD9Tr4/edit#heading=h.cfx6v5jgl5es

The strategic approach taken is also being considered here: https://docs.google.com/drawings/d/1JHkjhMw4YRgET8F4u3BSeo-tc4n8kPQ0YnuGEH2rTRM/edit

Ian would like the parsers to be as _dumb_ as possible, keeping as much functionality as possible in our tested, supported processing library (and similarly minimising the volume of code that the data scientists maintain).

So, for this reason Ian would like the test-suite to be run in `file_processor.py`.  An issue with this, is that different parsers ask for different levels of testing.  So, if multiple parsers handle a file, we may be running different levels of testing on the data that's sitting in "temporary storage" before being pushed to the database.

It _looks like_ the relevant place to do the testing is when a parser returns control to file_processor. Then file_processor could run the relevant level of testing against the records read in by that parser.

This would mean we have to do something like:
1.  capture `measurements.size()` before running a parser, then run the tests from that row to the end of measurements.
2. after running tests, submit those measurements to the database - which empties the `measurements` array
3. store the measurements for each parser into a hashmap indexed by the parser, then run all tests at the end, before submitting.

_Maybe_ the strategy should be led by what happens if there's a failure.  We can't submit just the records from one parser, since if the tests for a subsequent parser fail, the analyst will fix the file and resubmit it, and the records from the first parser would all be submitted to the database again.  Hmm, so I think we should run all of the parsers, and all of the tests before we fail - then we can give the analyst a full to-do list of what needs fixing.

**Comment by robintw** [comment]
Yes I agree that this needs to be led by what we do with a failure. This is quite a long comment, with some of my thoughts from pondering this tonight.

In simplistic terms, to answer your direct question, I think we should do the following:

1. We run all parsers on all data files first.

2. Then we run all tests on all the measurements, making sure we keep track of which measurements came from which parser operating on which file.

3. We then submit any measurements from a file where _all_ of the tests for _all_ of the parsers that worked on that file have passed.

4. For each file that has _any_ failures, we list the failures for each separate parser for that file, and ask the user what they want to do (ignore failures, or allow the user to fix and resubmit the file).

Interestingly, I think this links quite considerably with one of the points I raised in #104. We have two sorts of errors we need to keep track of:

1. Parsing errors - such as 'we can't parse this string into a numerical value' or 'the date isn't a valid date'

2. Validation errors - such as 'this location/speed makes no sense given the last location/speed'

I think these should probably all be treated in a similar way, as the end result of them all is the same: the user will have to either choose to accept (ignore) them, or go back and edit the file and reimport. I think we should come up with one solution that will work for both of these use cases.

At the moment the parsing errors are simply `print()`ed to the console and we just continue on to the next line/XML element of the file. This isn't ideal as there is a problem as to what the user should do once they notice these errors: they could fix the file, but reimporting would then duplicate the measurements. It also makes it rather difficult to test that parsers produce errors in the correct places for malformed files (as noted in #104). Exactly the same applies to the validation errors.

In terms of how we do this: we could keep an `errors` list each entry of which is a dict/object that records what the error was, where it was, whether it occurred during parsing or during validation, what parser was being used etc. We'd come up with a clean way of allowing parsers to add entries to this list when there was a parsing error, and the validators would also add to this list when validating.

What we actually do with this list once we've got it is the harder part - and will require some UI design. The simplest case is to just print out the list in a nice way, and then let the user decide whether to go ahead and import the whole lot or not. More complex would be to allow the user to ignore certain specific errors, or import all the measurements that came from certain files with certain parsers. A lot of the specific design for this will depend on what exactly the clients want.

A slightly related point: we keep track of data-files in the database, but I don't believe we keep track of which parsers have been used to import those datafiles? Is that worth keeping somewhere - that would allow more insight into exactly where data came from, so we could do things like warn users if they are going to reimport data from the same datafile and parser combination, or delete all the data that came from a specific parser and specific datafile if we realised the parser had major errors. This would require altering the database design a bit though.

I hope that mostly made sense and is useful - I'm happy to discuss more next week.

**Comment by IanMayo** [comment]
>  I don't believe we keep track of which parsers have been used to import those datafiles
The schema includes the `Changes` and `Log` table.  The `Log` table will record the creation of each new row, with a row in the `Changes` table covering each import process.  The `Reason` field will contain the name of the parser.

Separate to that, how does this import flow-chart look?
![Import Flow, with Error Handling](https://user-images.githubusercontent.com/1108513/75612345-76e1ac80-5b1a-11ea-9a5f-eeb4863a2dc2.png)

**Comment by robintw** [comment]
That looks good. A couple of questions:

1. What is the difference between 'Store Errors' and 'Store Failures'? Is 'Store Failures' actually meant to come after the 'Loop through tests'?

2. Do you think the client will be happy with us moving the original files? I don't know if they might be on a read-only network share, or whether they want them kept in the original file structure.

**Comment by IanMayo** [comment]
1. Yes, I think you're right.
2. At two client meetings I've proposed this as a way of tidily allowing Pepys to process a folder of files. Each time they've been quite pleased with the strategy.  Their position may change with time, but they are happy with this initial strategy.

**Comment by robintw** [comment]
Excellent - I think this is a good way forward then :)
