### ISSUE TITLE
Make Postgres tests skip properly if Postgres setup fails

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#951]
## 🐞 Overview
Nearly all the tests that use Postgres have some code like this in the class `setUp` function:

```
except RuntimeError:
      print("PostgreSQL database couldn't be created! Test is skipping.")
      return
```
and
```
except Exception:
    print("Database schema and data population failed! Test is skipping.")
```

Unfortunately, the print statement is a lie... (!) The test doesn't skip, it just prints that message, and the test then probably fails later on for some other reason.

We should alter this so that the test actually skips, or fails, rather than just printing a message that will rarely (if ever) be seen.

This should be fixable with some clever find/replace.

**Comment by robintw** [comment]
Just looking at this @IanMayo, and it would be a fairly easy fix - but what do we want to do if we can't get the testing postgres database working. I don't think we actually want to skip the test - we probably want to fail, but with an exception that clearly says that the Postgres setup isn't working. Does that sound sensible?

**Comment by IanMayo** [comment]
There are occasions when the dev setup works for everything except Postgres.  This would be sufficient to do some non PG-dependent development.  The PR would still perform Postgres tests on GitHub.

So, if the tests still run to the end - and the dev can see it's just the PG tests that failed, then I'm happy with that.
