### ISSUE TITLE
Treat warnings as errors when running tests on CI

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#955]
## 🐞 Overview
At the moment, warnings are printed out when running pytest, but don't cause an error - so would allow the CI to pass. We don't want any warnings, so we should use the appropriate options to pytest to convert warnings to errors, and therefore make the tests fail if there are any warnings.

This is particularly useful for me when testing the new SQLAlchemy version, as I need to check for deprecation warnings, but it is something we should do anyway as it will be useful elsewhere.

**Comment by IanMayo** [comment]
Fully support this - particularly if we're currently at/near `zero warnings`.
