### ISSUE TITLE
Output value of build-date, not name

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#959]
## Version

0.0.26

## 🐞 Description

It is only possible to test the presence of `build_date` in the changes log using a release of Pepys

Pepys is outputting the variable name, not the value.  Suspect we have a missing `f` marker.

![image](https://user-images.githubusercontent.com/1108513/129552155-027eae10-8685-4707-9480-9b69b5d23f54.png)

While this is relatively low priority (since we have the build version), it's probably only seconds to fix.

**Comment by robintw** [comment]
Ah drat, fixing now.

**Comment by IanMayo** [comment]
Fixed in #960
