### ISSUE TITLE
Disable old version of Pepys from connecting to database

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#964]
## 🐞 Overview
An old version of Pepys somewhere on the client network is causing significant problems for us and the clients.

We want to disable this old version, without being able to modify its code in any way.

One way to do this would be to change the code that parses the environment variable into the path for the Pepys config file. At the moment, the environment variable is set like this: 

```PEPYS_CONFIG_FILE=/Users/robin/Documents/IanMayo/pepys_config.ini```

We could change it to something like:

```PEPYS_CONFIG_FILE=PEPYS/Users/robin/Documents/IanMayo/pepys_config.ini```

and then alter the code that reads the variable to strip the `PEPYS` off the beginning. The old code wouldn't know to do this, and would therefore try to read a file with that name, and give an error like:

```
Pepys config file not found at location: 'PEPYS/Users/robin/Documents/IanMayo/pepys_config.ini'.
```

(The `PEPYS` string could be any string that we could stick at the front of the path to make it invalid.)

Part of me thinks this is a bit of a 'yucky' solution, but it would definitely work, and would stop the old version of Pepys in its tracks.

To make this sort of problem easier to solve in future, we could create a table in the database called something like `InvalidClientVersions`, which Pepys checks on startup, and if it finds its version number listed in there then it stops and gives an error. This gives us a 'kill switch' that would allow us to disable specific versions of Pepys by simply editing the database (either in pgAdmin, or through an interface we could provide in Pepys Admin).

What do you think @IanMayo?

**Comment by IanMayo** [comment]
@robintw - this is just the _innovative_ kind of fix I was hoping for.

Yes, it's a bit `yucky`.  It also means the users can't use the file-browser in the `Environment Variables` control panel to navigate to the `.ini` file.

Aah, what if we mangle the contents of the `.ini` file?  Just change the name of `db_type` or `db_name` fields.  We then update the shared `.ini` file they use on their network and legacy versions will fail to connect. Obvs we'll also have to update the documentation.  If we do change the field name, when we load the `.ini` but the field is missing, we can provide guidance that the ini format has changed.

What do you think @robintw ?

**Comment by robintw** [comment]
That's a better idea @IanMayo - yes.

I've just tested changing `db_type` to `database_type` in the ini file, and I get the following error:

```
Traceback (most recent call last):
  File "/Users/robin/anaconda3/envs/pepys_sa14/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/robin/anaconda3/envs/pepys_sa14/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/robin/Documents/IanMayo/pepys-import/pepys_admin/cli.py", line 7, in <module>
    import config
  File "/Users/robin/Documents/IanMayo/pepys-import/config.py", line 36, in <module>
    DB_TYPE = config.get("database", "db_type")
  File "/Users/robin/anaconda3/envs/pepys_sa14/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'db_type' in section: 'database'
```

Note: this does not fail if you change the name of `db_username`, `db_password` or `db_port`.

We'll need to update the documentation, and maybe even put a comment in the ini file (can we have comments there?) which notes why one of the config parameters doesn't follow the same name style as the rest of them. (Alternatively, we change all of them to `database_X` - which would also work).

We should make sure the error message is changed to say that you may be using an old version of Pepys, and to check with an administrator (rather than just editing the ini file!).

**Comment by robintw** [comment]
Where does this come in the current priority list @IanMayo? I think it should be reasonably high up the list, as we could run into other problems again because of the old version of Pepys causing problems. However, it would take some work with MWC to change the config file etc.

**Comment by IanMayo** [comment]
@SamWilliams-dev - we talked about this task today.

Please ensure you include these steps:
* [ ] if database_type parameter is missing from the config file provide below warning, then exit
* [ ] create a config file that's deliberately in the legacy format, and test that both the warning gets shown, and the app exits

Warning on missing `database_type`:
```
Database connection type ('database_type') missing. This may be because your config file needs to be updated by converting `db_xxx` to `database_xxx`.
```
