### ISSUE TITLE
Import REP Comments

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#965]
## :speech_balloon: Brief description of feature

The clients have some converters that can convert assorted narrative document types into Debrief's `.rep` `NARRATIVE` & `NARRATIVE2` formats.

If Pepys can import this file format it will _open the door_ to supporting a wide range of data sources.  JCHAT was the example provided today.  The client's REP converter combines JChat from multiple channels into one.

## :bangbang: Business impact

* Provide greater context & tactical thinking to analysis process

### :rocket: Efficiency of analysis
* Reduce volume of manual file-wrangling

### Effectiveness of analysis
* Provide detail otherwise missing from analysis process

## :100: Acceptance criteria
* [ ] Load sample of REP comments in both `NARRATIVE` and `NARRATIVE2` formats.

**Comment by robintw** [comment]
I'm pretty sure we support NARRATIVE and NARRATIVE2 formats in REP already - see, for example https://github.com/debrief/pepys-import/blob/develop/importers/replay_comment_importer.py#L34

**Comment by IanMayo** [comment]
Well, that was easy :-)

Thanks @robintw
