### ISSUE TITLE
Deal with Codacy/pylint warnings about no-self-use in tests

### ISSUE THREAD

**Issue by robintw** [debrief/pepys-import#974]
## 🐞 Overview
The Codacy static analysis tool is giving lots of warnings about methods that could be functions. This occurs when you have a method defined like this:

```
class Blah:
    def method_here(self):
         # Code here
         # which never accesses self
```

The analysis warns that your `method_here` could actually be a standalone function, as it never actually accesses anything on the class. In general this is a pretty good warning, but it is being triggered a lot by some of our old-style tests in the Pepys codebase.

The old-style way of writing Python tests (using the `unittest` framework, which is based on JUnit from Java) is to write a test class which inherits from `unittest.TestCase` and then have all the tests as methods within that class. If this is a test that doesn't require any sort of setup or teardown, then the methods inside the test class will never access `self` - and thus will trigger this warning. The new-style way of writing Python tests is to write them as standalone functions, and only use test classes when you need particular setup or teardown (like creating/deleting a database at the start/end of the test).

The cleanest way to deal with this would be to switch all tests that don't _require_ a class to be standalone functions, but that will be a lot of boring work across the codebase and probably isn't a high priority.

Another approach would be to disable this warning. The underlying tool that the warning comes from is pylint, so you can use a pylint config file to turn off the `no-self-use` warning. However, this would disable them everywhere. We could put comments in the test functions to disable them for that test, but that would require littering the codebase with comments. A better option would be to put comments at the top of all of the test files that use old-style tests to disable the warning for that file - something like `# pylint: disable=no-self-use` at the top of the file should work.

The other alternative is to do nothing and just ignore the warnings if they come from a test file.

What do you think is best? I think I'd lean towards putting comments at the top of all of the old-style test files.

**Comment by robintw** [comment]
In the meantime, of course, @SamWilliams-dev can ignore this Codacy warning for test methods.

**Comment by IanMayo** [comment]
Putting the comment at the top of old-style tests seems a valid solution to me.
