### ISSUE TITLE
As an internal/external reviewer I wish to be able to see a live version of Pepys-Timeline

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#983]
For the original `pepys-timeline` we had Heroku hosting of the timeline viewer.

As we push ahead with `timeline` changes before and during JW 21/2, it would be useful for us (and the analysts) to view a live preview of `pepys-timeline`.

It was triggered by this file:
https://github.com/debrief/pepys-timeline/blob/main/Procfile

The timeline changed (slightly) as it transitioned into Pepys-Admin, but it would be useful if we had a single-line of Python to open it.

This tasks covers creating Heroku Hosting, making changes (if necessary) to get timeline hosted in Heroku, and the Heroku config to show the timeline viewer.

We have to provide the database details to heroku in a safe way.  _Maybe_ we need to extend Pepys to allow access of fields from environment variables that we configure in Heroku.  Or, _maybe_ we provide a `.ini` file in the repo that has the encrypted password.  Hmm, maybe not - since that could allow malicious use of Pepys-Admin on our demo data.

**Comment by robintw** [comment]
I thought I vaguely remembered this...and it turns out it's all setup already. See https://dashboard.heroku.com/apps/pepys-import for the app config, and https://pepys-import.herokuapp.com/ for the app itself. It is connected to TracStor and shows the correct serials if you choose the right time period (late Dec 2020 to early Feb 2021, for example).

I'm just setting up automatic deployment of 'review apps' based on PRs.

**Comment by robintw** [comment]
All working now! :)

**Comment by IanMayo** [comment]
Hmm, we may be wishing the `config.ini` params. It appears to be looking for port `0`:
![image](https://user-images.githubusercontent.com/1108513/133063393-5346d45b-6f29-4271-8b68-087d3f0dc464.png)

Note: the `develop` branch does work ok, it _appears_ to last be updated in May:
![image](https://user-images.githubusercontent.com/1108513/133063476-08d70ea1-951c-484c-bcda-07088a153028.png)

**Comment by robintw** [comment]
Fixed now. The Heroku 'secrets' didn't copy across to the new pipeline, and they are used to initialise the secrets for each review app. I've regenerated a couple of review apps now, and they all work fine - so this should work fine for any subsequent PRs. For any PRs that are currently open and don't work, you can go into the Heroku dashboard, and delete and then recreate the review app, and it'll pick up the new secrets.
