### ISSUE TITLE
As a Pepys developer I'd like to access a hosted development environment in order to perform maintenance away from a dev machine

### ISSUE THREAD

**Issue by IanMayo** [debrief/pepys-import#989]
## :speech_balloon: Brief description of feature

GitHub offers development codespaces for repos. Use of such a codespace would a developer to be up & running in a very short time - particularly for non_GUI tasks.

## :bangbang: Business impact

I don't have quick access to a Python development environment that is suitably configured for Pepys dev.

I'm doing some tidying to a PR, and it would be really convenient if I could jump into a suitably configured workspace, update (fix) the tests in the PR, and re-submit it.

This bring zero immediate analyst benefit,  but it may just _save the day_ one day - through the provision of a quick-turnaround fix away from a development workstation.

### :rocket: Efficiency of analysis
Nil.
### Effectiveness of analysis
Nil.
## :100: Acceptance criteria

* [ ] Instructions on repo on how to access development codespace
* [ ] Brief instructions on running tests or running Pepys from CLI in hosted codespace

More details on this capability here:   https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-python-project-for-codespaces

Note: the above may incur a cost.  We'll have to discuss the size/impact of this cost.

Note: it appears I have a `develop` codespace already, we'd want to create them on a per-branch basis, I guess.  Aah, or we just switch branches at the command-line (or via the VS-Code git UI).

![image](https://user-images.githubusercontent.com/1108513/133088224-d1ca876c-aa6b-459f-a548-906998f7a82a.png)

**Comment by robintw** [comment]
It seems that to create a codespace at all, now that they've started charging (which started yesterday), you have to change a setting for the organisation to give a spending limit. If you're happy to spend some money on this, do you want to go ahead and set a spending limit, then I should be able to create a codespace in the organisation and do some config.

See https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-codespaces

**Comment by IanMayo** [comment]
Ok, $20/month spending limit assigned.

**Comment by robintw** [comment]
(No rush for this tonight - I'm stopping shortly)

Thanks. I think Codespaces also have to be turned on following the instructions at https://docs.github.com/en/codespaces/managing-codespaces-for-your-organization/enabling-codespaces-for-your-organization first.

**Comment by IanMayo** [comment]
Hmm, have set spending limit for Debrief organisation:
![image](https://user-images.githubusercontent.com/1108513/133391558-cc5547d2-c2aa-4347-afcf-4ba9195bd684.png)

But, `Codespaces` doesn't appear on the Organisation settings:
![image](https://user-images.githubusercontent.com/1108513/133391658-bb3b540a-9496-49f4-ac8d-e927ec93585d.png)

**Comment by robintw** [comment]
Hmm, that's weird. Also, the screenshot of the spending limit screen shows the spending limit as applying to Actions and Packages, and not Codespaces.

The docs say:
>Codespaces is available for organizations using GitHub Team or GitHub Enterprise Cloud. For more information, see "GitHub's products."

Maybe that doesn't cover our organisation?

**Comment by IanMayo** [comment]
Aah, maybe that's it.  It will be quite a burden to start paying per team-member, per month.
![image](https://user-images.githubusercontent.com/1108513/133395096-010bd069-b72e-44a1-bdd0-b6eec8a961b4.png)

But, it does seem like I have `personal` access to codespaces - from the `Code` drop-down:
![image](https://user-images.githubusercontent.com/1108513/133395279-943df979-0caf-41d2-aa7b-321d16e7ba84.png)

**Comment by robintw** [comment]
Yeah, I don't have that on my dropdown:

![image](https://user-images.githubusercontent.com/296686/133395493-c326928d-bcc5-453a-8c53-e50dad7434d6.png)

Possibly because I'm not paying for Github at all.

If you want me to try and set things up for Codespaces I can have a go with editing the right files in the repo and then you can test it, and we can screenshare if necessary to get it working. Want me to have a go?

**Comment by IanMayo** [comment]
Aah yes - I am on a paid subscription.

Yes please - I'd be interested in giving it a go.  I've realised that being able to `develop in the cloud` may open opportunities for development/fixes from client networks without needing custom installs.

**Comment by IanMayo** [comment]
Fixed in #993
